// Code generated by MockGen. DO NOT EDIT.
// Source: registry_clients.go
//
// Generated by this command:
//
//	mockgen -source=registry_clients.go -destination=registry_clients_mock_test.go -package=release
//

// Package release is a generated GoMock package.
package release

import (
	reflect "reflect"

	clients "github.com/Stackdome/stackdome/pkg/clients"
	credentials "github.com/Stackdome/stackdome/pkg/credentials"
	gomock "go.uber.org/mock/gomock"
)

// MockregistryClientProvider is a mock of registryClientProvider interface.
type MockregistryClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MockregistryClientProviderMockRecorder
	isgomock struct{}
}

// MockregistryClientProviderMockRecorder is the mock recorder for MockregistryClientProvider.
type MockregistryClientProviderMockRecorder struct {
	mock *MockregistryClientProvider
}

// NewMockregistryClientProvider creates a new mock instance.
func NewMockregistryClientProvider(ctrl *gomock.Controller) *MockregistryClientProvider {
	mock := &MockregistryClientProvider{ctrl: ctrl}
	mock.recorder = &MockregistryClientProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockregistryClientProvider) EXPECT() *MockregistryClientProviderMockRecorder {
	return m.recorder
}

// ClientFor mocks base method.
func (m *MockregistryClientProvider) ClientFor(resolved *credentials.ResolvedRegistryCredential) (clients.RegistryClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientFor", resolved)
	ret0, _ := ret[0].(clients.RegistryClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientFor indicates an expected call of ClientFor.
func (mr *MockregistryClientProviderMockRecorder) ClientFor(resolved any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientFor", reflect.TypeOf((*MockregistryClientProvider)(nil).ClientFor), resolved)
}
