apiVersion: core.stackdome.io/v1alpha1
kind: StackResource
metadata:
  name: db
  namespace: stackdome-control-plane
  labels:
    app.kubernetes.io/part-of: stackdome-platform
    app.kubernetes.io/managed-by: stackdome-installer
    stackdome.io/bootstrap: "true"
    core.stackdome.io/stack-name: stackdome-platform
  ownerReferences:
    - apiVersion: core.stackdome.io/v1alpha1
      kind: Stack
      name: stackdome-platform
      uid: "{{.StackUID}}"
spec:
  workloadType: {{.DBWorkloadType}}
  imageSpec:
    image: postgres:16-alpine
  ports:
    - name: postgres
      number: 5432
      protocol: tcp
      exposeToPublic: false
  volumeMounts:
    - sourceVolume: stackdome-db-data
      destination: /var/lib/postgresql/data
  environmentVariables:
    - name: POSTGRES_DB
      value: stackdome
    - name: POSTGRES_USER
      value: stackdome
    - name: POSTGRES_PASSWORD
      value: "{{.DBPassword}}"
