apiVersion: core.stackdome.io/v1alpha1
kind: Stack
metadata:
  name: stackdome-platform
  namespace: stackdome-control-plane
  labels:
    app.kubernetes.io/part-of: stackdome-platform
    app.kubernetes.io/managed-by: stackdome-installer
    stackdome.io/bootstrap: "true"
spec:
  resourceNames:
    - api-server
    - db
