openapi: 3.0.0
info:
  title: stackdome-api-server
  version: 0.0.1
  description: stackdome-api-server
paths:
  /api/v1/users:
    post:
      summary: Create new user
      description: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/users/{id}:
    get:
      security:
        - Bearer: []
      summary: Get a user
      description: Get a user
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: User fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/auth/login:
    post:
      summary: User login
      description: Authenticate user and generate an access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/workspace-provision-requests:
    post:
      summary: Create a new workpace provision request object
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceProvisionRequest'
      responses:
        '201':
          description: WorkspaceProvisionRequest added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceProvisionRequest'
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /api/v1/workspace-provision-requests/{id}:
    get:
      summary: Get a workspace provision request object by ID
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: WorkspaceProvisionRequest details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceProvisionRequest'
        '401':
          description: Unauthorized
        '404':
          description: WorkspaceProvisionRequest object not found
        '500':
          description: Internal server error
    put:
      summary: Update a WorkspaceProvisionRequest
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceProvisionRequest'
      responses:
        '200':
          description: WorkspaceProvisionRequest updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceProvisionRequest'
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized
        '404':
          description: WorkspaceProvisionRequest not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a WorkspaceProvisionRequest
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: WorkspaceProvisionRequest deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: WorkspaceProvisionRequest not found
        '500':
          description: Internal server error
  /api/v1/clusters:
    post:
      summary: Create a new cluster
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cluster'
      responses:
        '201':
          description: Cluster added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster'
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

    get:
      summary: Get all clusters
      security:
        - Bearer: []
      responses:
        '200':
          description: List of clusters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cluster'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/v1/clusters/{id}:
    get:
      summary: Get a cluster by ID
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Cluster details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster'
        '401':
          description: Unauthorized
        '404':
          description: Cluster not found
        '500':
          description: Internal server error

    put:
      summary: Update a cluster
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cluster'
      responses:
        '200':
          description: Cluster updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster'
        '400':
          description: Invalid request payload
        '401':
          description: Unauthorized
        '404':
          description: Cluster not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a cluster
      security:
        - Bearer: []
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Cluster deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Cluster not found
        '500':
          description: Internal server error

components:
  parameters:
    id:
      name: id
      in: path
      description: The id of record
      required: true
      schema:
        type: string
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: User's ID
        name:
          type: string
          description: User's name
        username:
          type: string
          description: User's username
        email:
          type: string
          format: email
          description: User's email address
        organisation:
          type: string
          description: User's organisation
        role:
          type: string
          description: User's role
        organisation_id:
          type: integer
          description: OrganisationID
    UserCreateRequest:
      type: object
      required:
      - name
      - email
      - password
      - organisation_id
      properties:
        name:
          type: string
          description: User's name
        username:
          type: string
          description: User's username
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          description: Users desired password
        organisation:
          type: string
          description: User's organisation
        organisation_id:
          type: integer
          description: OrganisationID
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: User's email
        password:
          type: string
          format: password
          description: User's password
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: Access token for authenticated requests
        expires_in:
          type: integer
          description: Token expiration time in seconds
    WorkspaceProvisionRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
        org_id:
          type: integer
        ssh_public_key:
          type: string
        status:
          $ref: '#/components/schemas/WorkspaceProvisionRequestStatus'
        state:
          type: string
        message:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - ssh_public_key
    WorkspaceProvisionRequestStatus:
      type: object
      properties:
        workspace_namespace:
          type: string
          nullable: true
        workspace_service_accountname:
          type: string
          nullable: true
        workspace_serviceaccount_token:
          type: string
          nullable: true
        cluster_ca_cert:
          type: string
          nullable: true
        cluster_url:
          type: string
          nullable: true
        domain:
          type: string
          nullable: true
    Cluster:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        organisation_id:
          type: string
        default:
          type: boolean
        cluster_url:
          type: string
        cluster_ca_data:
          type: string
        client_cert_data:
          type: string
        client_key_data:
          type: string
    Error:
      allOf:
        - $ref: '#/components/schemas/ObjectReference'
        - type: object
          properties:
            code:
              type: string
            reason:
              type: string
            operation_id:
              type: string
    ErrorList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      allOf:
        - $ref: '#/components/schemas/List'
    List:
      type: object
      properties:
        kind:
          type: string
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
      required:
        - kind
        - page
        - size
        - total
        - items
    ObjectReference:
      type: object
      properties:
        id:
          type: string
        kind:
          type: string
        href:
          type: string