/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SecretReference struct for SecretReference
type SecretReference struct {
	// UUID of the Stackdome secret
	SecretId string `json:"secret_id"`
	// Key within the secret containing the value
	Key string `json:"key"`
}

// NewSecretReference instantiates a new SecretReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretReference(secretId string, key string) *SecretReference {
	this := SecretReference{}
	this.SecretId = secretId
	this.Key = key
	return &this
}

// NewSecretReferenceWithDefaults instantiates a new SecretReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretReferenceWithDefaults() *SecretReference {
	this := SecretReference{}
	return &this
}

// GetSecretId returns the SecretId field value
func (o *SecretReference) GetSecretId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretId
}

// GetSecretIdOk returns a tuple with the SecretId field value
// and a boolean to check if the value has been set.
func (o *SecretReference) GetSecretIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretId, true
}

// SetSecretId sets field value
func (o *SecretReference) SetSecretId(v string) {
	o.SecretId = v
}

// GetKey returns the Key field value
func (o *SecretReference) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *SecretReference) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *SecretReference) SetKey(v string) {
	o.Key = v
}

func (o SecretReference) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["secret_id"] = o.SecretId
	}
	if true {
		toSerialize["key"] = o.Key
	}
	return json.Marshal(toSerialize)
}

type NullableSecretReference struct {
	value *SecretReference
	isSet bool
}

func (v NullableSecretReference) Get() *SecretReference {
	return v.value
}

func (v *NullableSecretReference) Set(val *SecretReference) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretReference) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretReference(val *SecretReference) *NullableSecretReference {
	return &NullableSecretReference{value: val, isSet: true}
}

func (v NullableSecretReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
