/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WorkspaceUserStatus struct for WorkspaceUserStatus
type WorkspaceUserStatus struct {
	ObservedVersion       *int32                                          `json:"observed_version,omitempty"`
	ProvisionedNamespaces []WorkspaceUserStatusProvisionedNamespacesInner `json:"provisioned_namespaces,omitempty"`
	ServiceAccountName    NullableString                                  `json:"service_account_name,omitempty"`
	ServiceaccountToken   NullableString                                  `json:"serviceaccount_token,omitempty"`
	ClusterCaCert         NullableString                                  `json:"cluster_ca_cert,omitempty"`
	ClusterUrl            NullableString                                  `json:"cluster_url,omitempty"`
	Conditions            []Condition                                     `json:"conditions,omitempty"`
}

// NewWorkspaceUserStatus instantiates a new WorkspaceUserStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceUserStatus() *WorkspaceUserStatus {
	this := WorkspaceUserStatus{}
	return &this
}

// NewWorkspaceUserStatusWithDefaults instantiates a new WorkspaceUserStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceUserStatusWithDefaults() *WorkspaceUserStatus {
	this := WorkspaceUserStatus{}
	return &this
}

// GetObservedVersion returns the ObservedVersion field value if set, zero value otherwise.
func (o *WorkspaceUserStatus) GetObservedVersion() int32 {
	if o == nil || o.ObservedVersion == nil {
		var ret int32
		return ret
	}
	return *o.ObservedVersion
}

// GetObservedVersionOk returns a tuple with the ObservedVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceUserStatus) GetObservedVersionOk() (*int32, bool) {
	if o == nil || o.ObservedVersion == nil {
		return nil, false
	}
	return o.ObservedVersion, true
}

// HasObservedVersion returns a boolean if a field has been set.
func (o *WorkspaceUserStatus) HasObservedVersion() bool {
	if o != nil && o.ObservedVersion != nil {
		return true
	}

	return false
}

// SetObservedVersion gets a reference to the given int32 and assigns it to the ObservedVersion field.
func (o *WorkspaceUserStatus) SetObservedVersion(v int32) {
	o.ObservedVersion = &v
}

// GetProvisionedNamespaces returns the ProvisionedNamespaces field value if set, zero value otherwise.
func (o *WorkspaceUserStatus) GetProvisionedNamespaces() []WorkspaceUserStatusProvisionedNamespacesInner {
	if o == nil || o.ProvisionedNamespaces == nil {
		var ret []WorkspaceUserStatusProvisionedNamespacesInner
		return ret
	}
	return o.ProvisionedNamespaces
}

// GetProvisionedNamespacesOk returns a tuple with the ProvisionedNamespaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceUserStatus) GetProvisionedNamespacesOk() ([]WorkspaceUserStatusProvisionedNamespacesInner, bool) {
	if o == nil || o.ProvisionedNamespaces == nil {
		return nil, false
	}
	return o.ProvisionedNamespaces, true
}

// HasProvisionedNamespaces returns a boolean if a field has been set.
func (o *WorkspaceUserStatus) HasProvisionedNamespaces() bool {
	if o != nil && o.ProvisionedNamespaces != nil {
		return true
	}

	return false
}

// SetProvisionedNamespaces gets a reference to the given []WorkspaceUserStatusProvisionedNamespacesInner and assigns it to the ProvisionedNamespaces field.
func (o *WorkspaceUserStatus) SetProvisionedNamespaces(v []WorkspaceUserStatusProvisionedNamespacesInner) {
	o.ProvisionedNamespaces = v
}

// GetServiceAccountName returns the ServiceAccountName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkspaceUserStatus) GetServiceAccountName() string {
	if o == nil || o.ServiceAccountName.Get() == nil {
		var ret string
		return ret
	}
	return *o.ServiceAccountName.Get()
}

// GetServiceAccountNameOk returns a tuple with the ServiceAccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspaceUserStatus) GetServiceAccountNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceAccountName.Get(), o.ServiceAccountName.IsSet()
}

// HasServiceAccountName returns a boolean if a field has been set.
func (o *WorkspaceUserStatus) HasServiceAccountName() bool {
	if o != nil && o.ServiceAccountName.IsSet() {
		return true
	}

	return false
}

// SetServiceAccountName gets a reference to the given NullableString and assigns it to the ServiceAccountName field.
func (o *WorkspaceUserStatus) SetServiceAccountName(v string) {
	o.ServiceAccountName.Set(&v)
}

// SetServiceAccountNameNil sets the value for ServiceAccountName to be an explicit nil
func (o *WorkspaceUserStatus) SetServiceAccountNameNil() {
	o.ServiceAccountName.Set(nil)
}

// UnsetServiceAccountName ensures that no value is present for ServiceAccountName, not even an explicit nil
func (o *WorkspaceUserStatus) UnsetServiceAccountName() {
	o.ServiceAccountName.Unset()
}

// GetServiceaccountToken returns the ServiceaccountToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkspaceUserStatus) GetServiceaccountToken() string {
	if o == nil || o.ServiceaccountToken.Get() == nil {
		var ret string
		return ret
	}
	return *o.ServiceaccountToken.Get()
}

// GetServiceaccountTokenOk returns a tuple with the ServiceaccountToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspaceUserStatus) GetServiceaccountTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceaccountToken.Get(), o.ServiceaccountToken.IsSet()
}

// HasServiceaccountToken returns a boolean if a field has been set.
func (o *WorkspaceUserStatus) HasServiceaccountToken() bool {
	if o != nil && o.ServiceaccountToken.IsSet() {
		return true
	}

	return false
}

// SetServiceaccountToken gets a reference to the given NullableString and assigns it to the ServiceaccountToken field.
func (o *WorkspaceUserStatus) SetServiceaccountToken(v string) {
	o.ServiceaccountToken.Set(&v)
}

// SetServiceaccountTokenNil sets the value for ServiceaccountToken to be an explicit nil
func (o *WorkspaceUserStatus) SetServiceaccountTokenNil() {
	o.ServiceaccountToken.Set(nil)
}

// UnsetServiceaccountToken ensures that no value is present for ServiceaccountToken, not even an explicit nil
func (o *WorkspaceUserStatus) UnsetServiceaccountToken() {
	o.ServiceaccountToken.Unset()
}

// GetClusterCaCert returns the ClusterCaCert field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkspaceUserStatus) GetClusterCaCert() string {
	if o == nil || o.ClusterCaCert.Get() == nil {
		var ret string
		return ret
	}
	return *o.ClusterCaCert.Get()
}

// GetClusterCaCertOk returns a tuple with the ClusterCaCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspaceUserStatus) GetClusterCaCertOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClusterCaCert.Get(), o.ClusterCaCert.IsSet()
}

// HasClusterCaCert returns a boolean if a field has been set.
func (o *WorkspaceUserStatus) HasClusterCaCert() bool {
	if o != nil && o.ClusterCaCert.IsSet() {
		return true
	}

	return false
}

// SetClusterCaCert gets a reference to the given NullableString and assigns it to the ClusterCaCert field.
func (o *WorkspaceUserStatus) SetClusterCaCert(v string) {
	o.ClusterCaCert.Set(&v)
}

// SetClusterCaCertNil sets the value for ClusterCaCert to be an explicit nil
func (o *WorkspaceUserStatus) SetClusterCaCertNil() {
	o.ClusterCaCert.Set(nil)
}

// UnsetClusterCaCert ensures that no value is present for ClusterCaCert, not even an explicit nil
func (o *WorkspaceUserStatus) UnsetClusterCaCert() {
	o.ClusterCaCert.Unset()
}

// GetClusterUrl returns the ClusterUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkspaceUserStatus) GetClusterUrl() string {
	if o == nil || o.ClusterUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.ClusterUrl.Get()
}

// GetClusterUrlOk returns a tuple with the ClusterUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspaceUserStatus) GetClusterUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClusterUrl.Get(), o.ClusterUrl.IsSet()
}

// HasClusterUrl returns a boolean if a field has been set.
func (o *WorkspaceUserStatus) HasClusterUrl() bool {
	if o != nil && o.ClusterUrl.IsSet() {
		return true
	}

	return false
}

// SetClusterUrl gets a reference to the given NullableString and assigns it to the ClusterUrl field.
func (o *WorkspaceUserStatus) SetClusterUrl(v string) {
	o.ClusterUrl.Set(&v)
}

// SetClusterUrlNil sets the value for ClusterUrl to be an explicit nil
func (o *WorkspaceUserStatus) SetClusterUrlNil() {
	o.ClusterUrl.Set(nil)
}

// UnsetClusterUrl ensures that no value is present for ClusterUrl, not even an explicit nil
func (o *WorkspaceUserStatus) UnsetClusterUrl() {
	o.ClusterUrl.Unset()
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *WorkspaceUserStatus) GetConditions() []Condition {
	if o == nil || o.Conditions == nil {
		var ret []Condition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceUserStatus) GetConditionsOk() ([]Condition, bool) {
	if o == nil || o.Conditions == nil {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *WorkspaceUserStatus) HasConditions() bool {
	if o != nil && o.Conditions != nil {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []Condition and assigns it to the Conditions field.
func (o *WorkspaceUserStatus) SetConditions(v []Condition) {
	o.Conditions = v
}

func (o WorkspaceUserStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ObservedVersion != nil {
		toSerialize["observed_version"] = o.ObservedVersion
	}
	if o.ProvisionedNamespaces != nil {
		toSerialize["provisioned_namespaces"] = o.ProvisionedNamespaces
	}
	if o.ServiceAccountName.IsSet() {
		toSerialize["service_account_name"] = o.ServiceAccountName.Get()
	}
	if o.ServiceaccountToken.IsSet() {
		toSerialize["serviceaccount_token"] = o.ServiceaccountToken.Get()
	}
	if o.ClusterCaCert.IsSet() {
		toSerialize["cluster_ca_cert"] = o.ClusterCaCert.Get()
	}
	if o.ClusterUrl.IsSet() {
		toSerialize["cluster_url"] = o.ClusterUrl.Get()
	}
	if o.Conditions != nil {
		toSerialize["conditions"] = o.Conditions
	}
	return json.Marshal(toSerialize)
}

type NullableWorkspaceUserStatus struct {
	value *WorkspaceUserStatus
	isSet bool
}

func (v NullableWorkspaceUserStatus) Get() *WorkspaceUserStatus {
	return v.value
}

func (v *NullableWorkspaceUserStatus) Set(val *WorkspaceUserStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceUserStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceUserStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceUserStatus(val *WorkspaceUserStatus) *NullableWorkspaceUserStatus {
	return &NullableWorkspaceUserStatus{value: val, isSet: true}
}

func (v NullableWorkspaceUserStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceUserStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
