/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// ProjectMembership struct for ProjectMembership
type ProjectMembership struct {
	Id        *string    `json:"id,omitempty"`
	ProjectId string     `json:"project_id"`
	UserId    string     `json:"user_id"`
	Role      string     `json:"role"`
	Project   *Project   `json:"project,omitempty"`
	User      *User      `json:"user,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewProjectMembership instantiates a new ProjectMembership object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectMembership(projectId string, userId string, role string) *ProjectMembership {
	this := ProjectMembership{}
	this.ProjectId = projectId
	this.UserId = userId
	this.Role = role
	return &this
}

// NewProjectMembershipWithDefaults instantiates a new ProjectMembership object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectMembershipWithDefaults() *ProjectMembership {
	this := ProjectMembership{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectMembership) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectMembership) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectMembership) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProjectMembership) SetId(v string) {
	o.Id = &v
}

// GetProjectId returns the ProjectId field value
func (o *ProjectMembership) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ProjectMembership) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ProjectMembership) SetProjectId(v string) {
	o.ProjectId = v
}

// GetUserId returns the UserId field value
func (o *ProjectMembership) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ProjectMembership) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ProjectMembership) SetUserId(v string) {
	o.UserId = v
}

// GetRole returns the Role field value
func (o *ProjectMembership) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ProjectMembership) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ProjectMembership) SetRole(v string) {
	o.Role = v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *ProjectMembership) GetProject() Project {
	if o == nil || o.Project == nil {
		var ret Project
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectMembership) GetProjectOk() (*Project, bool) {
	if o == nil || o.Project == nil {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *ProjectMembership) HasProject() bool {
	if o != nil && o.Project != nil {
		return true
	}

	return false
}

// SetProject gets a reference to the given Project and assigns it to the Project field.
func (o *ProjectMembership) SetProject(v Project) {
	o.Project = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *ProjectMembership) GetUser() User {
	if o == nil || o.User == nil {
		var ret User
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectMembership) GetUserOk() (*User, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *ProjectMembership) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given User and assigns it to the User field.
func (o *ProjectMembership) SetUser(v User) {
	o.User = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ProjectMembership) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectMembership) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ProjectMembership) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ProjectMembership) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o ProjectMembership) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["project_id"] = o.ProjectId
	}
	if true {
		toSerialize["user_id"] = o.UserId
	}
	if true {
		toSerialize["role"] = o.Role
	}
	if o.Project != nil {
		toSerialize["project"] = o.Project
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableProjectMembership struct {
	value *ProjectMembership
	isSet bool
}

func (v NullableProjectMembership) Get() *ProjectMembership {
	return v.value
}

func (v *NullableProjectMembership) Set(val *ProjectMembership) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectMembership) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectMembership) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectMembership(val *ProjectMembership) *NullableProjectMembership {
	return &NullableProjectMembership{value: val, isSet: true}
}

func (v NullableProjectMembership) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectMembership) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
