/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response struct for ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response
type ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response struct {
	Message *string `json:"message,omitempty"`
	Fenced  *bool   `json:"fenced,omitempty"`
}

// NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response instantiates a new ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response() *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response {
	this := ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response{}
	return &this
}

// NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200ResponseWithDefaults instantiates a new ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200ResponseWithDefaults() *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response {
	this := ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) SetMessage(v string) {
	o.Message = &v
}

// GetFenced returns the Fenced field value if set, zero value otherwise.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) GetFenced() bool {
	if o == nil || o.Fenced == nil {
		var ret bool
		return ret
	}
	return *o.Fenced
}

// GetFencedOk returns a tuple with the Fenced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) GetFencedOk() (*bool, bool) {
	if o == nil || o.Fenced == nil {
		return nil, false
	}
	return o.Fenced, true
}

// HasFenced returns a boolean if a field has been set.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) HasFenced() bool {
	if o != nil && o.Fenced != nil {
		return true
	}

	return false
}

// SetFenced gets a reference to the given bool and assigns it to the Fenced field.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) SetFenced(v bool) {
	o.Fenced = &v
}

func (o ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Fenced != nil {
		toSerialize["fenced"] = o.Fenced
	}
	return json.Marshal(toSerialize)
}

type NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response struct {
	value *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response
	isSet bool
}

func (v NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) Get() *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response {
	return v.value
}

func (v *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) Set(val *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response(val *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response {
	return &NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response{value: val, isSet: true}
}

func (v NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
