/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UserProjectMembership struct for UserProjectMembership
type UserProjectMembership struct {
	ProjectId      *string `json:"project_id,omitempty"`
	ProjectName    *string `json:"project_name,omitempty"`
	Role           *string `json:"role,omitempty"`
	DefaultProject *bool   `json:"default_project,omitempty"`
}

// NewUserProjectMembership instantiates a new UserProjectMembership object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserProjectMembership() *UserProjectMembership {
	this := UserProjectMembership{}
	return &this
}

// NewUserProjectMembershipWithDefaults instantiates a new UserProjectMembership object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserProjectMembershipWithDefaults() *UserProjectMembership {
	this := UserProjectMembership{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *UserProjectMembership) GetProjectId() string {
	if o == nil || o.ProjectId == nil {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProjectMembership) GetProjectIdOk() (*string, bool) {
	if o == nil || o.ProjectId == nil {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *UserProjectMembership) HasProjectId() bool {
	if o != nil && o.ProjectId != nil {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *UserProjectMembership) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *UserProjectMembership) GetProjectName() string {
	if o == nil || o.ProjectName == nil {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProjectMembership) GetProjectNameOk() (*string, bool) {
	if o == nil || o.ProjectName == nil {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *UserProjectMembership) HasProjectName() bool {
	if o != nil && o.ProjectName != nil {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *UserProjectMembership) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *UserProjectMembership) GetRole() string {
	if o == nil || o.Role == nil {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProjectMembership) GetRoleOk() (*string, bool) {
	if o == nil || o.Role == nil {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *UserProjectMembership) HasRole() bool {
	if o != nil && o.Role != nil {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *UserProjectMembership) SetRole(v string) {
	o.Role = &v
}

// GetDefaultProject returns the DefaultProject field value if set, zero value otherwise.
func (o *UserProjectMembership) GetDefaultProject() bool {
	if o == nil || o.DefaultProject == nil {
		var ret bool
		return ret
	}
	return *o.DefaultProject
}

// GetDefaultProjectOk returns a tuple with the DefaultProject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProjectMembership) GetDefaultProjectOk() (*bool, bool) {
	if o == nil || o.DefaultProject == nil {
		return nil, false
	}
	return o.DefaultProject, true
}

// HasDefaultProject returns a boolean if a field has been set.
func (o *UserProjectMembership) HasDefaultProject() bool {
	if o != nil && o.DefaultProject != nil {
		return true
	}

	return false
}

// SetDefaultProject gets a reference to the given bool and assigns it to the DefaultProject field.
func (o *UserProjectMembership) SetDefaultProject(v bool) {
	o.DefaultProject = &v
}

func (o UserProjectMembership) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ProjectId != nil {
		toSerialize["project_id"] = o.ProjectId
	}
	if o.ProjectName != nil {
		toSerialize["project_name"] = o.ProjectName
	}
	if o.Role != nil {
		toSerialize["role"] = o.Role
	}
	if o.DefaultProject != nil {
		toSerialize["default_project"] = o.DefaultProject
	}
	return json.Marshal(toSerialize)
}

type NullableUserProjectMembership struct {
	value *UserProjectMembership
	isSet bool
}

func (v NullableUserProjectMembership) Get() *UserProjectMembership {
	return v.value
}

func (v *NullableUserProjectMembership) Set(val *UserProjectMembership) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProjectMembership) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProjectMembership) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProjectMembership(val *UserProjectMembership) *NullableUserProjectMembership {
	return &NullableUserProjectMembership{value: val, isSet: true}
}

func (v NullableUserProjectMembership) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProjectMembership) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
