/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GitHubAppManifestFlow struct for GitHubAppManifestFlow
type GitHubAppManifestFlow struct {
	// GitHub App manifest to POST to github_url as the manifest form field. Absent when the hub runs a platform-wide GitHub App: github_url is then the app's install page and the browser is redirected to it.
	Manifest  map[string]interface{} `json:"manifest,omitempty"`
	GithubUrl *string                `json:"github_url,omitempty"`
	State     *string                `json:"state,omitempty"`
}

// NewGitHubAppManifestFlow instantiates a new GitHubAppManifestFlow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitHubAppManifestFlow() *GitHubAppManifestFlow {
	this := GitHubAppManifestFlow{}
	return &this
}

// NewGitHubAppManifestFlowWithDefaults instantiates a new GitHubAppManifestFlow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitHubAppManifestFlowWithDefaults() *GitHubAppManifestFlow {
	this := GitHubAppManifestFlow{}
	return &this
}

// GetManifest returns the Manifest field value if set, zero value otherwise.
func (o *GitHubAppManifestFlow) GetManifest() map[string]interface{} {
	if o == nil || o.Manifest == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Manifest
}

// GetManifestOk returns a tuple with the Manifest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitHubAppManifestFlow) GetManifestOk() (map[string]interface{}, bool) {
	if o == nil || o.Manifest == nil {
		return nil, false
	}
	return o.Manifest, true
}

// HasManifest returns a boolean if a field has been set.
func (o *GitHubAppManifestFlow) HasManifest() bool {
	if o != nil && o.Manifest != nil {
		return true
	}

	return false
}

// SetManifest gets a reference to the given map[string]interface{} and assigns it to the Manifest field.
func (o *GitHubAppManifestFlow) SetManifest(v map[string]interface{}) {
	o.Manifest = v
}

// GetGithubUrl returns the GithubUrl field value if set, zero value otherwise.
func (o *GitHubAppManifestFlow) GetGithubUrl() string {
	if o == nil || o.GithubUrl == nil {
		var ret string
		return ret
	}
	return *o.GithubUrl
}

// GetGithubUrlOk returns a tuple with the GithubUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitHubAppManifestFlow) GetGithubUrlOk() (*string, bool) {
	if o == nil || o.GithubUrl == nil {
		return nil, false
	}
	return o.GithubUrl, true
}

// HasGithubUrl returns a boolean if a field has been set.
func (o *GitHubAppManifestFlow) HasGithubUrl() bool {
	if o != nil && o.GithubUrl != nil {
		return true
	}

	return false
}

// SetGithubUrl gets a reference to the given string and assigns it to the GithubUrl field.
func (o *GitHubAppManifestFlow) SetGithubUrl(v string) {
	o.GithubUrl = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *GitHubAppManifestFlow) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitHubAppManifestFlow) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *GitHubAppManifestFlow) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *GitHubAppManifestFlow) SetState(v string) {
	o.State = &v
}

func (o GitHubAppManifestFlow) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Manifest != nil {
		toSerialize["manifest"] = o.Manifest
	}
	if o.GithubUrl != nil {
		toSerialize["github_url"] = o.GithubUrl
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	return json.Marshal(toSerialize)
}

type NullableGitHubAppManifestFlow struct {
	value *GitHubAppManifestFlow
	isSet bool
}

func (v NullableGitHubAppManifestFlow) Get() *GitHubAppManifestFlow {
	return v.value
}

func (v *NullableGitHubAppManifestFlow) Set(val *GitHubAppManifestFlow) {
	v.value = val
	v.isSet = true
}

func (v NullableGitHubAppManifestFlow) IsSet() bool {
	return v.isSet
}

func (v *NullableGitHubAppManifestFlow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitHubAppManifestFlow(val *GitHubAppManifestFlow) *NullableGitHubAppManifestFlow {
	return &NullableGitHubAppManifestFlow{value: val, isSet: true}
}

func (v NullableGitHubAppManifestFlow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitHubAppManifestFlow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
