/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// WorkspaceResourceBuild struct for WorkspaceResourceBuild
type WorkspaceResourceBuild struct {
	Id                  *string              `json:"id,omitempty"`
	Namespace           *string              `json:"namespace,omitempty"`
	WorkspaceId         *string              `json:"workspace_id,omitempty"`
	WorkspaceResourceId *string              `json:"workspace_resource_id,omitempty"`
	SourceHash          *string              `json:"source_hash,omitempty"`
	ImageRegistry       *string              `json:"image_registry,omitempty"`
	Status              *ResourceBuildStatus `json:"status,omitempty"`
	CreatedAt           *time.Time           `json:"created_at,omitempty"`
	UpdatedAt           *time.Time           `json:"updated_at,omitempty"`
}

// NewWorkspaceResourceBuild instantiates a new WorkspaceResourceBuild object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceResourceBuild() *WorkspaceResourceBuild {
	this := WorkspaceResourceBuild{}
	return &this
}

// NewWorkspaceResourceBuildWithDefaults instantiates a new WorkspaceResourceBuild object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceResourceBuildWithDefaults() *WorkspaceResourceBuild {
	this := WorkspaceResourceBuild{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WorkspaceResourceBuild) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceBuild) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WorkspaceResourceBuild) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WorkspaceResourceBuild) SetId(v string) {
	o.Id = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *WorkspaceResourceBuild) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceBuild) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *WorkspaceResourceBuild) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *WorkspaceResourceBuild) SetNamespace(v string) {
	o.Namespace = &v
}

// GetWorkspaceId returns the WorkspaceId field value if set, zero value otherwise.
func (o *WorkspaceResourceBuild) GetWorkspaceId() string {
	if o == nil || o.WorkspaceId == nil {
		var ret string
		return ret
	}
	return *o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceBuild) GetWorkspaceIdOk() (*string, bool) {
	if o == nil || o.WorkspaceId == nil {
		return nil, false
	}
	return o.WorkspaceId, true
}

// HasWorkspaceId returns a boolean if a field has been set.
func (o *WorkspaceResourceBuild) HasWorkspaceId() bool {
	if o != nil && o.WorkspaceId != nil {
		return true
	}

	return false
}

// SetWorkspaceId gets a reference to the given string and assigns it to the WorkspaceId field.
func (o *WorkspaceResourceBuild) SetWorkspaceId(v string) {
	o.WorkspaceId = &v
}

// GetWorkspaceResourceId returns the WorkspaceResourceId field value if set, zero value otherwise.
func (o *WorkspaceResourceBuild) GetWorkspaceResourceId() string {
	if o == nil || o.WorkspaceResourceId == nil {
		var ret string
		return ret
	}
	return *o.WorkspaceResourceId
}

// GetWorkspaceResourceIdOk returns a tuple with the WorkspaceResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceBuild) GetWorkspaceResourceIdOk() (*string, bool) {
	if o == nil || o.WorkspaceResourceId == nil {
		return nil, false
	}
	return o.WorkspaceResourceId, true
}

// HasWorkspaceResourceId returns a boolean if a field has been set.
func (o *WorkspaceResourceBuild) HasWorkspaceResourceId() bool {
	if o != nil && o.WorkspaceResourceId != nil {
		return true
	}

	return false
}

// SetWorkspaceResourceId gets a reference to the given string and assigns it to the WorkspaceResourceId field.
func (o *WorkspaceResourceBuild) SetWorkspaceResourceId(v string) {
	o.WorkspaceResourceId = &v
}

// GetSourceHash returns the SourceHash field value if set, zero value otherwise.
func (o *WorkspaceResourceBuild) GetSourceHash() string {
	if o == nil || o.SourceHash == nil {
		var ret string
		return ret
	}
	return *o.SourceHash
}

// GetSourceHashOk returns a tuple with the SourceHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceBuild) GetSourceHashOk() (*string, bool) {
	if o == nil || o.SourceHash == nil {
		return nil, false
	}
	return o.SourceHash, true
}

// HasSourceHash returns a boolean if a field has been set.
func (o *WorkspaceResourceBuild) HasSourceHash() bool {
	if o != nil && o.SourceHash != nil {
		return true
	}

	return false
}

// SetSourceHash gets a reference to the given string and assigns it to the SourceHash field.
func (o *WorkspaceResourceBuild) SetSourceHash(v string) {
	o.SourceHash = &v
}

// GetImageRegistry returns the ImageRegistry field value if set, zero value otherwise.
func (o *WorkspaceResourceBuild) GetImageRegistry() string {
	if o == nil || o.ImageRegistry == nil {
		var ret string
		return ret
	}
	return *o.ImageRegistry
}

// GetImageRegistryOk returns a tuple with the ImageRegistry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceBuild) GetImageRegistryOk() (*string, bool) {
	if o == nil || o.ImageRegistry == nil {
		return nil, false
	}
	return o.ImageRegistry, true
}

// HasImageRegistry returns a boolean if a field has been set.
func (o *WorkspaceResourceBuild) HasImageRegistry() bool {
	if o != nil && o.ImageRegistry != nil {
		return true
	}

	return false
}

// SetImageRegistry gets a reference to the given string and assigns it to the ImageRegistry field.
func (o *WorkspaceResourceBuild) SetImageRegistry(v string) {
	o.ImageRegistry = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WorkspaceResourceBuild) GetStatus() ResourceBuildStatus {
	if o == nil || o.Status == nil {
		var ret ResourceBuildStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceBuild) GetStatusOk() (*ResourceBuildStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WorkspaceResourceBuild) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ResourceBuildStatus and assigns it to the Status field.
func (o *WorkspaceResourceBuild) SetStatus(v ResourceBuildStatus) {
	o.Status = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WorkspaceResourceBuild) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceBuild) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WorkspaceResourceBuild) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WorkspaceResourceBuild) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *WorkspaceResourceBuild) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceBuild) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *WorkspaceResourceBuild) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *WorkspaceResourceBuild) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o WorkspaceResourceBuild) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Namespace != nil {
		toSerialize["namespace"] = o.Namespace
	}
	if o.WorkspaceId != nil {
		toSerialize["workspace_id"] = o.WorkspaceId
	}
	if o.WorkspaceResourceId != nil {
		toSerialize["workspace_resource_id"] = o.WorkspaceResourceId
	}
	if o.SourceHash != nil {
		toSerialize["source_hash"] = o.SourceHash
	}
	if o.ImageRegistry != nil {
		toSerialize["image_registry"] = o.ImageRegistry
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableWorkspaceResourceBuild struct {
	value *WorkspaceResourceBuild
	isSet bool
}

func (v NullableWorkspaceResourceBuild) Get() *WorkspaceResourceBuild {
	return v.value
}

func (v *NullableWorkspaceResourceBuild) Set(val *WorkspaceResourceBuild) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceResourceBuild) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceResourceBuild) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceResourceBuild(val *WorkspaceResourceBuild) *NullableWorkspaceResourceBuild {
	return &NullableWorkspaceResourceBuild{value: val, isSet: true}
}

func (v NullableWorkspaceResourceBuild) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceResourceBuild) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
