/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// APITokenList struct for APITokenList
type APITokenList struct {
	Items []APIToken `json:"items,omitempty"`
	Total *int32     `json:"total,omitempty"`
}

// NewAPITokenList instantiates a new APITokenList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPITokenList() *APITokenList {
	this := APITokenList{}
	return &this
}

// NewAPITokenListWithDefaults instantiates a new APITokenList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPITokenListWithDefaults() *APITokenList {
	this := APITokenList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *APITokenList) GetItems() []APIToken {
	if o == nil || o.Items == nil {
		var ret []APIToken
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APITokenList) GetItemsOk() ([]APIToken, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *APITokenList) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []APIToken and assigns it to the Items field.
func (o *APITokenList) SetItems(v []APIToken) {
	o.Items = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *APITokenList) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APITokenList) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *APITokenList) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *APITokenList) SetTotal(v int32) {
	o.Total = &v
}

func (o APITokenList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableAPITokenList struct {
	value *APITokenList
	isSet bool
}

func (v NullableAPITokenList) Get() *APITokenList {
	return v.value
}

func (v *NullableAPITokenList) Set(val *APITokenList) {
	v.value = val
	v.isSet = true
}

func (v NullableAPITokenList) IsSet() bool {
	return v.isSet
}

func (v *NullableAPITokenList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPITokenList(val *APITokenList) *NullableAPITokenList {
	return &NullableAPITokenList{value: val, isSet: true}
}

func (v NullableAPITokenList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPITokenList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
