/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StackSettings struct for StackSettings
type StackSettings struct {
	// Maximum total releases to retain per stack
	ReleaseRetentionLimit *int32 `json:"release_retention_limit,omitempty"`
	// Minimum number of successful releases to always keep
	MinSuccessfulReleases *int32 `json:"min_successful_releases,omitempty"`
	// Minutes to wait for a deploy to converge before marking it failed
	DeployTimeoutMinutes *int32 `json:"deploy_timeout_minutes,omitempty"`
}

// NewStackSettings instantiates a new StackSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackSettings() *StackSettings {
	this := StackSettings{}
	var releaseRetentionLimit int32 = 10
	this.ReleaseRetentionLimit = &releaseRetentionLimit
	var minSuccessfulReleases int32 = 5
	this.MinSuccessfulReleases = &minSuccessfulReleases
	var deployTimeoutMinutes int32 = 15
	this.DeployTimeoutMinutes = &deployTimeoutMinutes
	return &this
}

// NewStackSettingsWithDefaults instantiates a new StackSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackSettingsWithDefaults() *StackSettings {
	this := StackSettings{}
	var releaseRetentionLimit int32 = 10
	this.ReleaseRetentionLimit = &releaseRetentionLimit
	var minSuccessfulReleases int32 = 5
	this.MinSuccessfulReleases = &minSuccessfulReleases
	var deployTimeoutMinutes int32 = 15
	this.DeployTimeoutMinutes = &deployTimeoutMinutes
	return &this
}

// GetReleaseRetentionLimit returns the ReleaseRetentionLimit field value if set, zero value otherwise.
func (o *StackSettings) GetReleaseRetentionLimit() int32 {
	if o == nil || o.ReleaseRetentionLimit == nil {
		var ret int32
		return ret
	}
	return *o.ReleaseRetentionLimit
}

// GetReleaseRetentionLimitOk returns a tuple with the ReleaseRetentionLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackSettings) GetReleaseRetentionLimitOk() (*int32, bool) {
	if o == nil || o.ReleaseRetentionLimit == nil {
		return nil, false
	}
	return o.ReleaseRetentionLimit, true
}

// HasReleaseRetentionLimit returns a boolean if a field has been set.
func (o *StackSettings) HasReleaseRetentionLimit() bool {
	if o != nil && o.ReleaseRetentionLimit != nil {
		return true
	}

	return false
}

// SetReleaseRetentionLimit gets a reference to the given int32 and assigns it to the ReleaseRetentionLimit field.
func (o *StackSettings) SetReleaseRetentionLimit(v int32) {
	o.ReleaseRetentionLimit = &v
}

// GetMinSuccessfulReleases returns the MinSuccessfulReleases field value if set, zero value otherwise.
func (o *StackSettings) GetMinSuccessfulReleases() int32 {
	if o == nil || o.MinSuccessfulReleases == nil {
		var ret int32
		return ret
	}
	return *o.MinSuccessfulReleases
}

// GetMinSuccessfulReleasesOk returns a tuple with the MinSuccessfulReleases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackSettings) GetMinSuccessfulReleasesOk() (*int32, bool) {
	if o == nil || o.MinSuccessfulReleases == nil {
		return nil, false
	}
	return o.MinSuccessfulReleases, true
}

// HasMinSuccessfulReleases returns a boolean if a field has been set.
func (o *StackSettings) HasMinSuccessfulReleases() bool {
	if o != nil && o.MinSuccessfulReleases != nil {
		return true
	}

	return false
}

// SetMinSuccessfulReleases gets a reference to the given int32 and assigns it to the MinSuccessfulReleases field.
func (o *StackSettings) SetMinSuccessfulReleases(v int32) {
	o.MinSuccessfulReleases = &v
}

// GetDeployTimeoutMinutes returns the DeployTimeoutMinutes field value if set, zero value otherwise.
func (o *StackSettings) GetDeployTimeoutMinutes() int32 {
	if o == nil || o.DeployTimeoutMinutes == nil {
		var ret int32
		return ret
	}
	return *o.DeployTimeoutMinutes
}

// GetDeployTimeoutMinutesOk returns a tuple with the DeployTimeoutMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackSettings) GetDeployTimeoutMinutesOk() (*int32, bool) {
	if o == nil || o.DeployTimeoutMinutes == nil {
		return nil, false
	}
	return o.DeployTimeoutMinutes, true
}

// HasDeployTimeoutMinutes returns a boolean if a field has been set.
func (o *StackSettings) HasDeployTimeoutMinutes() bool {
	if o != nil && o.DeployTimeoutMinutes != nil {
		return true
	}

	return false
}

// SetDeployTimeoutMinutes gets a reference to the given int32 and assigns it to the DeployTimeoutMinutes field.
func (o *StackSettings) SetDeployTimeoutMinutes(v int32) {
	o.DeployTimeoutMinutes = &v
}

func (o StackSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ReleaseRetentionLimit != nil {
		toSerialize["release_retention_limit"] = o.ReleaseRetentionLimit
	}
	if o.MinSuccessfulReleases != nil {
		toSerialize["min_successful_releases"] = o.MinSuccessfulReleases
	}
	if o.DeployTimeoutMinutes != nil {
		toSerialize["deploy_timeout_minutes"] = o.DeployTimeoutMinutes
	}
	return json.Marshal(toSerialize)
}

type NullableStackSettings struct {
	value *StackSettings
	isSet bool
}

func (v NullableStackSettings) Get() *StackSettings {
	return v.value
}

func (v *NullableStackSettings) Set(val *StackSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableStackSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableStackSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackSettings(val *StackSettings) *NullableStackSettings {
	return &NullableStackSettings{value: val, isSet: true}
}

func (v NullableStackSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
