/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// ObjectStore struct for ObjectStore
type ObjectStore struct {
	Id             *string `json:"id,omitempty"`
	OrganisationId *string `json:"organisation_id,omitempty"`
	ProjectId      *string `json:"project_id,omitempty"`
	// Unique name for this object store configuration
	Name      string             `json:"name"`
	Spec      ObjectStoreSpec    `json:"spec"`
	Status    *ObjectStoreStatus `json:"status,omitempty"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
}

// NewObjectStore instantiates a new ObjectStore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectStore(name string, spec ObjectStoreSpec) *ObjectStore {
	this := ObjectStore{}
	this.Name = name
	this.Spec = spec
	return &this
}

// NewObjectStoreWithDefaults instantiates a new ObjectStore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectStoreWithDefaults() *ObjectStore {
	this := ObjectStore{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ObjectStore) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStore) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ObjectStore) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ObjectStore) SetId(v string) {
	o.Id = &v
}

// GetOrganisationId returns the OrganisationId field value if set, zero value otherwise.
func (o *ObjectStore) GetOrganisationId() string {
	if o == nil || o.OrganisationId == nil {
		var ret string
		return ret
	}
	return *o.OrganisationId
}

// GetOrganisationIdOk returns a tuple with the OrganisationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStore) GetOrganisationIdOk() (*string, bool) {
	if o == nil || o.OrganisationId == nil {
		return nil, false
	}
	return o.OrganisationId, true
}

// HasOrganisationId returns a boolean if a field has been set.
func (o *ObjectStore) HasOrganisationId() bool {
	if o != nil && o.OrganisationId != nil {
		return true
	}

	return false
}

// SetOrganisationId gets a reference to the given string and assigns it to the OrganisationId field.
func (o *ObjectStore) SetOrganisationId(v string) {
	o.OrganisationId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ObjectStore) GetProjectId() string {
	if o == nil || o.ProjectId == nil {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStore) GetProjectIdOk() (*string, bool) {
	if o == nil || o.ProjectId == nil {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ObjectStore) HasProjectId() bool {
	if o != nil && o.ProjectId != nil {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *ObjectStore) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetName returns the Name field value
func (o *ObjectStore) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ObjectStore) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ObjectStore) SetName(v string) {
	o.Name = v
}

// GetSpec returns the Spec field value
func (o *ObjectStore) GetSpec() ObjectStoreSpec {
	if o == nil {
		var ret ObjectStoreSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *ObjectStore) GetSpecOk() (*ObjectStoreSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *ObjectStore) SetSpec(v ObjectStoreSpec) {
	o.Spec = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ObjectStore) GetStatus() ObjectStoreStatus {
	if o == nil || o.Status == nil {
		var ret ObjectStoreStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStore) GetStatusOk() (*ObjectStoreStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ObjectStore) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ObjectStoreStatus and assigns it to the Status field.
func (o *ObjectStore) SetStatus(v ObjectStoreStatus) {
	o.Status = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ObjectStore) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStore) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ObjectStore) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ObjectStore) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ObjectStore) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStore) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ObjectStore) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ObjectStore) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o ObjectStore) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.OrganisationId != nil {
		toSerialize["organisation_id"] = o.OrganisationId
	}
	if o.ProjectId != nil {
		toSerialize["project_id"] = o.ProjectId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["spec"] = o.Spec
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableObjectStore struct {
	value *ObjectStore
	isSet bool
}

func (v NullableObjectStore) Get() *ObjectStore {
	return v.value
}

func (v *NullableObjectStore) Set(val *ObjectStore) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectStore) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectStore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectStore(val *ObjectStore) *NullableObjectStore {
	return &NullableObjectStore{value: val, isSet: true}
}

func (v NullableObjectStore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectStore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
