/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GCSCredentials struct for GCSCredentials
type GCSCredentials struct {
	// Reference to secret containing GCS service account key JSON
	ServiceAccountKey string `json:"service_account_key"`
}

// NewGCSCredentials instantiates a new GCSCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGCSCredentials(serviceAccountKey string) *GCSCredentials {
	this := GCSCredentials{}
	this.ServiceAccountKey = serviceAccountKey
	return &this
}

// NewGCSCredentialsWithDefaults instantiates a new GCSCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGCSCredentialsWithDefaults() *GCSCredentials {
	this := GCSCredentials{}
	return &this
}

// GetServiceAccountKey returns the ServiceAccountKey field value
func (o *GCSCredentials) GetServiceAccountKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceAccountKey
}

// GetServiceAccountKeyOk returns a tuple with the ServiceAccountKey field value
// and a boolean to check if the value has been set.
func (o *GCSCredentials) GetServiceAccountKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceAccountKey, true
}

// SetServiceAccountKey sets field value
func (o *GCSCredentials) SetServiceAccountKey(v string) {
	o.ServiceAccountKey = v
}

func (o GCSCredentials) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["service_account_key"] = o.ServiceAccountKey
	}
	return json.Marshal(toSerialize)
}

type NullableGCSCredentials struct {
	value *GCSCredentials
	isSet bool
}

func (v NullableGCSCredentials) Get() *GCSCredentials {
	return v.value
}

func (v *NullableGCSCredentials) Set(val *GCSCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableGCSCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableGCSCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGCSCredentials(val *GCSCredentials) *NullableGCSCredentials {
	return &NullableGCSCredentials{value: val, isSet: true}
}

func (v NullableGCSCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGCSCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
