/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StackPreviewConfigCreate struct for StackPreviewConfigCreate
type StackPreviewConfigCreate struct {
	Name              string               `json:"name"`
	GitRepository     PreviewGitRepository `json:"git_repository"`
	Description       *string              `json:"description,omitempty"`
	StackfilePath     *string              `json:"stackfile_path,omitempty"`
	MaxActivePreviews *int32               `json:"max_active_previews,omitempty"`
	// Env var overrides applied to every preview environment; may use secret references.
	Env         []EnvVar     `json:"env,omitempty"`
	Labels      []Label      `json:"labels,omitempty"`
	Annotations []Annotation `json:"annotations,omitempty"`
}

// NewStackPreviewConfigCreate instantiates a new StackPreviewConfigCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackPreviewConfigCreate(name string, gitRepository PreviewGitRepository) *StackPreviewConfigCreate {
	this := StackPreviewConfigCreate{}
	this.Name = name
	this.GitRepository = gitRepository
	return &this
}

// NewStackPreviewConfigCreateWithDefaults instantiates a new StackPreviewConfigCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackPreviewConfigCreateWithDefaults() *StackPreviewConfigCreate {
	this := StackPreviewConfigCreate{}
	return &this
}

// GetName returns the Name field value
func (o *StackPreviewConfigCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StackPreviewConfigCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StackPreviewConfigCreate) SetName(v string) {
	o.Name = v
}

// GetGitRepository returns the GitRepository field value
func (o *StackPreviewConfigCreate) GetGitRepository() PreviewGitRepository {
	if o == nil {
		var ret PreviewGitRepository
		return ret
	}

	return o.GitRepository
}

// GetGitRepositoryOk returns a tuple with the GitRepository field value
// and a boolean to check if the value has been set.
func (o *StackPreviewConfigCreate) GetGitRepositoryOk() (*PreviewGitRepository, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GitRepository, true
}

// SetGitRepository sets field value
func (o *StackPreviewConfigCreate) SetGitRepository(v PreviewGitRepository) {
	o.GitRepository = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *StackPreviewConfigCreate) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackPreviewConfigCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *StackPreviewConfigCreate) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *StackPreviewConfigCreate) SetDescription(v string) {
	o.Description = &v
}

// GetStackfilePath returns the StackfilePath field value if set, zero value otherwise.
func (o *StackPreviewConfigCreate) GetStackfilePath() string {
	if o == nil || o.StackfilePath == nil {
		var ret string
		return ret
	}
	return *o.StackfilePath
}

// GetStackfilePathOk returns a tuple with the StackfilePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackPreviewConfigCreate) GetStackfilePathOk() (*string, bool) {
	if o == nil || o.StackfilePath == nil {
		return nil, false
	}
	return o.StackfilePath, true
}

// HasStackfilePath returns a boolean if a field has been set.
func (o *StackPreviewConfigCreate) HasStackfilePath() bool {
	if o != nil && o.StackfilePath != nil {
		return true
	}

	return false
}

// SetStackfilePath gets a reference to the given string and assigns it to the StackfilePath field.
func (o *StackPreviewConfigCreate) SetStackfilePath(v string) {
	o.StackfilePath = &v
}

// GetMaxActivePreviews returns the MaxActivePreviews field value if set, zero value otherwise.
func (o *StackPreviewConfigCreate) GetMaxActivePreviews() int32 {
	if o == nil || o.MaxActivePreviews == nil {
		var ret int32
		return ret
	}
	return *o.MaxActivePreviews
}

// GetMaxActivePreviewsOk returns a tuple with the MaxActivePreviews field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackPreviewConfigCreate) GetMaxActivePreviewsOk() (*int32, bool) {
	if o == nil || o.MaxActivePreviews == nil {
		return nil, false
	}
	return o.MaxActivePreviews, true
}

// HasMaxActivePreviews returns a boolean if a field has been set.
func (o *StackPreviewConfigCreate) HasMaxActivePreviews() bool {
	if o != nil && o.MaxActivePreviews != nil {
		return true
	}

	return false
}

// SetMaxActivePreviews gets a reference to the given int32 and assigns it to the MaxActivePreviews field.
func (o *StackPreviewConfigCreate) SetMaxActivePreviews(v int32) {
	o.MaxActivePreviews = &v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *StackPreviewConfigCreate) GetEnv() []EnvVar {
	if o == nil || o.Env == nil {
		var ret []EnvVar
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackPreviewConfigCreate) GetEnvOk() ([]EnvVar, bool) {
	if o == nil || o.Env == nil {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *StackPreviewConfigCreate) HasEnv() bool {
	if o != nil && o.Env != nil {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []EnvVar and assigns it to the Env field.
func (o *StackPreviewConfigCreate) SetEnv(v []EnvVar) {
	o.Env = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *StackPreviewConfigCreate) GetLabels() []Label {
	if o == nil || o.Labels == nil {
		var ret []Label
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackPreviewConfigCreate) GetLabelsOk() ([]Label, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *StackPreviewConfigCreate) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []Label and assigns it to the Labels field.
func (o *StackPreviewConfigCreate) SetLabels(v []Label) {
	o.Labels = v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *StackPreviewConfigCreate) GetAnnotations() []Annotation {
	if o == nil || o.Annotations == nil {
		var ret []Annotation
		return ret
	}
	return o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackPreviewConfigCreate) GetAnnotationsOk() ([]Annotation, bool) {
	if o == nil || o.Annotations == nil {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *StackPreviewConfigCreate) HasAnnotations() bool {
	if o != nil && o.Annotations != nil {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given []Annotation and assigns it to the Annotations field.
func (o *StackPreviewConfigCreate) SetAnnotations(v []Annotation) {
	o.Annotations = v
}

func (o StackPreviewConfigCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["git_repository"] = o.GitRepository
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.StackfilePath != nil {
		toSerialize["stackfile_path"] = o.StackfilePath
	}
	if o.MaxActivePreviews != nil {
		toSerialize["max_active_previews"] = o.MaxActivePreviews
	}
	if o.Env != nil {
		toSerialize["env"] = o.Env
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Annotations != nil {
		toSerialize["annotations"] = o.Annotations
	}
	return json.Marshal(toSerialize)
}

type NullableStackPreviewConfigCreate struct {
	value *StackPreviewConfigCreate
	isSet bool
}

func (v NullableStackPreviewConfigCreate) Get() *StackPreviewConfigCreate {
	return v.value
}

func (v *NullableStackPreviewConfigCreate) Set(val *StackPreviewConfigCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableStackPreviewConfigCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableStackPreviewConfigCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackPreviewConfigCreate(val *StackPreviewConfigCreate) *NullableStackPreviewConfigCreate {
	return &NullableStackPreviewConfigCreate{value: val, isSet: true}
}

func (v NullableStackPreviewConfigCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackPreviewConfigCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
