/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostgresConnectionInfoDatabasesInner struct for PostgresConnectionInfoDatabasesInner
type PostgresConnectionInfoDatabasesInner struct {
	Name  *string `json:"name,omitempty"`
	Owner *string `json:"owner,omitempty"`
}

// NewPostgresConnectionInfoDatabasesInner instantiates a new PostgresConnectionInfoDatabasesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostgresConnectionInfoDatabasesInner() *PostgresConnectionInfoDatabasesInner {
	this := PostgresConnectionInfoDatabasesInner{}
	return &this
}

// NewPostgresConnectionInfoDatabasesInnerWithDefaults instantiates a new PostgresConnectionInfoDatabasesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostgresConnectionInfoDatabasesInnerWithDefaults() *PostgresConnectionInfoDatabasesInner {
	this := PostgresConnectionInfoDatabasesInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PostgresConnectionInfoDatabasesInner) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresConnectionInfoDatabasesInner) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PostgresConnectionInfoDatabasesInner) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PostgresConnectionInfoDatabasesInner) SetName(v string) {
	o.Name = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *PostgresConnectionInfoDatabasesInner) GetOwner() string {
	if o == nil || o.Owner == nil {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresConnectionInfoDatabasesInner) GetOwnerOk() (*string, bool) {
	if o == nil || o.Owner == nil {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *PostgresConnectionInfoDatabasesInner) HasOwner() bool {
	if o != nil && o.Owner != nil {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *PostgresConnectionInfoDatabasesInner) SetOwner(v string) {
	o.Owner = &v
}

func (o PostgresConnectionInfoDatabasesInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Owner != nil {
		toSerialize["owner"] = o.Owner
	}
	return json.Marshal(toSerialize)
}

type NullablePostgresConnectionInfoDatabasesInner struct {
	value *PostgresConnectionInfoDatabasesInner
	isSet bool
}

func (v NullablePostgresConnectionInfoDatabasesInner) Get() *PostgresConnectionInfoDatabasesInner {
	return v.value
}

func (v *NullablePostgresConnectionInfoDatabasesInner) Set(val *PostgresConnectionInfoDatabasesInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePostgresConnectionInfoDatabasesInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePostgresConnectionInfoDatabasesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostgresConnectionInfoDatabasesInner(val *PostgresConnectionInfoDatabasesInner) *NullablePostgresConnectionInfoDatabasesInner {
	return &NullablePostgresConnectionInfoDatabasesInner{value: val, isSet: true}
}

func (v NullablePostgresConnectionInfoDatabasesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostgresConnectionInfoDatabasesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
