/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostgresEnvConfig Config for env connections from a PostgreSQL addon (kind=env, from.type=addon/postgres). credential_scope and superuser are mutually exclusive.
type PostgresEnvConfig struct {
	// Target database name within the addon.
	Database *string `json:"database,omitempty"`
	// Which credential set to inject. Mutually exclusive with superuser.
	CredentialScope *string `json:"credential_scope,omitempty"`
	// Use superuser credentials. Mutually exclusive with credential_scope.
	Superuser *bool `json:"superuser,omitempty"`
}

// NewPostgresEnvConfig instantiates a new PostgresEnvConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostgresEnvConfig() *PostgresEnvConfig {
	this := PostgresEnvConfig{}
	return &this
}

// NewPostgresEnvConfigWithDefaults instantiates a new PostgresEnvConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostgresEnvConfigWithDefaults() *PostgresEnvConfig {
	this := PostgresEnvConfig{}
	return &this
}

// GetDatabase returns the Database field value if set, zero value otherwise.
func (o *PostgresEnvConfig) GetDatabase() string {
	if o == nil || o.Database == nil {
		var ret string
		return ret
	}
	return *o.Database
}

// GetDatabaseOk returns a tuple with the Database field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresEnvConfig) GetDatabaseOk() (*string, bool) {
	if o == nil || o.Database == nil {
		return nil, false
	}
	return o.Database, true
}

// HasDatabase returns a boolean if a field has been set.
func (o *PostgresEnvConfig) HasDatabase() bool {
	if o != nil && o.Database != nil {
		return true
	}

	return false
}

// SetDatabase gets a reference to the given string and assigns it to the Database field.
func (o *PostgresEnvConfig) SetDatabase(v string) {
	o.Database = &v
}

// GetCredentialScope returns the CredentialScope field value if set, zero value otherwise.
func (o *PostgresEnvConfig) GetCredentialScope() string {
	if o == nil || o.CredentialScope == nil {
		var ret string
		return ret
	}
	return *o.CredentialScope
}

// GetCredentialScopeOk returns a tuple with the CredentialScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresEnvConfig) GetCredentialScopeOk() (*string, bool) {
	if o == nil || o.CredentialScope == nil {
		return nil, false
	}
	return o.CredentialScope, true
}

// HasCredentialScope returns a boolean if a field has been set.
func (o *PostgresEnvConfig) HasCredentialScope() bool {
	if o != nil && o.CredentialScope != nil {
		return true
	}

	return false
}

// SetCredentialScope gets a reference to the given string and assigns it to the CredentialScope field.
func (o *PostgresEnvConfig) SetCredentialScope(v string) {
	o.CredentialScope = &v
}

// GetSuperuser returns the Superuser field value if set, zero value otherwise.
func (o *PostgresEnvConfig) GetSuperuser() bool {
	if o == nil || o.Superuser == nil {
		var ret bool
		return ret
	}
	return *o.Superuser
}

// GetSuperuserOk returns a tuple with the Superuser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresEnvConfig) GetSuperuserOk() (*bool, bool) {
	if o == nil || o.Superuser == nil {
		return nil, false
	}
	return o.Superuser, true
}

// HasSuperuser returns a boolean if a field has been set.
func (o *PostgresEnvConfig) HasSuperuser() bool {
	if o != nil && o.Superuser != nil {
		return true
	}

	return false
}

// SetSuperuser gets a reference to the given bool and assigns it to the Superuser field.
func (o *PostgresEnvConfig) SetSuperuser(v bool) {
	o.Superuser = &v
}

func (o PostgresEnvConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Database != nil {
		toSerialize["database"] = o.Database
	}
	if o.CredentialScope != nil {
		toSerialize["credential_scope"] = o.CredentialScope
	}
	if o.Superuser != nil {
		toSerialize["superuser"] = o.Superuser
	}
	return json.Marshal(toSerialize)
}

type NullablePostgresEnvConfig struct {
	value *PostgresEnvConfig
	isSet bool
}

func (v NullablePostgresEnvConfig) Get() *PostgresEnvConfig {
	return v.value
}

func (v *NullablePostgresEnvConfig) Set(val *PostgresEnvConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePostgresEnvConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePostgresEnvConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostgresEnvConfig(val *PostgresEnvConfig) *NullablePostgresEnvConfig {
	return &NullablePostgresEnvConfig{value: val, isSet: true}
}

func (v NullablePostgresEnvConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostgresEnvConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
