/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UserSignupRequest struct for UserSignupRequest
type UserSignupRequest struct {
	// User's name
	Name string `json:"name"`
	// User's email address
	Email string `json:"email"`
	// Users desired password
	Password     string        `json:"password"`
	Organisation *Organisation `json:"organisation,omitempty"`
	// Optional invite token for joining an existing organization
	InviteToken *string `json:"invite_token,omitempty"`
	// Turnstile token required for protected public password signup
	TurnstileToken *string `json:"turnstile_token,omitempty"`
}

// NewUserSignupRequest instantiates a new UserSignupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSignupRequest(name string, email string, password string) *UserSignupRequest {
	this := UserSignupRequest{}
	this.Name = name
	this.Email = email
	this.Password = password
	return &this
}

// NewUserSignupRequestWithDefaults instantiates a new UserSignupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSignupRequestWithDefaults() *UserSignupRequest {
	this := UserSignupRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UserSignupRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserSignupRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserSignupRequest) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *UserSignupRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserSignupRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserSignupRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *UserSignupRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UserSignupRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UserSignupRequest) SetPassword(v string) {
	o.Password = v
}

// GetOrganisation returns the Organisation field value if set, zero value otherwise.
func (o *UserSignupRequest) GetOrganisation() Organisation {
	if o == nil || o.Organisation == nil {
		var ret Organisation
		return ret
	}
	return *o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSignupRequest) GetOrganisationOk() (*Organisation, bool) {
	if o == nil || o.Organisation == nil {
		return nil, false
	}
	return o.Organisation, true
}

// HasOrganisation returns a boolean if a field has been set.
func (o *UserSignupRequest) HasOrganisation() bool {
	if o != nil && o.Organisation != nil {
		return true
	}

	return false
}

// SetOrganisation gets a reference to the given Organisation and assigns it to the Organisation field.
func (o *UserSignupRequest) SetOrganisation(v Organisation) {
	o.Organisation = &v
}

// GetInviteToken returns the InviteToken field value if set, zero value otherwise.
func (o *UserSignupRequest) GetInviteToken() string {
	if o == nil || o.InviteToken == nil {
		var ret string
		return ret
	}
	return *o.InviteToken
}

// GetInviteTokenOk returns a tuple with the InviteToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSignupRequest) GetInviteTokenOk() (*string, bool) {
	if o == nil || o.InviteToken == nil {
		return nil, false
	}
	return o.InviteToken, true
}

// HasInviteToken returns a boolean if a field has been set.
func (o *UserSignupRequest) HasInviteToken() bool {
	if o != nil && o.InviteToken != nil {
		return true
	}

	return false
}

// SetInviteToken gets a reference to the given string and assigns it to the InviteToken field.
func (o *UserSignupRequest) SetInviteToken(v string) {
	o.InviteToken = &v
}

// GetTurnstileToken returns the TurnstileToken field value if set, zero value otherwise.
func (o *UserSignupRequest) GetTurnstileToken() string {
	if o == nil || o.TurnstileToken == nil {
		var ret string
		return ret
	}
	return *o.TurnstileToken
}

// GetTurnstileTokenOk returns a tuple with the TurnstileToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSignupRequest) GetTurnstileTokenOk() (*string, bool) {
	if o == nil || o.TurnstileToken == nil {
		return nil, false
	}
	return o.TurnstileToken, true
}

// HasTurnstileToken returns a boolean if a field has been set.
func (o *UserSignupRequest) HasTurnstileToken() bool {
	if o != nil && o.TurnstileToken != nil {
		return true
	}

	return false
}

// SetTurnstileToken gets a reference to the given string and assigns it to the TurnstileToken field.
func (o *UserSignupRequest) SetTurnstileToken(v string) {
	o.TurnstileToken = &v
}

func (o UserSignupRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["password"] = o.Password
	}
	if o.Organisation != nil {
		toSerialize["organisation"] = o.Organisation
	}
	if o.InviteToken != nil {
		toSerialize["invite_token"] = o.InviteToken
	}
	if o.TurnstileToken != nil {
		toSerialize["turnstile_token"] = o.TurnstileToken
	}
	return json.Marshal(toSerialize)
}

type NullableUserSignupRequest struct {
	value *UserSignupRequest
	isSet bool
}

func (v NullableUserSignupRequest) Get() *UserSignupRequest {
	return v.value
}

func (v *NullableUserSignupRequest) Set(val *UserSignupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSignupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSignupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSignupRequest(val *UserSignupRequest) *NullableUserSignupRequest {
	return &NullableUserSignupRequest{value: val, isSet: true}
}

func (v NullableUserSignupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSignupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
