/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GitRepositoryPage struct for GitRepositoryPage
type GitRepositoryPage struct {
	Items      []GitRepository `json:"items,omitempty"`
	Page       *int32          `json:"page,omitempty"`
	TotalCount *int32          `json:"total_count,omitempty"`
	HasNext    *bool           `json:"has_next,omitempty"`
}

// NewGitRepositoryPage instantiates a new GitRepositoryPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitRepositoryPage() *GitRepositoryPage {
	this := GitRepositoryPage{}
	return &this
}

// NewGitRepositoryPageWithDefaults instantiates a new GitRepositoryPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitRepositoryPageWithDefaults() *GitRepositoryPage {
	this := GitRepositoryPage{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GitRepositoryPage) GetItems() []GitRepository {
	if o == nil || o.Items == nil {
		var ret []GitRepository
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitRepositoryPage) GetItemsOk() ([]GitRepository, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GitRepositoryPage) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []GitRepository and assigns it to the Items field.
func (o *GitRepositoryPage) SetItems(v []GitRepository) {
	o.Items = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GitRepositoryPage) GetPage() int32 {
	if o == nil || o.Page == nil {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitRepositoryPage) GetPageOk() (*int32, bool) {
	if o == nil || o.Page == nil {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GitRepositoryPage) HasPage() bool {
	if o != nil && o.Page != nil {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *GitRepositoryPage) SetPage(v int32) {
	o.Page = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *GitRepositoryPage) GetTotalCount() int32 {
	if o == nil || o.TotalCount == nil {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitRepositoryPage) GetTotalCountOk() (*int32, bool) {
	if o == nil || o.TotalCount == nil {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *GitRepositoryPage) HasTotalCount() bool {
	if o != nil && o.TotalCount != nil {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *GitRepositoryPage) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetHasNext returns the HasNext field value if set, zero value otherwise.
func (o *GitRepositoryPage) GetHasNext() bool {
	if o == nil || o.HasNext == nil {
		var ret bool
		return ret
	}
	return *o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitRepositoryPage) GetHasNextOk() (*bool, bool) {
	if o == nil || o.HasNext == nil {
		return nil, false
	}
	return o.HasNext, true
}

// HasHasNext returns a boolean if a field has been set.
func (o *GitRepositoryPage) HasHasNext() bool {
	if o != nil && o.HasNext != nil {
		return true
	}

	return false
}

// SetHasNext gets a reference to the given bool and assigns it to the HasNext field.
func (o *GitRepositoryPage) SetHasNext(v bool) {
	o.HasNext = &v
}

func (o GitRepositoryPage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Page != nil {
		toSerialize["page"] = o.Page
	}
	if o.TotalCount != nil {
		toSerialize["total_count"] = o.TotalCount
	}
	if o.HasNext != nil {
		toSerialize["has_next"] = o.HasNext
	}
	return json.Marshal(toSerialize)
}

type NullableGitRepositoryPage struct {
	value *GitRepositoryPage
	isSet bool
}

func (v NullableGitRepositoryPage) Get() *GitRepositoryPage {
	return v.value
}

func (v *NullableGitRepositoryPage) Set(val *GitRepositoryPage) {
	v.value = val
	v.isSet = true
}

func (v NullableGitRepositoryPage) IsSet() bool {
	return v.isSet
}

func (v *NullableGitRepositoryPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitRepositoryPage(val *GitRepositoryPage) *NullableGitRepositoryPage {
	return &NullableGitRepositoryPage{value: val, isSet: true}
}

func (v NullableGitRepositoryPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitRepositoryPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
