/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StackReleaseSnapshotStack struct for StackReleaseSnapshotStack
type StackReleaseSnapshotStack struct {
	Id             *string            `json:"id,omitempty"`
	OrganisationId *string            `json:"organisation_id,omitempty"`
	ProjectId      *string            `json:"project_id,omitempty"`
	ClusterId      *string            `json:"cluster_id,omitempty"`
	UserId         *string            `json:"user_id,omitempty"`
	Name           *string            `json:"name,omitempty"`
	NamespaceId    *string            `json:"namespace_id,omitempty"`
	Namespace      *string            `json:"namespace,omitempty"`
	Labels         *map[string]string `json:"labels,omitempty"`
	Annotations    *map[string]string `json:"annotations,omitempty"`
}

// NewStackReleaseSnapshotStack instantiates a new StackReleaseSnapshotStack object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackReleaseSnapshotStack() *StackReleaseSnapshotStack {
	this := StackReleaseSnapshotStack{}
	return &this
}

// NewStackReleaseSnapshotStackWithDefaults instantiates a new StackReleaseSnapshotStack object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackReleaseSnapshotStackWithDefaults() *StackReleaseSnapshotStack {
	this := StackReleaseSnapshotStack{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *StackReleaseSnapshotStack) SetId(v string) {
	o.Id = &v
}

// GetOrganisationId returns the OrganisationId field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetOrganisationId() string {
	if o == nil || o.OrganisationId == nil {
		var ret string
		return ret
	}
	return *o.OrganisationId
}

// GetOrganisationIdOk returns a tuple with the OrganisationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetOrganisationIdOk() (*string, bool) {
	if o == nil || o.OrganisationId == nil {
		return nil, false
	}
	return o.OrganisationId, true
}

// HasOrganisationId returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasOrganisationId() bool {
	if o != nil && o.OrganisationId != nil {
		return true
	}

	return false
}

// SetOrganisationId gets a reference to the given string and assigns it to the OrganisationId field.
func (o *StackReleaseSnapshotStack) SetOrganisationId(v string) {
	o.OrganisationId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetProjectId() string {
	if o == nil || o.ProjectId == nil {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetProjectIdOk() (*string, bool) {
	if o == nil || o.ProjectId == nil {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasProjectId() bool {
	if o != nil && o.ProjectId != nil {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *StackReleaseSnapshotStack) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetClusterId() string {
	if o == nil || o.ClusterId == nil {
		var ret string
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetClusterIdOk() (*string, bool) {
	if o == nil || o.ClusterId == nil {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasClusterId() bool {
	if o != nil && o.ClusterId != nil {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given string and assigns it to the ClusterId field.
func (o *StackReleaseSnapshotStack) SetClusterId(v string) {
	o.ClusterId = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *StackReleaseSnapshotStack) SetUserId(v string) {
	o.UserId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StackReleaseSnapshotStack) SetName(v string) {
	o.Name = &v
}

// GetNamespaceId returns the NamespaceId field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetNamespaceId() string {
	if o == nil || o.NamespaceId == nil {
		var ret string
		return ret
	}
	return *o.NamespaceId
}

// GetNamespaceIdOk returns a tuple with the NamespaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetNamespaceIdOk() (*string, bool) {
	if o == nil || o.NamespaceId == nil {
		return nil, false
	}
	return o.NamespaceId, true
}

// HasNamespaceId returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasNamespaceId() bool {
	if o != nil && o.NamespaceId != nil {
		return true
	}

	return false
}

// SetNamespaceId gets a reference to the given string and assigns it to the NamespaceId field.
func (o *StackReleaseSnapshotStack) SetNamespaceId(v string) {
	o.NamespaceId = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *StackReleaseSnapshotStack) SetNamespace(v string) {
	o.Namespace = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetLabels() map[string]string {
	if o == nil || o.Labels == nil {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *StackReleaseSnapshotStack) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *StackReleaseSnapshotStack) GetAnnotations() map[string]string {
	if o == nil || o.Annotations == nil {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackReleaseSnapshotStack) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || o.Annotations == nil {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *StackReleaseSnapshotStack) HasAnnotations() bool {
	if o != nil && o.Annotations != nil {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *StackReleaseSnapshotStack) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

func (o StackReleaseSnapshotStack) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.OrganisationId != nil {
		toSerialize["organisation_id"] = o.OrganisationId
	}
	if o.ProjectId != nil {
		toSerialize["project_id"] = o.ProjectId
	}
	if o.ClusterId != nil {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if o.UserId != nil {
		toSerialize["user_id"] = o.UserId
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.NamespaceId != nil {
		toSerialize["namespace_id"] = o.NamespaceId
	}
	if o.Namespace != nil {
		toSerialize["namespace"] = o.Namespace
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Annotations != nil {
		toSerialize["annotations"] = o.Annotations
	}
	return json.Marshal(toSerialize)
}

type NullableStackReleaseSnapshotStack struct {
	value *StackReleaseSnapshotStack
	isSet bool
}

func (v NullableStackReleaseSnapshotStack) Get() *StackReleaseSnapshotStack {
	return v.value
}

func (v *NullableStackReleaseSnapshotStack) Set(val *StackReleaseSnapshotStack) {
	v.value = val
	v.isSet = true
}

func (v NullableStackReleaseSnapshotStack) IsSet() bool {
	return v.isSet
}

func (v *NullableStackReleaseSnapshotStack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackReleaseSnapshotStack(val *StackReleaseSnapshotStack) *NullableStackReleaseSnapshotStack {
	return &NullableStackReleaseSnapshotStack{value: val, isSet: true}
}

func (v NullableStackReleaseSnapshotStack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackReleaseSnapshotStack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
