/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WorkspaceResourceList struct for WorkspaceResourceList
type WorkspaceResourceList struct {
	Items []WorkspaceResource `json:"items,omitempty"`
	Total *int32              `json:"total,omitempty"`
}

// NewWorkspaceResourceList instantiates a new WorkspaceResourceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceResourceList() *WorkspaceResourceList {
	this := WorkspaceResourceList{}
	return &this
}

// NewWorkspaceResourceListWithDefaults instantiates a new WorkspaceResourceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceResourceListWithDefaults() *WorkspaceResourceList {
	this := WorkspaceResourceList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *WorkspaceResourceList) GetItems() []WorkspaceResource {
	if o == nil || o.Items == nil {
		var ret []WorkspaceResource
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceList) GetItemsOk() ([]WorkspaceResource, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *WorkspaceResourceList) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []WorkspaceResource and assigns it to the Items field.
func (o *WorkspaceResourceList) SetItems(v []WorkspaceResource) {
	o.Items = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *WorkspaceResourceList) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceResourceList) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *WorkspaceResourceList) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *WorkspaceResourceList) SetTotal(v int32) {
	o.Total = &v
}

func (o WorkspaceResourceList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableWorkspaceResourceList struct {
	value *WorkspaceResourceList
	isSet bool
}

func (v NullableWorkspaceResourceList) Get() *WorkspaceResourceList {
	return v.value
}

func (v *NullableWorkspaceResourceList) Set(val *WorkspaceResourceList) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceResourceList) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceResourceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceResourceList(val *WorkspaceResourceList) *NullableWorkspaceResourceList {
	return &NullableWorkspaceResourceList{value: val, isSet: true}
}

func (v NullableWorkspaceResourceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceResourceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
