/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest struct for ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest
type ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest struct {
	// true to fence the cluster, false to unfence
	Fence bool `json:"fence"`
	// Reason for fencing/unfencing
	Reason *string `json:"reason,omitempty"`
}

// NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest instantiates a new ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest(fence bool) *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest {
	this := ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest{}
	this.Fence = fence
	return &this
}

// NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequestWithDefaults instantiates a new ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequestWithDefaults() *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest {
	this := ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest{}
	return &this
}

// GetFence returns the Fence field value
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) GetFence() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Fence
}

// GetFenceOk returns a tuple with the Fence field value
// and a boolean to check if the value has been set.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) GetFenceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fence, true
}

// SetFence sets field value
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) SetFence(v bool) {
	o.Fence = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) SetReason(v string) {
	o.Reason = &v
}

func (o ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["fence"] = o.Fence
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	return json.Marshal(toSerialize)
}

type NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest struct {
	value *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest
	isSet bool
}

func (v NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) Get() *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest {
	return v.value
}

func (v *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) Set(val *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest(val *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest {
	return &NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest{value: val, isSet: true}
}

func (v NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsFencePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
