/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResourceOutcome struct for ResourceOutcome
type ResourceOutcome struct {
	Phase         *string `json:"phase,omitempty"`
	ReadyReplicas *int32  `json:"ready_replicas,omitempty"`
	Replicas      *int32  `json:"replicas,omitempty"`
	Message       *string `json:"message,omitempty"`
}

// NewResourceOutcome instantiates a new ResourceOutcome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceOutcome() *ResourceOutcome {
	this := ResourceOutcome{}
	return &this
}

// NewResourceOutcomeWithDefaults instantiates a new ResourceOutcome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceOutcomeWithDefaults() *ResourceOutcome {
	this := ResourceOutcome{}
	return &this
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *ResourceOutcome) GetPhase() string {
	if o == nil || o.Phase == nil {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceOutcome) GetPhaseOk() (*string, bool) {
	if o == nil || o.Phase == nil {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *ResourceOutcome) HasPhase() bool {
	if o != nil && o.Phase != nil {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *ResourceOutcome) SetPhase(v string) {
	o.Phase = &v
}

// GetReadyReplicas returns the ReadyReplicas field value if set, zero value otherwise.
func (o *ResourceOutcome) GetReadyReplicas() int32 {
	if o == nil || o.ReadyReplicas == nil {
		var ret int32
		return ret
	}
	return *o.ReadyReplicas
}

// GetReadyReplicasOk returns a tuple with the ReadyReplicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceOutcome) GetReadyReplicasOk() (*int32, bool) {
	if o == nil || o.ReadyReplicas == nil {
		return nil, false
	}
	return o.ReadyReplicas, true
}

// HasReadyReplicas returns a boolean if a field has been set.
func (o *ResourceOutcome) HasReadyReplicas() bool {
	if o != nil && o.ReadyReplicas != nil {
		return true
	}

	return false
}

// SetReadyReplicas gets a reference to the given int32 and assigns it to the ReadyReplicas field.
func (o *ResourceOutcome) SetReadyReplicas(v int32) {
	o.ReadyReplicas = &v
}

// GetReplicas returns the Replicas field value if set, zero value otherwise.
func (o *ResourceOutcome) GetReplicas() int32 {
	if o == nil || o.Replicas == nil {
		var ret int32
		return ret
	}
	return *o.Replicas
}

// GetReplicasOk returns a tuple with the Replicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceOutcome) GetReplicasOk() (*int32, bool) {
	if o == nil || o.Replicas == nil {
		return nil, false
	}
	return o.Replicas, true
}

// HasReplicas returns a boolean if a field has been set.
func (o *ResourceOutcome) HasReplicas() bool {
	if o != nil && o.Replicas != nil {
		return true
	}

	return false
}

// SetReplicas gets a reference to the given int32 and assigns it to the Replicas field.
func (o *ResourceOutcome) SetReplicas(v int32) {
	o.Replicas = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResourceOutcome) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceOutcome) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResourceOutcome) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResourceOutcome) SetMessage(v string) {
	o.Message = &v
}

func (o ResourceOutcome) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Phase != nil {
		toSerialize["phase"] = o.Phase
	}
	if o.ReadyReplicas != nil {
		toSerialize["ready_replicas"] = o.ReadyReplicas
	}
	if o.Replicas != nil {
		toSerialize["replicas"] = o.Replicas
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableResourceOutcome struct {
	value *ResourceOutcome
	isSet bool
}

func (v NullableResourceOutcome) Get() *ResourceOutcome {
	return v.value
}

func (v *NullableResourceOutcome) Set(val *ResourceOutcome) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceOutcome(val *ResourceOutcome) *NullableResourceOutcome {
	return &NullableResourceOutcome{value: val, isSet: true}
}

func (v NullableResourceOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
