/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PreviewStackSync struct for PreviewStackSync
type PreviewStackSync struct {
	Commit           *string            `json:"commit,omitempty"`
	StackfileContent *string            `json:"stackfile_content,omitempty"`
	ForceSync        *bool              `json:"force_sync,omitempty"`
	ImageOverrides   *map[string]string `json:"image_overrides,omitempty"`
}

// NewPreviewStackSync instantiates a new PreviewStackSync object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreviewStackSync() *PreviewStackSync {
	this := PreviewStackSync{}
	return &this
}

// NewPreviewStackSyncWithDefaults instantiates a new PreviewStackSync object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreviewStackSyncWithDefaults() *PreviewStackSync {
	this := PreviewStackSync{}
	return &this
}

// GetCommit returns the Commit field value if set, zero value otherwise.
func (o *PreviewStackSync) GetCommit() string {
	if o == nil || o.Commit == nil {
		var ret string
		return ret
	}
	return *o.Commit
}

// GetCommitOk returns a tuple with the Commit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewStackSync) GetCommitOk() (*string, bool) {
	if o == nil || o.Commit == nil {
		return nil, false
	}
	return o.Commit, true
}

// HasCommit returns a boolean if a field has been set.
func (o *PreviewStackSync) HasCommit() bool {
	if o != nil && o.Commit != nil {
		return true
	}

	return false
}

// SetCommit gets a reference to the given string and assigns it to the Commit field.
func (o *PreviewStackSync) SetCommit(v string) {
	o.Commit = &v
}

// GetStackfileContent returns the StackfileContent field value if set, zero value otherwise.
func (o *PreviewStackSync) GetStackfileContent() string {
	if o == nil || o.StackfileContent == nil {
		var ret string
		return ret
	}
	return *o.StackfileContent
}

// GetStackfileContentOk returns a tuple with the StackfileContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewStackSync) GetStackfileContentOk() (*string, bool) {
	if o == nil || o.StackfileContent == nil {
		return nil, false
	}
	return o.StackfileContent, true
}

// HasStackfileContent returns a boolean if a field has been set.
func (o *PreviewStackSync) HasStackfileContent() bool {
	if o != nil && o.StackfileContent != nil {
		return true
	}

	return false
}

// SetStackfileContent gets a reference to the given string and assigns it to the StackfileContent field.
func (o *PreviewStackSync) SetStackfileContent(v string) {
	o.StackfileContent = &v
}

// GetForceSync returns the ForceSync field value if set, zero value otherwise.
func (o *PreviewStackSync) GetForceSync() bool {
	if o == nil || o.ForceSync == nil {
		var ret bool
		return ret
	}
	return *o.ForceSync
}

// GetForceSyncOk returns a tuple with the ForceSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewStackSync) GetForceSyncOk() (*bool, bool) {
	if o == nil || o.ForceSync == nil {
		return nil, false
	}
	return o.ForceSync, true
}

// HasForceSync returns a boolean if a field has been set.
func (o *PreviewStackSync) HasForceSync() bool {
	if o != nil && o.ForceSync != nil {
		return true
	}

	return false
}

// SetForceSync gets a reference to the given bool and assigns it to the ForceSync field.
func (o *PreviewStackSync) SetForceSync(v bool) {
	o.ForceSync = &v
}

// GetImageOverrides returns the ImageOverrides field value if set, zero value otherwise.
func (o *PreviewStackSync) GetImageOverrides() map[string]string {
	if o == nil || o.ImageOverrides == nil {
		var ret map[string]string
		return ret
	}
	return *o.ImageOverrides
}

// GetImageOverridesOk returns a tuple with the ImageOverrides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewStackSync) GetImageOverridesOk() (*map[string]string, bool) {
	if o == nil || o.ImageOverrides == nil {
		return nil, false
	}
	return o.ImageOverrides, true
}

// HasImageOverrides returns a boolean if a field has been set.
func (o *PreviewStackSync) HasImageOverrides() bool {
	if o != nil && o.ImageOverrides != nil {
		return true
	}

	return false
}

// SetImageOverrides gets a reference to the given map[string]string and assigns it to the ImageOverrides field.
func (o *PreviewStackSync) SetImageOverrides(v map[string]string) {
	o.ImageOverrides = &v
}

func (o PreviewStackSync) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Commit != nil {
		toSerialize["commit"] = o.Commit
	}
	if o.StackfileContent != nil {
		toSerialize["stackfile_content"] = o.StackfileContent
	}
	if o.ForceSync != nil {
		toSerialize["force_sync"] = o.ForceSync
	}
	if o.ImageOverrides != nil {
		toSerialize["image_overrides"] = o.ImageOverrides
	}
	return json.Marshal(toSerialize)
}

type NullablePreviewStackSync struct {
	value *PreviewStackSync
	isSet bool
}

func (v NullablePreviewStackSync) Get() *PreviewStackSync {
	return v.value
}

func (v *NullablePreviewStackSync) Set(val *PreviewStackSync) {
	v.value = val
	v.isSet = true
}

func (v NullablePreviewStackSync) IsSet() bool {
	return v.isSet
}

func (v *NullablePreviewStackSync) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreviewStackSync(val *PreviewStackSync) *NullablePreviewStackSync {
	return &NullablePreviewStackSync{value: val, isSet: true}
}

func (v NullablePreviewStackSync) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreviewStackSync) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
