/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddonEnvSource struct for AddonEnvSource
type AddonEnvSource struct {
	Postgres *PostgresAddonEnvSource `json:"postgres,omitempty"`
}

// NewAddonEnvSource instantiates a new AddonEnvSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddonEnvSource() *AddonEnvSource {
	this := AddonEnvSource{}
	return &this
}

// NewAddonEnvSourceWithDefaults instantiates a new AddonEnvSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddonEnvSourceWithDefaults() *AddonEnvSource {
	this := AddonEnvSource{}
	return &this
}

// GetPostgres returns the Postgres field value if set, zero value otherwise.
func (o *AddonEnvSource) GetPostgres() PostgresAddonEnvSource {
	if o == nil || o.Postgres == nil {
		var ret PostgresAddonEnvSource
		return ret
	}
	return *o.Postgres
}

// GetPostgresOk returns a tuple with the Postgres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddonEnvSource) GetPostgresOk() (*PostgresAddonEnvSource, bool) {
	if o == nil || o.Postgres == nil {
		return nil, false
	}
	return o.Postgres, true
}

// HasPostgres returns a boolean if a field has been set.
func (o *AddonEnvSource) HasPostgres() bool {
	if o != nil && o.Postgres != nil {
		return true
	}

	return false
}

// SetPostgres gets a reference to the given PostgresAddonEnvSource and assigns it to the Postgres field.
func (o *AddonEnvSource) SetPostgres(v PostgresAddonEnvSource) {
	o.Postgres = &v
}

func (o AddonEnvSource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Postgres != nil {
		toSerialize["postgres"] = o.Postgres
	}
	return json.Marshal(toSerialize)
}

type NullableAddonEnvSource struct {
	value *AddonEnvSource
	isSet bool
}

func (v NullableAddonEnvSource) Get() *AddonEnvSource {
	return v.value
}

func (v *NullableAddonEnvSource) Set(val *AddonEnvSource) {
	v.value = val
	v.isSet = true
}

func (v NullableAddonEnvSource) IsSet() bool {
	return v.isSet
}

func (v *NullableAddonEnvSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddonEnvSource(val *AddonEnvSource) *NullableAddonEnvSource {
	return &NullableAddonEnvSource{value: val, isSet: true}
}

func (v NullableAddonEnvSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddonEnvSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
