/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StackResourceList struct for StackResourceList
type StackResourceList struct {
	Items []StackResource `json:"items,omitempty"`
	Total *int32          `json:"total,omitempty"`
}

// NewStackResourceList instantiates a new StackResourceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackResourceList() *StackResourceList {
	this := StackResourceList{}
	return &this
}

// NewStackResourceListWithDefaults instantiates a new StackResourceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackResourceListWithDefaults() *StackResourceList {
	this := StackResourceList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *StackResourceList) GetItems() []StackResource {
	if o == nil || o.Items == nil {
		var ret []StackResource
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackResourceList) GetItemsOk() ([]StackResource, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *StackResourceList) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []StackResource and assigns it to the Items field.
func (o *StackResourceList) SetItems(v []StackResource) {
	o.Items = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *StackResourceList) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackResourceList) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *StackResourceList) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *StackResourceList) SetTotal(v int32) {
	o.Total = &v
}

func (o StackResourceList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableStackResourceList struct {
	value *StackResourceList
	isSet bool
}

func (v NullableStackResourceList) Get() *StackResourceList {
	return v.value
}

func (v *NullableStackResourceList) Set(val *StackResourceList) {
	v.value = val
	v.isSet = true
}

func (v NullableStackResourceList) IsSet() bool {
	return v.isSet
}

func (v *NullableStackResourceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackResourceList(val *StackResourceList) *NullableStackResourceList {
	return &NullableStackResourceList{value: val, isSet: true}
}

func (v NullableStackResourceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackResourceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
