/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PreviewGitRepository struct for PreviewGitRepository
type PreviewGitRepository struct {
	RepoUrl      string  `json:"repo_url"`
	BaseBranch   *string `json:"base_branch,omitempty"`
	GitSecretRef *string `json:"git_secret_ref,omitempty"`
}

// NewPreviewGitRepository instantiates a new PreviewGitRepository object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreviewGitRepository(repoUrl string) *PreviewGitRepository {
	this := PreviewGitRepository{}
	this.RepoUrl = repoUrl
	return &this
}

// NewPreviewGitRepositoryWithDefaults instantiates a new PreviewGitRepository object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreviewGitRepositoryWithDefaults() *PreviewGitRepository {
	this := PreviewGitRepository{}
	return &this
}

// GetRepoUrl returns the RepoUrl field value
func (o *PreviewGitRepository) GetRepoUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value
// and a boolean to check if the value has been set.
func (o *PreviewGitRepository) GetRepoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoUrl, true
}

// SetRepoUrl sets field value
func (o *PreviewGitRepository) SetRepoUrl(v string) {
	o.RepoUrl = v
}

// GetBaseBranch returns the BaseBranch field value if set, zero value otherwise.
func (o *PreviewGitRepository) GetBaseBranch() string {
	if o == nil || o.BaseBranch == nil {
		var ret string
		return ret
	}
	return *o.BaseBranch
}

// GetBaseBranchOk returns a tuple with the BaseBranch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewGitRepository) GetBaseBranchOk() (*string, bool) {
	if o == nil || o.BaseBranch == nil {
		return nil, false
	}
	return o.BaseBranch, true
}

// HasBaseBranch returns a boolean if a field has been set.
func (o *PreviewGitRepository) HasBaseBranch() bool {
	if o != nil && o.BaseBranch != nil {
		return true
	}

	return false
}

// SetBaseBranch gets a reference to the given string and assigns it to the BaseBranch field.
func (o *PreviewGitRepository) SetBaseBranch(v string) {
	o.BaseBranch = &v
}

// GetGitSecretRef returns the GitSecretRef field value if set, zero value otherwise.
func (o *PreviewGitRepository) GetGitSecretRef() string {
	if o == nil || o.GitSecretRef == nil {
		var ret string
		return ret
	}
	return *o.GitSecretRef
}

// GetGitSecretRefOk returns a tuple with the GitSecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewGitRepository) GetGitSecretRefOk() (*string, bool) {
	if o == nil || o.GitSecretRef == nil {
		return nil, false
	}
	return o.GitSecretRef, true
}

// HasGitSecretRef returns a boolean if a field has been set.
func (o *PreviewGitRepository) HasGitSecretRef() bool {
	if o != nil && o.GitSecretRef != nil {
		return true
	}

	return false
}

// SetGitSecretRef gets a reference to the given string and assigns it to the GitSecretRef field.
func (o *PreviewGitRepository) SetGitSecretRef(v string) {
	o.GitSecretRef = &v
}

func (o PreviewGitRepository) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if o.BaseBranch != nil {
		toSerialize["base_branch"] = o.BaseBranch
	}
	if o.GitSecretRef != nil {
		toSerialize["git_secret_ref"] = o.GitSecretRef
	}
	return json.Marshal(toSerialize)
}

type NullablePreviewGitRepository struct {
	value *PreviewGitRepository
	isSet bool
}

func (v NullablePreviewGitRepository) Get() *PreviewGitRepository {
	return v.value
}

func (v *NullablePreviewGitRepository) Set(val *PreviewGitRepository) {
	v.value = val
	v.isSet = true
}

func (v NullablePreviewGitRepository) IsSet() bool {
	return v.isSet
}

func (v *NullablePreviewGitRepository) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreviewGitRepository(val *PreviewGitRepository) *NullablePreviewGitRepository {
	return &NullablePreviewGitRepository{value: val, isSet: true}
}

func (v NullablePreviewGitRepository) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreviewGitRepository) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
