/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UserTeamMembership struct for UserTeamMembership
type UserTeamMembership struct {
	TeamId      *string `json:"team_id,omitempty"`
	TeamName    *string `json:"team_name,omitempty"`
	Role        *string `json:"role,omitempty"`
	DefaultTeam *bool   `json:"default_team,omitempty"`
}

// NewUserTeamMembership instantiates a new UserTeamMembership object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserTeamMembership() *UserTeamMembership {
	this := UserTeamMembership{}
	return &this
}

// NewUserTeamMembershipWithDefaults instantiates a new UserTeamMembership object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserTeamMembershipWithDefaults() *UserTeamMembership {
	this := UserTeamMembership{}
	return &this
}

// GetTeamId returns the TeamId field value if set, zero value otherwise.
func (o *UserTeamMembership) GetTeamId() string {
	if o == nil || o.TeamId == nil {
		var ret string
		return ret
	}
	return *o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserTeamMembership) GetTeamIdOk() (*string, bool) {
	if o == nil || o.TeamId == nil {
		return nil, false
	}
	return o.TeamId, true
}

// HasTeamId returns a boolean if a field has been set.
func (o *UserTeamMembership) HasTeamId() bool {
	if o != nil && o.TeamId != nil {
		return true
	}

	return false
}

// SetTeamId gets a reference to the given string and assigns it to the TeamId field.
func (o *UserTeamMembership) SetTeamId(v string) {
	o.TeamId = &v
}

// GetTeamName returns the TeamName field value if set, zero value otherwise.
func (o *UserTeamMembership) GetTeamName() string {
	if o == nil || o.TeamName == nil {
		var ret string
		return ret
	}
	return *o.TeamName
}

// GetTeamNameOk returns a tuple with the TeamName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserTeamMembership) GetTeamNameOk() (*string, bool) {
	if o == nil || o.TeamName == nil {
		return nil, false
	}
	return o.TeamName, true
}

// HasTeamName returns a boolean if a field has been set.
func (o *UserTeamMembership) HasTeamName() bool {
	if o != nil && o.TeamName != nil {
		return true
	}

	return false
}

// SetTeamName gets a reference to the given string and assigns it to the TeamName field.
func (o *UserTeamMembership) SetTeamName(v string) {
	o.TeamName = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *UserTeamMembership) GetRole() string {
	if o == nil || o.Role == nil {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserTeamMembership) GetRoleOk() (*string, bool) {
	if o == nil || o.Role == nil {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *UserTeamMembership) HasRole() bool {
	if o != nil && o.Role != nil {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *UserTeamMembership) SetRole(v string) {
	o.Role = &v
}

// GetDefaultTeam returns the DefaultTeam field value if set, zero value otherwise.
func (o *UserTeamMembership) GetDefaultTeam() bool {
	if o == nil || o.DefaultTeam == nil {
		var ret bool
		return ret
	}
	return *o.DefaultTeam
}

// GetDefaultTeamOk returns a tuple with the DefaultTeam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserTeamMembership) GetDefaultTeamOk() (*bool, bool) {
	if o == nil || o.DefaultTeam == nil {
		return nil, false
	}
	return o.DefaultTeam, true
}

// HasDefaultTeam returns a boolean if a field has been set.
func (o *UserTeamMembership) HasDefaultTeam() bool {
	if o != nil && o.DefaultTeam != nil {
		return true
	}

	return false
}

// SetDefaultTeam gets a reference to the given bool and assigns it to the DefaultTeam field.
func (o *UserTeamMembership) SetDefaultTeam(v bool) {
	o.DefaultTeam = &v
}

func (o UserTeamMembership) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TeamId != nil {
		toSerialize["team_id"] = o.TeamId
	}
	if o.TeamName != nil {
		toSerialize["team_name"] = o.TeamName
	}
	if o.Role != nil {
		toSerialize["role"] = o.Role
	}
	if o.DefaultTeam != nil {
		toSerialize["default_team"] = o.DefaultTeam
	}
	return json.Marshal(toSerialize)
}

type NullableUserTeamMembership struct {
	value *UserTeamMembership
	isSet bool
}

func (v NullableUserTeamMembership) Get() *UserTeamMembership {
	return v.value
}

func (v *NullableUserTeamMembership) Set(val *UserTeamMembership) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTeamMembership) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTeamMembership) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTeamMembership(val *UserTeamMembership) *NullableUserTeamMembership {
	return &NullableUserTeamMembership{value: val, isSet: true}
}

func (v NullableUserTeamMembership) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTeamMembership) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
