/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RegistryCredentialDeleteResponse struct for RegistryCredentialDeleteResponse
type RegistryCredentialDeleteResponse struct {
	// Stacks that were implicitly resolving against the deleted credential
	AffectedStacks []AffectedStackRef `json:"affected_stacks,omitempty"`
}

// NewRegistryCredentialDeleteResponse instantiates a new RegistryCredentialDeleteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryCredentialDeleteResponse() *RegistryCredentialDeleteResponse {
	this := RegistryCredentialDeleteResponse{}
	return &this
}

// NewRegistryCredentialDeleteResponseWithDefaults instantiates a new RegistryCredentialDeleteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryCredentialDeleteResponseWithDefaults() *RegistryCredentialDeleteResponse {
	this := RegistryCredentialDeleteResponse{}
	return &this
}

// GetAffectedStacks returns the AffectedStacks field value if set, zero value otherwise.
func (o *RegistryCredentialDeleteResponse) GetAffectedStacks() []AffectedStackRef {
	if o == nil || o.AffectedStacks == nil {
		var ret []AffectedStackRef
		return ret
	}
	return o.AffectedStacks
}

// GetAffectedStacksOk returns a tuple with the AffectedStacks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryCredentialDeleteResponse) GetAffectedStacksOk() ([]AffectedStackRef, bool) {
	if o == nil || o.AffectedStacks == nil {
		return nil, false
	}
	return o.AffectedStacks, true
}

// HasAffectedStacks returns a boolean if a field has been set.
func (o *RegistryCredentialDeleteResponse) HasAffectedStacks() bool {
	if o != nil && o.AffectedStacks != nil {
		return true
	}

	return false
}

// SetAffectedStacks gets a reference to the given []AffectedStackRef and assigns it to the AffectedStacks field.
func (o *RegistryCredentialDeleteResponse) SetAffectedStacks(v []AffectedStackRef) {
	o.AffectedStacks = v
}

func (o RegistryCredentialDeleteResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AffectedStacks != nil {
		toSerialize["affected_stacks"] = o.AffectedStacks
	}
	return json.Marshal(toSerialize)
}

type NullableRegistryCredentialDeleteResponse struct {
	value *RegistryCredentialDeleteResponse
	isSet bool
}

func (v NullableRegistryCredentialDeleteResponse) Get() *RegistryCredentialDeleteResponse {
	return v.value
}

func (v *NullableRegistryCredentialDeleteResponse) Set(val *RegistryCredentialDeleteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryCredentialDeleteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryCredentialDeleteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryCredentialDeleteResponse(val *RegistryCredentialDeleteResponse) *NullableRegistryCredentialDeleteResponse {
	return &NullableRegistryCredentialDeleteResponse{value: val, isSet: true}
}

func (v NullableRegistryCredentialDeleteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryCredentialDeleteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
