/*
api-server

api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UserCreateRequest struct for UserCreateRequest
type UserCreateRequest struct {
	// User's name
	Name string `json:"name"`
	// User's username
	Username *string `json:"username,omitempty"`
	// User's email address
	Email string `json:"email"`
	// Users desired password
	Password string `json:"password"`
	// User's organisation
	Organisation *string `json:"organisation,omitempty"`
	// OrganisationID
	OrganisationId int32 `json:"organisation_id"`
}

// NewUserCreateRequest instantiates a new UserCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCreateRequest(name string, email string, password string, organisationId int32) *UserCreateRequest {
	this := UserCreateRequest{}
	this.Name = name
	this.Email = email
	this.Password = password
	this.OrganisationId = organisationId
	return &this
}

// NewUserCreateRequestWithDefaults instantiates a new UserCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCreateRequestWithDefaults() *UserCreateRequest {
	this := UserCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UserCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserCreateRequest) SetName(v string) {
	o.Name = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *UserCreateRequest) GetUsername() string {
	if o == nil || o.Username == nil {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetUsernameOk() (*string, bool) {
	if o == nil || o.Username == nil {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *UserCreateRequest) HasUsername() bool {
	if o != nil && o.Username != nil {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *UserCreateRequest) SetUsername(v string) {
	o.Username = &v
}

// GetEmail returns the Email field value
func (o *UserCreateRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserCreateRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *UserCreateRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UserCreateRequest) SetPassword(v string) {
	o.Password = v
}

// GetOrganisation returns the Organisation field value if set, zero value otherwise.
func (o *UserCreateRequest) GetOrganisation() string {
	if o == nil || o.Organisation == nil {
		var ret string
		return ret
	}
	return *o.Organisation
}

// GetOrganisationOk returns a tuple with the Organisation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetOrganisationOk() (*string, bool) {
	if o == nil || o.Organisation == nil {
		return nil, false
	}
	return o.Organisation, true
}

// HasOrganisation returns a boolean if a field has been set.
func (o *UserCreateRequest) HasOrganisation() bool {
	if o != nil && o.Organisation != nil {
		return true
	}

	return false
}

// SetOrganisation gets a reference to the given string and assigns it to the Organisation field.
func (o *UserCreateRequest) SetOrganisation(v string) {
	o.Organisation = &v
}

// GetOrganisationId returns the OrganisationId field value
func (o *UserCreateRequest) GetOrganisationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrganisationId
}

// GetOrganisationIdOk returns a tuple with the OrganisationId field value
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetOrganisationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganisationId, true
}

// SetOrganisationId sets field value
func (o *UserCreateRequest) SetOrganisationId(v int32) {
	o.OrganisationId = v
}

func (o UserCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["password"] = o.Password
	}
	if o.Organisation != nil {
		toSerialize["organisation"] = o.Organisation
	}
	if true {
		toSerialize["organisation_id"] = o.OrganisationId
	}
	return json.Marshal(toSerialize)
}

type NullableUserCreateRequest struct {
	value *UserCreateRequest
	isSet bool
}

func (v NullableUserCreateRequest) Get() *UserCreateRequest {
	return v.value
}

func (v *NullableUserCreateRequest) Set(val *UserCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCreateRequest(val *UserCreateRequest) *NullableUserCreateRequest {
	return &NullableUserCreateRequest{value: val, isSet: true}
}

func (v NullableUserCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
