/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostgresClusterInfo struct for PostgresClusterInfo
type PostgresClusterInfo struct {
	// Current PostgreSQL version
	Version *string `json:"version,omitempty"`
}

// NewPostgresClusterInfo instantiates a new PostgresClusterInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostgresClusterInfo() *PostgresClusterInfo {
	this := PostgresClusterInfo{}
	return &this
}

// NewPostgresClusterInfoWithDefaults instantiates a new PostgresClusterInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostgresClusterInfoWithDefaults() *PostgresClusterInfo {
	this := PostgresClusterInfo{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *PostgresClusterInfo) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresClusterInfo) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *PostgresClusterInfo) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *PostgresClusterInfo) SetVersion(v string) {
	o.Version = &v
}

func (o PostgresClusterInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullablePostgresClusterInfo struct {
	value *PostgresClusterInfo
	isSet bool
}

func (v NullablePostgresClusterInfo) Get() *PostgresClusterInfo {
	return v.value
}

func (v *NullablePostgresClusterInfo) Set(val *PostgresClusterInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePostgresClusterInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePostgresClusterInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostgresClusterInfo(val *PostgresClusterInfo) *NullablePostgresClusterInfo {
	return &NullablePostgresClusterInfo{value: val, isSet: true}
}

func (v NullablePostgresClusterInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostgresClusterInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
