/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// StackReleaseState the model 'StackReleaseState'
type StackReleaseState string

// List of StackReleaseState
const (
	RELEASE_STATE_PENDING     StackReleaseState = "Pending"
	RELEASE_STATE_IN_PROGRESS StackReleaseState = "InProgress"
	RELEASE_STATE_RELEASED    StackReleaseState = "Released"
	RELEASE_STATE_FAILED      StackReleaseState = "Failed"
	RELEASE_STATE_SUPERSEDED  StackReleaseState = "Superseded"
	RELEASE_STATE_CANCELLED   StackReleaseState = "Cancelled"
)

// All allowed values of StackReleaseState enum
var AllowedStackReleaseStateEnumValues = []StackReleaseState{
	"Pending",
	"InProgress",
	"Released",
	"Failed",
	"Superseded",
	"Cancelled",
}

func (v *StackReleaseState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StackReleaseState(value)
	for _, existing := range AllowedStackReleaseStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StackReleaseState", value)
}

// NewStackReleaseStateFromValue returns a pointer to a valid StackReleaseState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStackReleaseStateFromValue(v string) (*StackReleaseState, error) {
	ev := StackReleaseState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for StackReleaseState: valid values are %v", v, AllowedStackReleaseStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v StackReleaseState) IsValid() bool {
	for _, existing := range AllowedStackReleaseStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to StackReleaseState value
func (v StackReleaseState) Ptr() *StackReleaseState {
	return &v
}

type NullableStackReleaseState struct {
	value *StackReleaseState
	isSet bool
}

func (v NullableStackReleaseState) Get() *StackReleaseState {
	return v.value
}

func (v *NullableStackReleaseState) Set(val *StackReleaseState) {
	v.value = val
	v.isSet = true
}

func (v NullableStackReleaseState) IsSet() bool {
	return v.isSet
}

func (v *NullableStackReleaseState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackReleaseState(val *StackReleaseState) *NullableStackReleaseState {
	return &NullableStackReleaseState{value: val, isSet: true}
}

func (v NullableStackReleaseState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackReleaseState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
