/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostgresAddonList struct for PostgresAddonList
type PostgresAddonList struct {
	Items []PostgresAddon `json:"items,omitempty"`
	Total *int32          `json:"total,omitempty"`
}

// NewPostgresAddonList instantiates a new PostgresAddonList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostgresAddonList() *PostgresAddonList {
	this := PostgresAddonList{}
	return &this
}

// NewPostgresAddonListWithDefaults instantiates a new PostgresAddonList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostgresAddonListWithDefaults() *PostgresAddonList {
	this := PostgresAddonList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PostgresAddonList) GetItems() []PostgresAddon {
	if o == nil || o.Items == nil {
		var ret []PostgresAddon
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresAddonList) GetItemsOk() ([]PostgresAddon, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PostgresAddonList) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PostgresAddon and assigns it to the Items field.
func (o *PostgresAddonList) SetItems(v []PostgresAddon) {
	o.Items = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PostgresAddonList) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresAddonList) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PostgresAddonList) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *PostgresAddonList) SetTotal(v int32) {
	o.Total = &v
}

func (o PostgresAddonList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullablePostgresAddonList struct {
	value *PostgresAddonList
	isSet bool
}

func (v NullablePostgresAddonList) Get() *PostgresAddonList {
	return v.value
}

func (v *NullablePostgresAddonList) Set(val *PostgresAddonList) {
	v.value = val
	v.isSet = true
}

func (v NullablePostgresAddonList) IsSet() bool {
	return v.isSet
}

func (v *NullablePostgresAddonList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostgresAddonList(val *PostgresAddonList) *NullablePostgresAddonList {
	return &NullablePostgresAddonList{value: val, isSet: true}
}

func (v NullablePostgresAddonList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostgresAddonList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
