/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ScopeResource struct for ScopeResource
type ScopeResource struct {
	// The resource name (e.g., stacks, secrets, addons/postgres)
	Resource *string `json:"resource,omitempty"`
	// The allowed actions for this resource (e.g., read, write, delete)
	Actions []string `json:"actions,omitempty"`
}

// NewScopeResource instantiates a new ScopeResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScopeResource() *ScopeResource {
	this := ScopeResource{}
	return &this
}

// NewScopeResourceWithDefaults instantiates a new ScopeResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScopeResourceWithDefaults() *ScopeResource {
	this := ScopeResource{}
	return &this
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *ScopeResource) GetResource() string {
	if o == nil || o.Resource == nil {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeResource) GetResourceOk() (*string, bool) {
	if o == nil || o.Resource == nil {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *ScopeResource) HasResource() bool {
	if o != nil && o.Resource != nil {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *ScopeResource) SetResource(v string) {
	o.Resource = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *ScopeResource) GetActions() []string {
	if o == nil || o.Actions == nil {
		var ret []string
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeResource) GetActionsOk() ([]string, bool) {
	if o == nil || o.Actions == nil {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *ScopeResource) HasActions() bool {
	if o != nil && o.Actions != nil {
		return true
	}

	return false
}

// SetActions gets a reference to the given []string and assigns it to the Actions field.
func (o *ScopeResource) SetActions(v []string) {
	o.Actions = v
}

func (o ScopeResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Resource != nil {
		toSerialize["resource"] = o.Resource
	}
	if o.Actions != nil {
		toSerialize["actions"] = o.Actions
	}
	return json.Marshal(toSerialize)
}

type NullableScopeResource struct {
	value *ScopeResource
	isSet bool
}

func (v NullableScopeResource) Get() *ScopeResource {
	return v.value
}

func (v *NullableScopeResource) Set(val *ScopeResource) {
	v.value = val
	v.isSet = true
}

func (v NullableScopeResource) IsSet() bool {
	return v.isSet
}

func (v *NullableScopeResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScopeResource(val *ScopeResource) *NullableScopeResource {
	return &NullableScopeResource{value: val, isSet: true}
}

func (v NullableScopeResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScopeResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
