/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ImageSource struct for ImageSource
type ImageSource struct {
	Ref string `json:"ref"`
	// Org-level registry credential override for pull auth
	RegistryCredentialsId *string `json:"registry_credentials_id,omitempty"`
}

// NewImageSource instantiates a new ImageSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageSource(ref string) *ImageSource {
	this := ImageSource{}
	this.Ref = ref
	return &this
}

// NewImageSourceWithDefaults instantiates a new ImageSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageSourceWithDefaults() *ImageSource {
	this := ImageSource{}
	return &this
}

// GetRef returns the Ref field value
func (o *ImageSource) GetRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ref
}

// GetRefOk returns a tuple with the Ref field value
// and a boolean to check if the value has been set.
func (o *ImageSource) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ref, true
}

// SetRef sets field value
func (o *ImageSource) SetRef(v string) {
	o.Ref = v
}

// GetRegistryCredentialsId returns the RegistryCredentialsId field value if set, zero value otherwise.
func (o *ImageSource) GetRegistryCredentialsId() string {
	if o == nil || o.RegistryCredentialsId == nil {
		var ret string
		return ret
	}
	return *o.RegistryCredentialsId
}

// GetRegistryCredentialsIdOk returns a tuple with the RegistryCredentialsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageSource) GetRegistryCredentialsIdOk() (*string, bool) {
	if o == nil || o.RegistryCredentialsId == nil {
		return nil, false
	}
	return o.RegistryCredentialsId, true
}

// HasRegistryCredentialsId returns a boolean if a field has been set.
func (o *ImageSource) HasRegistryCredentialsId() bool {
	if o != nil && o.RegistryCredentialsId != nil {
		return true
	}

	return false
}

// SetRegistryCredentialsId gets a reference to the given string and assigns it to the RegistryCredentialsId field.
func (o *ImageSource) SetRegistryCredentialsId(v string) {
	o.RegistryCredentialsId = &v
}

func (o ImageSource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ref"] = o.Ref
	}
	if o.RegistryCredentialsId != nil {
		toSerialize["registry_credentials_id"] = o.RegistryCredentialsId
	}
	return json.Marshal(toSerialize)
}

type NullableImageSource struct {
	value *ImageSource
	isSet bool
}

func (v NullableImageSource) Get() *ImageSource {
	return v.value
}

func (v *NullableImageSource) Set(val *ImageSource) {
	v.value = val
	v.isSet = true
}

func (v NullableImageSource) IsSet() bool {
	return v.isSet
}

func (v *NullableImageSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageSource(val *ImageSource) *NullableImageSource {
	return &NullableImageSource{value: val, isSet: true}
}

func (v NullableImageSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
