/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GCSCredentials struct for GCSCredentials
type GCSCredentials struct {
	ServiceAccountCredentials SecretReference `json:"service_account_credentials"`
}

// NewGCSCredentials instantiates a new GCSCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGCSCredentials(serviceAccountCredentials SecretReference) *GCSCredentials {
	this := GCSCredentials{}
	this.ServiceAccountCredentials = serviceAccountCredentials
	return &this
}

// NewGCSCredentialsWithDefaults instantiates a new GCSCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGCSCredentialsWithDefaults() *GCSCredentials {
	this := GCSCredentials{}
	return &this
}

// GetServiceAccountCredentials returns the ServiceAccountCredentials field value
func (o *GCSCredentials) GetServiceAccountCredentials() SecretReference {
	if o == nil {
		var ret SecretReference
		return ret
	}

	return o.ServiceAccountCredentials
}

// GetServiceAccountCredentialsOk returns a tuple with the ServiceAccountCredentials field value
// and a boolean to check if the value has been set.
func (o *GCSCredentials) GetServiceAccountCredentialsOk() (*SecretReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceAccountCredentials, true
}

// SetServiceAccountCredentials sets field value
func (o *GCSCredentials) SetServiceAccountCredentials(v SecretReference) {
	o.ServiceAccountCredentials = v
}

func (o GCSCredentials) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["service_account_credentials"] = o.ServiceAccountCredentials
	}
	return json.Marshal(toSerialize)
}

type NullableGCSCredentials struct {
	value *GCSCredentials
	isSet bool
}

func (v NullableGCSCredentials) Get() *GCSCredentials {
	return v.value
}

func (v *NullableGCSCredentials) Set(val *GCSCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableGCSCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableGCSCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGCSCredentials(val *GCSCredentials) *NullableGCSCredentials {
	return &NullableGCSCredentials{value: val, isSet: true}
}

func (v NullableGCSCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGCSCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
