/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StackSpec struct for StackSpec
type StackSpec struct {
	StackResources []StackResource   `json:"stack_resources,omitempty"`
	Volumes        []Volume          `json:"volumes,omitempty"`
	Connections    []StackConnection `json:"connections,omitempty"`
}

// NewStackSpec instantiates a new StackSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackSpec() *StackSpec {
	this := StackSpec{}
	return &this
}

// NewStackSpecWithDefaults instantiates a new StackSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackSpecWithDefaults() *StackSpec {
	this := StackSpec{}
	return &this
}

// GetStackResources returns the StackResources field value if set, zero value otherwise.
func (o *StackSpec) GetStackResources() []StackResource {
	if o == nil || o.StackResources == nil {
		var ret []StackResource
		return ret
	}
	return o.StackResources
}

// GetStackResourcesOk returns a tuple with the StackResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackSpec) GetStackResourcesOk() ([]StackResource, bool) {
	if o == nil || o.StackResources == nil {
		return nil, false
	}
	return o.StackResources, true
}

// HasStackResources returns a boolean if a field has been set.
func (o *StackSpec) HasStackResources() bool {
	if o != nil && o.StackResources != nil {
		return true
	}

	return false
}

// SetStackResources gets a reference to the given []StackResource and assigns it to the StackResources field.
func (o *StackSpec) SetStackResources(v []StackResource) {
	o.StackResources = v
}

// GetVolumes returns the Volumes field value if set, zero value otherwise.
func (o *StackSpec) GetVolumes() []Volume {
	if o == nil || o.Volumes == nil {
		var ret []Volume
		return ret
	}
	return o.Volumes
}

// GetVolumesOk returns a tuple with the Volumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackSpec) GetVolumesOk() ([]Volume, bool) {
	if o == nil || o.Volumes == nil {
		return nil, false
	}
	return o.Volumes, true
}

// HasVolumes returns a boolean if a field has been set.
func (o *StackSpec) HasVolumes() bool {
	if o != nil && o.Volumes != nil {
		return true
	}

	return false
}

// SetVolumes gets a reference to the given []Volume and assigns it to the Volumes field.
func (o *StackSpec) SetVolumes(v []Volume) {
	o.Volumes = v
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *StackSpec) GetConnections() []StackConnection {
	if o == nil || o.Connections == nil {
		var ret []StackConnection
		return ret
	}
	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackSpec) GetConnectionsOk() ([]StackConnection, bool) {
	if o == nil || o.Connections == nil {
		return nil, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *StackSpec) HasConnections() bool {
	if o != nil && o.Connections != nil {
		return true
	}

	return false
}

// SetConnections gets a reference to the given []StackConnection and assigns it to the Connections field.
func (o *StackSpec) SetConnections(v []StackConnection) {
	o.Connections = v
}

func (o StackSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.StackResources != nil {
		toSerialize["stack_resources"] = o.StackResources
	}
	if o.Volumes != nil {
		toSerialize["volumes"] = o.Volumes
	}
	if o.Connections != nil {
		toSerialize["connections"] = o.Connections
	}
	return json.Marshal(toSerialize)
}

type NullableStackSpec struct {
	value *StackSpec
	isSet bool
}

func (v NullableStackSpec) Get() *StackSpec {
	return v.value
}

func (v *NullableStackSpec) Set(val *StackSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableStackSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableStackSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackSpec(val *StackSpec) *NullableStackSpec {
	return &NullableStackSpec{value: val, isSet: true}
}

func (v NullableStackSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
