/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// APITokenCreateResponse struct for APITokenCreateResponse
type APITokenCreateResponse struct {
	// The raw API token (only returned on creation)
	Token *string `json:"token,omitempty"`
	Id    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	// Prefix of the token for identification
	TokenPrefix *string    `json:"token_prefix,omitempty"`
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
}

// NewAPITokenCreateResponse instantiates a new APITokenCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPITokenCreateResponse() *APITokenCreateResponse {
	this := APITokenCreateResponse{}
	return &this
}

// NewAPITokenCreateResponseWithDefaults instantiates a new APITokenCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPITokenCreateResponseWithDefaults() *APITokenCreateResponse {
	this := APITokenCreateResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *APITokenCreateResponse) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APITokenCreateResponse) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *APITokenCreateResponse) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *APITokenCreateResponse) SetToken(v string) {
	o.Token = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *APITokenCreateResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APITokenCreateResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *APITokenCreateResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *APITokenCreateResponse) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *APITokenCreateResponse) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APITokenCreateResponse) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *APITokenCreateResponse) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *APITokenCreateResponse) SetName(v string) {
	o.Name = &v
}

// GetTokenPrefix returns the TokenPrefix field value if set, zero value otherwise.
func (o *APITokenCreateResponse) GetTokenPrefix() string {
	if o == nil || o.TokenPrefix == nil {
		var ret string
		return ret
	}
	return *o.TokenPrefix
}

// GetTokenPrefixOk returns a tuple with the TokenPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APITokenCreateResponse) GetTokenPrefixOk() (*string, bool) {
	if o == nil || o.TokenPrefix == nil {
		return nil, false
	}
	return o.TokenPrefix, true
}

// HasTokenPrefix returns a boolean if a field has been set.
func (o *APITokenCreateResponse) HasTokenPrefix() bool {
	if o != nil && o.TokenPrefix != nil {
		return true
	}

	return false
}

// SetTokenPrefix gets a reference to the given string and assigns it to the TokenPrefix field.
func (o *APITokenCreateResponse) SetTokenPrefix(v string) {
	o.TokenPrefix = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *APITokenCreateResponse) GetExpiresAt() time.Time {
	if o == nil || o.ExpiresAt == nil {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APITokenCreateResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || o.ExpiresAt == nil {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *APITokenCreateResponse) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt != nil {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *APITokenCreateResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o APITokenCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.TokenPrefix != nil {
		toSerialize["token_prefix"] = o.TokenPrefix
	}
	if o.ExpiresAt != nil {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	return json.Marshal(toSerialize)
}

type NullableAPITokenCreateResponse struct {
	value *APITokenCreateResponse
	isSet bool
}

func (v NullableAPITokenCreateResponse) Get() *APITokenCreateResponse {
	return v.value
}

func (v *NullableAPITokenCreateResponse) Set(val *APITokenCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAPITokenCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAPITokenCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPITokenCreateResponse(val *APITokenCreateResponse) *NullableAPITokenCreateResponse {
	return &NullableAPITokenCreateResponse{value: val, isSet: true}
}

func (v NullableAPITokenCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPITokenCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
