/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response struct for ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response
type ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response struct {
	Items []WorkspaceResource `json:"items,omitempty"`
}

// NewApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response instantiates a new ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response() *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response {
	this := ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response{}
	return &this
}

// NewApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200ResponseWithDefaults instantiates a new ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200ResponseWithDefaults() *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response {
	this := ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) GetItems() []WorkspaceResource {
	if o == nil || o.Items == nil {
		var ret []WorkspaceResource
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) GetItemsOk() ([]WorkspaceResource, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []WorkspaceResource and assigns it to the Items field.
func (o *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) SetItems(v []WorkspaceResource) {
	o.Items = v
}

func (o ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response struct {
	value *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response
	isSet bool
}

func (v NullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) Get() *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response {
	return v.value
}

func (v *NullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) Set(val *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response(val *ApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) *NullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response {
	return &NullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response{value: val, isSet: true}
}

func (v NullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1OrganizationsOrgIdWorkspacesWorkspaceIdResourcesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
