/*
Stackdome API

Deploy, debug, and operate applications through the Stackdome REST API on Stackdome Cloud or a self-hosted installation. This API is in alpha and may change before general availability.

API version: 0.0.1-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GitRepoSource struct for GitRepoSource
type GitRepoSource struct {
	RepoUrl  string          `json:"repo_url"`
	Revision GitRepoRevision `json:"revision"`
}

// NewGitRepoSource instantiates a new GitRepoSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitRepoSource(repoUrl string, revision GitRepoRevision) *GitRepoSource {
	this := GitRepoSource{}
	this.RepoUrl = repoUrl
	this.Revision = revision
	return &this
}

// NewGitRepoSourceWithDefaults instantiates a new GitRepoSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitRepoSourceWithDefaults() *GitRepoSource {
	this := GitRepoSource{}
	return &this
}

// GetRepoUrl returns the RepoUrl field value
func (o *GitRepoSource) GetRepoUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value
// and a boolean to check if the value has been set.
func (o *GitRepoSource) GetRepoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoUrl, true
}

// SetRepoUrl sets field value
func (o *GitRepoSource) SetRepoUrl(v string) {
	o.RepoUrl = v
}

// GetRevision returns the Revision field value
func (o *GitRepoSource) GetRevision() GitRepoRevision {
	if o == nil {
		var ret GitRepoRevision
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *GitRepoSource) GetRevisionOk() (*GitRepoRevision, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *GitRepoSource) SetRevision(v GitRepoRevision) {
	o.Revision = v
}

func (o GitRepoSource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if true {
		toSerialize["revision"] = o.Revision
	}
	return json.Marshal(toSerialize)
}

type NullableGitRepoSource struct {
	value *GitRepoSource
	isSet bool
}

func (v NullableGitRepoSource) Get() *GitRepoSource {
	return v.value
}

func (v *NullableGitRepoSource) Set(val *GitRepoSource) {
	v.value = val
	v.isSet = true
}

func (v NullableGitRepoSource) IsSet() bool {
	return v.isSet
}

func (v *NullableGitRepoSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitRepoSource(val *GitRepoSource) *NullableGitRepoSource {
	return &NullableGitRepoSource{value: val, isSet: true}
}

func (v NullableGitRepoSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitRepoSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
