/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateTeamMemberRoleRequest struct for UpdateTeamMemberRoleRequest
type UpdateTeamMemberRoleRequest struct {
	Role TeamRole `json:"role"`
}

// NewUpdateTeamMemberRoleRequest instantiates a new UpdateTeamMemberRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTeamMemberRoleRequest(role TeamRole) *UpdateTeamMemberRoleRequest {
	this := UpdateTeamMemberRoleRequest{}
	this.Role = role
	return &this
}

// NewUpdateTeamMemberRoleRequestWithDefaults instantiates a new UpdateTeamMemberRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTeamMemberRoleRequestWithDefaults() *UpdateTeamMemberRoleRequest {
	this := UpdateTeamMemberRoleRequest{}
	return &this
}

// GetRole returns the Role field value
func (o *UpdateTeamMemberRoleRequest) GetRole() TeamRole {
	if o == nil {
		var ret TeamRole
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UpdateTeamMemberRoleRequest) GetRoleOk() (*TeamRole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UpdateTeamMemberRoleRequest) SetRole(v TeamRole) {
	o.Role = v
}

func (o UpdateTeamMemberRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["role"] = o.Role
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateTeamMemberRoleRequest struct {
	value *UpdateTeamMemberRoleRequest
	isSet bool
}

func (v NullableUpdateTeamMemberRoleRequest) Get() *UpdateTeamMemberRoleRequest {
	return v.value
}

func (v *NullableUpdateTeamMemberRoleRequest) Set(val *UpdateTeamMemberRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTeamMemberRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTeamMemberRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTeamMemberRoleRequest(val *UpdateTeamMemberRoleRequest) *NullableUpdateTeamMemberRoleRequest {
	return &NullableUpdateTeamMemberRoleRequest{value: val, isSet: true}
}

func (v NullableUpdateTeamMemberRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTeamMemberRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
