/*
stackdome-api-server

stackdome-api-server

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest struct for ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest
type ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest struct {
	// true to hibernate, false to wake
	Hibernate bool `json:"hibernate"`
}

// NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest instantiates a new ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest(hibernate bool) *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest {
	this := ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest{}
	this.Hibernate = hibernate
	return &this
}

// NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequestWithDefaults instantiates a new ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequestWithDefaults() *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest {
	this := ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest{}
	return &this
}

// GetHibernate returns the Hibernate field value
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) GetHibernate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Hibernate
}

// GetHibernateOk returns a tuple with the Hibernate field value
// and a boolean to check if the value has been set.
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) GetHibernateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hibernate, true
}

// SetHibernate sets field value
func (o *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) SetHibernate(v bool) {
	o.Hibernate = v
}

func (o ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["hibernate"] = o.Hibernate
	}
	return json.Marshal(toSerialize)
}

type NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest struct {
	value *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest
	isSet bool
}

func (v NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) Get() *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest {
	return v.value
}

func (v *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) Set(val *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest(val *ApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest {
	return &NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest{value: val, isSet: true}
}

func (v NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1OrganizationsOrgIdAddonsPostgresIdActionsHibernatePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
