package config

const (
	// APPLICATION CONFIG
	JWT_SECRET     string = "JWT_SECRET"
	LOG_LEVEL      string = "LOG_LEVEL"
	ENCRYPTION_KEY string = "ENCRYPTION_KEY"
	// SERVER CONFIG
	SERVER_HOSTNAME     string = "SERVER_HOSTNAME"
	SERVER_BIND_ADDRESS string = "SERVER_BIND_ADDRESS"

	// DATABASE CONFIG
	DB_SSL_MODE        string = "DB_SSL_MODE"
	DB_MAX_CONNECTIONS string = "DB_MAX_CONNECTIONS"
	DB_HOST            string = "DB_HOST"
	DB_PORT            string = "DB_PORT"
	DB_NAME            string = "DB_NAME"
	DB_USERNAME        string = "DB_USERNAME"
	DB_PASSWORD        string = "DB_PASSWORD"
	DB_ROOT_CERT_FILE  string = "DB_ROOT_CERT_FILE"
	DB_DEBUG_MODE      string = "DB_DEBUG_MODE"
	// DEFAULT CLUSTER CONFIG
	DEFAULT_CLUSTER_NAME    string = "DEFAULT_CLUSTER_NAME"
	DEFAULT_CLUSTER_API_URL string = "DEFAULT_CLUSTER_API_URL"
	DEFAULT_CLUSTER_CA_DATA string = "DEFAULT_CLUSTER_CA_DATA"
	DEFAULT_CLUSTER_TOKEN   string = "DEFAULT_CLUSTER_TOKEN"

	// DEFAULT USER CONFIG
	DEFAULT_USER_EMAIL = "DEFAULT_USER_EMAIL"
	DEFAULT_USER_NAME  = "DEFAULT_USER_NAME"
	DEFAULT_USER_PASS  = "DEFAULT_USER_PASSWORD"
)
