// Code generated by MockGen. DO NOT EDIT.
// Source: postgres_addon_store.go
//
// Generated by this command:
//
//	mockgen -source=postgres_addon_store.go -destination=../mocks/mock_postgres_addon_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPostgresAddonStore is a mock of PostgresAddonStore interface.
type MockPostgresAddonStore struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresAddonStoreMockRecorder
	isgomock struct{}
}

// MockPostgresAddonStoreMockRecorder is the mock recorder for MockPostgresAddonStore.
type MockPostgresAddonStoreMockRecorder struct {
	mock *MockPostgresAddonStore
}

// NewMockPostgresAddonStore creates a new mock instance.
func NewMockPostgresAddonStore(ctrl *gomock.Controller) *MockPostgresAddonStore {
	mock := &MockPostgresAddonStore{ctrl: ctrl}
	mock.recorder = &MockPostgresAddonStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresAddonStore) EXPECT() *MockPostgresAddonStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostgresAddonStore) Create(ctx context.Context, addon *models.PostgresAddon) (*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, addon)
	ret0, _ := ret[0].(*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPostgresAddonStoreMockRecorder) Create(ctx, addon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostgresAddonStore)(nil).Create), ctx, addon)
}

// CreateWithTx mocks base method.
func (m *MockPostgresAddonStore) CreateWithTx(ctx context.Context, addon *models.PostgresAddon) (*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, addon)
	ret0, _ := ret[0].(*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockPostgresAddonStoreMockRecorder) CreateWithTx(ctx, addon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockPostgresAddonStore)(nil).CreateWithTx), ctx, addon)
}

// Delete mocks base method.
func (m *MockPostgresAddonStore) Delete(ctx context.Context, ID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostgresAddonStoreMockRecorder) Delete(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostgresAddonStore)(nil).Delete), ctx, ID)
}

// GetByID mocks base method.
func (m *MockPostgresAddonStore) GetByID(ctx context.Context, ID string) (*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, ID)
	ret0, _ := ret[0].(*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPostgresAddonStoreMockRecorder) GetByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPostgresAddonStore)(nil).GetByID), ctx, ID)
}

// GetByName mocks base method.
func (m *MockPostgresAddonStore) GetByName(ctx context.Context, organisationID, name string) (*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, organisationID, name)
	ret0, _ := ret[0].(*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockPostgresAddonStoreMockRecorder) GetByName(ctx, organisationID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockPostgresAddonStore)(nil).GetByName), ctx, organisationID, name)
}

// InternalList mocks base method.
func (m *MockPostgresAddonStore) InternalList(ctx context.Context, query string, args ...any) ([]*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InternalList", varargs...)
	ret0, _ := ret[0].([]*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalList indicates an expected call of InternalList.
func (mr *MockPostgresAddonStoreMockRecorder) InternalList(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalList", reflect.TypeOf((*MockPostgresAddonStore)(nil).InternalList), varargs...)
}

// ListByCluster mocks base method.
func (m *MockPostgresAddonStore) ListByCluster(ctx context.Context, clusterID string) ([]*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCluster", ctx, clusterID)
	ret0, _ := ret[0].([]*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByCluster indicates an expected call of ListByCluster.
func (mr *MockPostgresAddonStoreMockRecorder) ListByCluster(ctx, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCluster", reflect.TypeOf((*MockPostgresAddonStore)(nil).ListByCluster), ctx, clusterID)
}

// ListByOrganisation mocks base method.
func (m *MockPostgresAddonStore) ListByOrganisation(ctx context.Context, organisationID string) ([]*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrganisation", ctx, organisationID)
	ret0, _ := ret[0].([]*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByOrganisation indicates an expected call of ListByOrganisation.
func (mr *MockPostgresAddonStoreMockRecorder) ListByOrganisation(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrganisation", reflect.TypeOf((*MockPostgresAddonStore)(nil).ListByOrganisation), ctx, organisationID)
}

// ListByTeamID mocks base method.
func (m *MockPostgresAddonStore) ListByTeamID(ctx context.Context, teamID string) ([]*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTeamID", ctx, teamID)
	ret0, _ := ret[0].([]*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByTeamID indicates an expected call of ListByTeamID.
func (mr *MockPostgresAddonStoreMockRecorder) ListByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTeamID", reflect.TypeOf((*MockPostgresAddonStore)(nil).ListByTeamID), ctx, teamID)
}

// ListByTeamIDs mocks base method.
func (m *MockPostgresAddonStore) ListByTeamIDs(ctx context.Context, teamIDs []string) ([]*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTeamIDs", ctx, teamIDs)
	ret0, _ := ret[0].([]*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByTeamIDs indicates an expected call of ListByTeamIDs.
func (mr *MockPostgresAddonStoreMockRecorder) ListByTeamIDs(ctx, teamIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTeamIDs", reflect.TypeOf((*MockPostgresAddonStore)(nil).ListByTeamIDs), ctx, teamIDs)
}

// Update mocks base method.
func (m *MockPostgresAddonStore) Update(ctx context.Context, addon *models.PostgresAddon) (*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, addon)
	ret0, _ := ret[0].(*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPostgresAddonStoreMockRecorder) Update(ctx, addon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPostgresAddonStore)(nil).Update), ctx, addon)
}

// UpdateBackupRequestedAt mocks base method.
func (m *MockPostgresAddonStore) UpdateBackupRequestedAt(ctx context.Context, id string, timestamp *time.Time) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBackupRequestedAt", ctx, id, timestamp)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// UpdateBackupRequestedAt indicates an expected call of UpdateBackupRequestedAt.
func (mr *MockPostgresAddonStoreMockRecorder) UpdateBackupRequestedAt(ctx, id, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBackupRequestedAt", reflect.TypeOf((*MockPostgresAddonStore)(nil).UpdateBackupRequestedAt), ctx, id, timestamp)
}

// UpdateStatus mocks base method.
func (m *MockPostgresAddonStore) UpdateStatus(ctx context.Context, id string, status *models.PostgresAddonStatus) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPostgresAddonStoreMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPostgresAddonStore)(nil).UpdateStatus), ctx, id, status)
}

// UpdateWithTx mocks base method.
func (m *MockPostgresAddonStore) UpdateWithTx(ctx context.Context, addon *models.PostgresAddon) (*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithTx", ctx, addon)
	ret0, _ := ret[0].(*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateWithTx indicates an expected call of UpdateWithTx.
func (mr *MockPostgresAddonStoreMockRecorder) UpdateWithTx(ctx, addon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTx", reflect.TypeOf((*MockPostgresAddonStore)(nil).UpdateWithTx), ctx, addon)
}

// ValidateAddonExists mocks base method.
func (m *MockPostgresAddonStore) ValidateAddonExists(ctx context.Context, addonID string) (bool, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAddonExists", ctx, addonID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ValidateAddonExists indicates an expected call of ValidateAddonExists.
func (mr *MockPostgresAddonStoreMockRecorder) ValidateAddonExists(ctx, addonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAddonExists", reflect.TypeOf((*MockPostgresAddonStore)(nil).ValidateAddonExists), ctx, addonID)
}

// ValidateAddonNameUnique mocks base method.
func (m *MockPostgresAddonStore) ValidateAddonNameUnique(ctx context.Context, organisationID, name, excludeID string) (bool, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAddonNameUnique", ctx, organisationID, name, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ValidateAddonNameUnique indicates an expected call of ValidateAddonNameUnique.
func (mr *MockPostgresAddonStoreMockRecorder) ValidateAddonNameUnique(ctx, organisationID, name, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAddonNameUnique", reflect.TypeOf((*MockPostgresAddonStore)(nil).ValidateAddonNameUnique), ctx, organisationID, name, excludeID)
}

// WithTransaction mocks base method.
func (m *MockPostgresAddonStore) WithTransaction(ctx context.Context, fn func(context.Context) *errors.ServiceError) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockPostgresAddonStoreMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockPostgresAddonStore)(nil).WithTransaction), ctx, fn)
}
