// Code generated by MockGen. DO NOT EDIT.
// Source: project_store.go
//
// Generated by this command:
//
//	mockgen -source=project_store.go -destination=../mocks/mock_project_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectStore is a mock of ProjectStore interface.
type MockProjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockProjectStoreMockRecorder
	isgomock struct{}
}

// MockProjectStoreMockRecorder is the mock recorder for MockProjectStore.
type MockProjectStoreMockRecorder struct {
	mock *MockProjectStore
}

// NewMockProjectStore creates a new mock instance.
func NewMockProjectStore(ctrl *gomock.Controller) *MockProjectStore {
	mock := &MockProjectStore{ctrl: ctrl}
	mock.recorder = &MockProjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectStore) EXPECT() *MockProjectStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectStore) Create(ctx context.Context, project *models.Project) (*models.Project, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, project)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectStoreMockRecorder) Create(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectStore)(nil).Create), ctx, project)
}

// Delete mocks base method.
func (m *MockProjectStore) Delete(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectStore)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockProjectStore) GetByID(ctx context.Context, id string) (*models.Project, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectStore)(nil).GetByID), ctx, id)
}

// GetByOrgAndName mocks base method.
func (m *MockProjectStore) GetByOrgAndName(ctx context.Context, orgID, name string) (*models.Project, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgAndName", ctx, orgID, name)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByOrgAndName indicates an expected call of GetByOrgAndName.
func (mr *MockProjectStoreMockRecorder) GetByOrgAndName(ctx, orgID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgAndName", reflect.TypeOf((*MockProjectStore)(nil).GetByOrgAndName), ctx, orgID, name)
}

// GetDefaultProjectForOrg mocks base method.
func (m *MockProjectStore) GetDefaultProjectForOrg(ctx context.Context, orgID string) (*models.Project, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultProjectForOrg", ctx, orgID)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetDefaultProjectForOrg indicates an expected call of GetDefaultProjectForOrg.
func (mr *MockProjectStoreMockRecorder) GetDefaultProjectForOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultProjectForOrg", reflect.TypeOf((*MockProjectStore)(nil).GetDefaultProjectForOrg), ctx, orgID)
}

// ListByOrgID mocks base method.
func (m *MockProjectStore) ListByOrgID(ctx context.Context, orgID string) ([]*models.Project, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrgID", ctx, orgID)
	ret0, _ := ret[0].([]*models.Project)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByOrgID indicates an expected call of ListByOrgID.
func (mr *MockProjectStoreMockRecorder) ListByOrgID(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrgID", reflect.TypeOf((*MockProjectStore)(nil).ListByOrgID), ctx, orgID)
}

// Update mocks base method.
func (m *MockProjectStore) Update(ctx context.Context, id string, project *models.Project) (*models.Project, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, project)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProjectStoreMockRecorder) Update(ctx, id, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectStore)(nil).Update), ctx, id, project)
}
