// Code generated by MockGen. DO NOT EDIT.
// Source: volume_store.go
//
// Generated by this command:
//
//	mockgen -source=volume_store.go -destination=../mocks/mock_volume_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockVolumeStore is a mock of VolumeStore interface.
type MockVolumeStore struct {
	ctrl     *gomock.Controller
	recorder *MockVolumeStoreMockRecorder
	isgomock struct{}
}

// MockVolumeStoreMockRecorder is the mock recorder for MockVolumeStore.
type MockVolumeStoreMockRecorder struct {
	mock *MockVolumeStore
}

// NewMockVolumeStore creates a new mock instance.
func NewMockVolumeStore(ctrl *gomock.Controller) *MockVolumeStore {
	mock := &MockVolumeStore{ctrl: ctrl}
	mock.recorder = &MockVolumeStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumeStore) EXPECT() *MockVolumeStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVolumeStore) Create(ctx context.Context, spec *models.Volume) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, spec)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVolumeStoreMockRecorder) Create(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVolumeStore)(nil).Create), ctx, spec)
}

// CreateWithTx mocks base method.
func (m *MockVolumeStore) CreateWithTx(ctx context.Context, spec *models.Volume) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, spec)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockVolumeStoreMockRecorder) CreateWithTx(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockVolumeStore)(nil).CreateWithTx), ctx, spec)
}

// Delete mocks base method.
func (m *MockVolumeStore) Delete(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVolumeStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVolumeStore)(nil).Delete), ctx, id)
}

// DeleteWithTx mocks base method.
func (m *MockVolumeStore) DeleteWithTx(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTx", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// DeleteWithTx indicates an expected call of DeleteWithTx.
func (mr *MockVolumeStoreMockRecorder) DeleteWithTx(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTx", reflect.TypeOf((*MockVolumeStore)(nil).DeleteWithTx), ctx, id)
}

// GetByID mocks base method.
func (m *MockVolumeStore) GetByID(ctx context.Context, id string) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVolumeStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVolumeStore)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockVolumeStore) GetByUserID(ctx context.Context, id string) ([]*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, id)
	ret0, _ := ret[0].([]*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockVolumeStoreMockRecorder) GetByUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockVolumeStore)(nil).GetByUserID), ctx, id)
}

// GetByVolumeNameAndNamespace mocks base method.
func (m *MockVolumeStore) GetByVolumeNameAndNamespace(ctx context.Context, volumeName, namespace string) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVolumeNameAndNamespace", ctx, volumeName, namespace)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByVolumeNameAndNamespace indicates an expected call of GetByVolumeNameAndNamespace.
func (mr *MockVolumeStoreMockRecorder) GetByVolumeNameAndNamespace(ctx, volumeName, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVolumeNameAndNamespace", reflect.TypeOf((*MockVolumeStore)(nil).GetByVolumeNameAndNamespace), ctx, volumeName, namespace)
}

// InternalList mocks base method.
func (m *MockVolumeStore) InternalList(ctx context.Context, ids []string) ([]*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalList", ctx, ids)
	ret0, _ := ret[0].([]*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalList indicates an expected call of InternalList.
func (mr *MockVolumeStoreMockRecorder) InternalList(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalList", reflect.TypeOf((*MockVolumeStore)(nil).InternalList), ctx, ids)
}

// InternalListNotReady mocks base method.
func (m *MockVolumeStore) InternalListNotReady(ctx context.Context) ([]*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalListNotReady", ctx)
	ret0, _ := ret[0].([]*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalListNotReady indicates an expected call of InternalListNotReady.
func (mr *MockVolumeStoreMockRecorder) InternalListNotReady(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalListNotReady", reflect.TypeOf((*MockVolumeStore)(nil).InternalListNotReady), ctx)
}

// ListByTeamID mocks base method.
func (m *MockVolumeStore) ListByTeamID(ctx context.Context, teamID string) ([]*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTeamID", ctx, teamID)
	ret0, _ := ret[0].([]*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByTeamID indicates an expected call of ListByTeamID.
func (mr *MockVolumeStoreMockRecorder) ListByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTeamID", reflect.TypeOf((*MockVolumeStore)(nil).ListByTeamID), ctx, teamID)
}

// UpdateGitRepoSourceRevision mocks base method.
func (m *MockVolumeStore) UpdateGitRepoSourceRevision(ctx context.Context, id string, revision models.GitRepoRevision) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGitRepoSourceRevision", ctx, id, revision)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateGitRepoSourceRevision indicates an expected call of UpdateGitRepoSourceRevision.
func (mr *MockVolumeStoreMockRecorder) UpdateGitRepoSourceRevision(ctx, id, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGitRepoSourceRevision", reflect.TypeOf((*MockVolumeStore)(nil).UpdateGitRepoSourceRevision), ctx, id, revision)
}

// UpdateGitRepoSourceRevisionWithTx mocks base method.
func (m *MockVolumeStore) UpdateGitRepoSourceRevisionWithTx(ctx context.Context, id string, revision models.GitRepoRevision) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGitRepoSourceRevisionWithTx", ctx, id, revision)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateGitRepoSourceRevisionWithTx indicates an expected call of UpdateGitRepoSourceRevisionWithTx.
func (mr *MockVolumeStoreMockRecorder) UpdateGitRepoSourceRevisionWithTx(ctx, id, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGitRepoSourceRevisionWithTx", reflect.TypeOf((*MockVolumeStore)(nil).UpdateGitRepoSourceRevisionWithTx), ctx, id, revision)
}

// UpdateRemoteDirSourceHash mocks base method.
func (m *MockVolumeStore) UpdateRemoteDirSourceHash(ctx context.Context, id, remoteDirHash string) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRemoteDirSourceHash", ctx, id, remoteDirHash)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateRemoteDirSourceHash indicates an expected call of UpdateRemoteDirSourceHash.
func (mr *MockVolumeStoreMockRecorder) UpdateRemoteDirSourceHash(ctx, id, remoteDirHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRemoteDirSourceHash", reflect.TypeOf((*MockVolumeStore)(nil).UpdateRemoteDirSourceHash), ctx, id, remoteDirHash)
}

// UpdateRemoteDirSourceHashWithTx mocks base method.
func (m *MockVolumeStore) UpdateRemoteDirSourceHashWithTx(ctx context.Context, id, remoteDirHash string) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRemoteDirSourceHashWithTx", ctx, id, remoteDirHash)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateRemoteDirSourceHashWithTx indicates an expected call of UpdateRemoteDirSourceHashWithTx.
func (mr *MockVolumeStoreMockRecorder) UpdateRemoteDirSourceHashWithTx(ctx, id, remoteDirHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRemoteDirSourceHashWithTx", reflect.TypeOf((*MockVolumeStore)(nil).UpdateRemoteDirSourceHashWithTx), ctx, id, remoteDirHash)
}

// UpdateStatus mocks base method.
func (m *MockVolumeStore) UpdateStatus(ctx context.Context, id string, status *models.VolumeStatus) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockVolumeStoreMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockVolumeStore)(nil).UpdateStatus), ctx, id, status)
}

// WithTransaction mocks base method.
func (m *MockVolumeStore) WithTransaction(ctx context.Context, fn func(context.Context) *errors.ServiceError) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockVolumeStoreMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockVolumeStore)(nil).WithTransaction), ctx, fn)
}
