// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Stackdome/stackdome/pkg/services (interfaces: ReferenceService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_reference_service.go -package=mocks github.com/Stackdome/stackdome/pkg/services ReferenceService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockReferenceService is a mock of ReferenceService interface.
type MockReferenceService struct {
	ctrl     *gomock.Controller
	recorder *MockReferenceServiceMockRecorder
	isgomock struct{}
}

// MockReferenceServiceMockRecorder is the mock recorder for MockReferenceService.
type MockReferenceServiceMockRecorder struct {
	mock *MockReferenceService
}

// NewMockReferenceService creates a new mock instance.
func NewMockReferenceService(ctrl *gomock.Controller) *MockReferenceService {
	mock := &MockReferenceService{ctrl: ctrl}
	mock.recorder = &MockReferenceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReferenceService) EXPECT() *MockReferenceServiceMockRecorder {
	return m.recorder
}

// InternalListReleaseReferents mocks base method.
func (m *MockReferenceService) InternalListReleaseReferents(ctx context.Context, releaseIDs []string, referentType models.ReferentType) ([]models.ResourceReference, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalListReleaseReferents", ctx, releaseIDs, referentType)
	ret0, _ := ret[0].([]models.ResourceReference)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalListReleaseReferents indicates an expected call of InternalListReleaseReferents.
func (mr *MockReferenceServiceMockRecorder) InternalListReleaseReferents(ctx, releaseIDs, referentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalListReleaseReferents", reflect.TypeOf((*MockReferenceService)(nil).InternalListReleaseReferents), ctx, releaseIDs, referentType)
}

// IsReferentInUse mocks base method.
func (m *MockReferenceService) IsReferentInUse(ctx context.Context, referentType models.ReferentType, referentID string) (bool, []models.ResourceReference, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReferentInUse", ctx, referentType, referentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]models.ResourceReference)
	ret2, _ := ret[2].(*errors.ServiceError)
	return ret0, ret1, ret2
}

// IsReferentInUse indicates an expected call of IsReferentInUse.
func (mr *MockReferenceServiceMockRecorder) IsReferentInUse(ctx, referentType, referentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReferentInUse", reflect.TypeOf((*MockReferenceService)(nil).IsReferentInUse), ctx, referentType, referentID)
}

// ProjectRelease mocks base method.
func (m *MockReferenceService) ProjectRelease(ctx context.Context, release *models.StackRelease) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectRelease", ctx, release)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// ProjectRelease indicates an expected call of ProjectRelease.
func (mr *MockReferenceServiceMockRecorder) ProjectRelease(ctx, release any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectRelease", reflect.TypeOf((*MockReferenceService)(nil).ProjectRelease), ctx, release)
}

// ReprojectSpec mocks base method.
func (m *MockReferenceService) ReprojectSpec(ctx context.Context, stackID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprojectSpec", ctx, stackID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// ReprojectSpec indicates an expected call of ReprojectSpec.
func (mr *MockReferenceServiceMockRecorder) ReprojectSpec(ctx, stackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprojectSpec", reflect.TypeOf((*MockReferenceService)(nil).ReprojectSpec), ctx, stackID)
}
