// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Stackdome/stackdome/pkg/services (interfaces: GitHubWebhookService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_github_webhook_service.go -package=mocks github.com/Stackdome/stackdome/pkg/services GitHubWebhookService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHubWebhookService is a mock of GitHubWebhookService interface.
type MockGitHubWebhookService struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubWebhookServiceMockRecorder
	isgomock struct{}
}

// MockGitHubWebhookServiceMockRecorder is the mock recorder for MockGitHubWebhookService.
type MockGitHubWebhookServiceMockRecorder struct {
	mock *MockGitHubWebhookService
}

// NewMockGitHubWebhookService creates a new mock instance.
func NewMockGitHubWebhookService(ctrl *gomock.Controller) *MockGitHubWebhookService {
	mock := &MockGitHubWebhookService{ctrl: ctrl}
	mock.recorder = &MockGitHubWebhookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubWebhookService) EXPECT() *MockGitHubWebhookServiceMockRecorder {
	return m.recorder
}

// ProcessGitHubWebhook mocks base method.
func (m *MockGitHubWebhookService) ProcessGitHubWebhook(ctx context.Context, event string, payload []byte, signature string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessGitHubWebhook", ctx, event, payload, signature)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// ProcessGitHubWebhook indicates an expected call of ProcessGitHubWebhook.
func (mr *MockGitHubWebhookServiceMockRecorder) ProcessGitHubWebhook(ctx, event, payload, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessGitHubWebhook", reflect.TypeOf((*MockGitHubWebhookService)(nil).ProcessGitHubWebhook), ctx, event, payload, signature)
}
