// Code generated by MockGen. DO NOT EDIT.
// Source: organisation_store.go
//
// Generated by this command:
//
//	mockgen -source=organisation_store.go -destination=../mocks/mock_organisation_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganisationStore is a mock of OrganisationStore interface.
type MockOrganisationStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrganisationStoreMockRecorder
	isgomock struct{}
}

// MockOrganisationStoreMockRecorder is the mock recorder for MockOrganisationStore.
type MockOrganisationStoreMockRecorder struct {
	mock *MockOrganisationStore
}

// NewMockOrganisationStore creates a new mock instance.
func NewMockOrganisationStore(ctrl *gomock.Controller) *MockOrganisationStore {
	mock := &MockOrganisationStore{ctrl: ctrl}
	mock.recorder = &MockOrganisationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganisationStore) EXPECT() *MockOrganisationStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganisationStore) Create(ctx context.Context, spec *models.Organisation) (*models.Organisation, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, spec)
	ret0, _ := ret[0].(*models.Organisation)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrganisationStoreMockRecorder) Create(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganisationStore)(nil).Create), ctx, spec)
}

// Delete mocks base method.
func (m *MockOrganisationStore) Delete(ctx context.Context, ID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganisationStoreMockRecorder) Delete(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganisationStore)(nil).Delete), ctx, ID)
}

// Get mocks base method.
func (m *MockOrganisationStore) Get(ctx context.Context, ID string) (*models.Organisation, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, ID)
	ret0, _ := ret[0].(*models.Organisation)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrganisationStoreMockRecorder) Get(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrganisationStore)(nil).Get), ctx, ID)
}

// GetPlatformOrg mocks base method.
func (m *MockOrganisationStore) GetPlatformOrg(ctx context.Context) (*models.Organisation, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatformOrg", ctx)
	ret0, _ := ret[0].(*models.Organisation)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetPlatformOrg indicates an expected call of GetPlatformOrg.
func (mr *MockOrganisationStoreMockRecorder) GetPlatformOrg(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatformOrg", reflect.TypeOf((*MockOrganisationStore)(nil).GetPlatformOrg), ctx)
}

// LockByID mocks base method.
func (m *MockOrganisationStore) LockByID(ctx context.Context, ID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockByID", ctx, ID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// LockByID indicates an expected call of LockByID.
func (mr *MockOrganisationStoreMockRecorder) LockByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockByID", reflect.TypeOf((*MockOrganisationStore)(nil).LockByID), ctx, ID)
}

// OrganisationNameExists mocks base method.
func (m *MockOrganisationStore) OrganisationNameExists(ctx context.Context, name string) (bool, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganisationNameExists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// OrganisationNameExists indicates an expected call of OrganisationNameExists.
func (mr *MockOrganisationStoreMockRecorder) OrganisationNameExists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganisationNameExists", reflect.TypeOf((*MockOrganisationStore)(nil).OrganisationNameExists), ctx, name)
}

// Update mocks base method.
func (m *MockOrganisationStore) Update(ctx context.Context, id string, org *models.Organisation) (*models.Organisation, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, org)
	ret0, _ := ret[0].(*models.Organisation)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrganisationStoreMockRecorder) Update(ctx, id, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganisationStore)(nil).Update), ctx, id, org)
}
