// Code generated by MockGen. DO NOT EDIT.
// Source: project_membership_store.go
//
// Generated by this command:
//
//	mockgen -source=project_membership_store.go -destination=../mocks/mock_project_membership_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectMembershipStore is a mock of ProjectMembershipStore interface.
type MockProjectMembershipStore struct {
	ctrl     *gomock.Controller
	recorder *MockProjectMembershipStoreMockRecorder
	isgomock struct{}
}

// MockProjectMembershipStoreMockRecorder is the mock recorder for MockProjectMembershipStore.
type MockProjectMembershipStoreMockRecorder struct {
	mock *MockProjectMembershipStore
}

// NewMockProjectMembershipStore creates a new mock instance.
func NewMockProjectMembershipStore(ctrl *gomock.Controller) *MockProjectMembershipStore {
	mock := &MockProjectMembershipStore{ctrl: ctrl}
	mock.recorder = &MockProjectMembershipStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectMembershipStore) EXPECT() *MockProjectMembershipStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectMembershipStore) Create(ctx context.Context, membership *models.ProjectMembership) (*models.ProjectMembership, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, membership)
	ret0, _ := ret[0].(*models.ProjectMembership)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectMembershipStoreMockRecorder) Create(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectMembershipStore)(nil).Create), ctx, membership)
}

// Delete mocks base method.
func (m *MockProjectMembershipStore) Delete(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectMembershipStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectMembershipStore)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockProjectMembershipStore) GetByID(ctx context.Context, id string) (*models.ProjectMembership, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.ProjectMembership)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectMembershipStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectMembershipStore)(nil).GetByID), ctx, id)
}

// GetByProjectAndUser mocks base method.
func (m *MockProjectMembershipStore) GetByProjectAndUser(ctx context.Context, projectID, userID string) (*models.ProjectMembership, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectAndUser", ctx, projectID, userID)
	ret0, _ := ret[0].(*models.ProjectMembership)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByProjectAndUser indicates an expected call of GetByProjectAndUser.
func (mr *MockProjectMembershipStoreMockRecorder) GetByProjectAndUser(ctx, projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectAndUser", reflect.TypeOf((*MockProjectMembershipStore)(nil).GetByProjectAndUser), ctx, projectID, userID)
}

// ListByProjectID mocks base method.
func (m *MockProjectMembershipStore) ListByProjectID(ctx context.Context, projectID string) ([]*models.ProjectMembership, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]*models.ProjectMembership)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByProjectID indicates an expected call of ListByProjectID.
func (mr *MockProjectMembershipStoreMockRecorder) ListByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProjectID", reflect.TypeOf((*MockProjectMembershipStore)(nil).ListByProjectID), ctx, projectID)
}

// ListByUserID mocks base method.
func (m *MockProjectMembershipStore) ListByUserID(ctx context.Context, userID string) ([]*models.ProjectMembership, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*models.ProjectMembership)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockProjectMembershipStoreMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockProjectMembershipStore)(nil).ListByUserID), ctx, userID)
}

// ListByUserIDAndOrgID mocks base method.
func (m *MockProjectMembershipStore) ListByUserIDAndOrgID(ctx context.Context, userID, orgID string) ([]*models.ProjectMembership, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserIDAndOrgID", ctx, userID, orgID)
	ret0, _ := ret[0].([]*models.ProjectMembership)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByUserIDAndOrgID indicates an expected call of ListByUserIDAndOrgID.
func (mr *MockProjectMembershipStoreMockRecorder) ListByUserIDAndOrgID(ctx, userID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserIDAndOrgID", reflect.TypeOf((*MockProjectMembershipStore)(nil).ListByUserIDAndOrgID), ctx, userID, orgID)
}

// Update mocks base method.
func (m *MockProjectMembershipStore) Update(ctx context.Context, id string, membership *models.ProjectMembership) (*models.ProjectMembership, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, membership)
	ret0, _ := ret[0].(*models.ProjectMembership)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProjectMembershipStoreMockRecorder) Update(ctx, id, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectMembershipStore)(nil).Update), ctx, id, membership)
}
