// Code generated by MockGen. DO NOT EDIT.
// Source: git_integration.go
//
// Generated by this command:
//
//	mockgen -source=git_integration.go -destination=../mocks/mock_git_integration_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockGitIntegrationStore is a mock of GitIntegrationStore interface.
type MockGitIntegrationStore struct {
	ctrl     *gomock.Controller
	recorder *MockGitIntegrationStoreMockRecorder
	isgomock struct{}
}

// MockGitIntegrationStoreMockRecorder is the mock recorder for MockGitIntegrationStore.
type MockGitIntegrationStoreMockRecorder struct {
	mock *MockGitIntegrationStore
}

// NewMockGitIntegrationStore creates a new mock instance.
func NewMockGitIntegrationStore(ctrl *gomock.Controller) *MockGitIntegrationStore {
	mock := &MockGitIntegrationStore{ctrl: ctrl}
	mock.recorder = &MockGitIntegrationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitIntegrationStore) EXPECT() *MockGitIntegrationStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGitIntegrationStore) Create(ctx context.Context, integration *models.GitIntegration) (*models.GitIntegration, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, integration)
	ret0, _ := ret[0].(*models.GitIntegration)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGitIntegrationStoreMockRecorder) Create(ctx, integration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGitIntegrationStore)(nil).Create), ctx, integration)
}

// Delete mocks base method.
func (m *MockGitIntegrationStore) Delete(ctx context.Context, ID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGitIntegrationStoreMockRecorder) Delete(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGitIntegrationStore)(nil).Delete), ctx, ID)
}

// GetByID mocks base method.
func (m *MockGitIntegrationStore) GetByID(ctx context.Context, ID string) (*models.GitIntegration, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, ID)
	ret0, _ := ret[0].(*models.GitIntegration)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGitIntegrationStoreMockRecorder) GetByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGitIntegrationStore)(nil).GetByID), ctx, ID)
}

// GetByOrgAndHost mocks base method.
func (m *MockGitIntegrationStore) GetByOrgAndHost(ctx context.Context, organisationID, host string) (*models.GitIntegration, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgAndHost", ctx, organisationID, host)
	ret0, _ := ret[0].(*models.GitIntegration)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByOrgAndHost indicates an expected call of GetByOrgAndHost.
func (mr *MockGitIntegrationStoreMockRecorder) GetByOrgAndHost(ctx, organisationID, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgAndHost", reflect.TypeOf((*MockGitIntegrationStore)(nil).GetByOrgAndHost), ctx, organisationID, host)
}

// GetGitHubAppForOrg mocks base method.
func (m *MockGitIntegrationStore) GetGitHubAppForOrg(ctx context.Context, organisationID string) (*models.GitIntegration, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitHubAppForOrg", ctx, organisationID)
	ret0, _ := ret[0].(*models.GitIntegration)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetGitHubAppForOrg indicates an expected call of GetGitHubAppForOrg.
func (mr *MockGitIntegrationStoreMockRecorder) GetGitHubAppForOrg(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitHubAppForOrg", reflect.TypeOf((*MockGitIntegrationStore)(nil).GetGitHubAppForOrg), ctx, organisationID)
}

// ListByOrgID mocks base method.
func (m *MockGitIntegrationStore) ListByOrgID(ctx context.Context, organisationID string) ([]*models.GitIntegration, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrgID", ctx, organisationID)
	ret0, _ := ret[0].([]*models.GitIntegration)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByOrgID indicates an expected call of ListByOrgID.
func (mr *MockGitIntegrationStoreMockRecorder) ListByOrgID(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrgID", reflect.TypeOf((*MockGitIntegrationStore)(nil).ListByOrgID), ctx, organisationID)
}

// ListGitHubApps mocks base method.
func (m *MockGitIntegrationStore) ListGitHubApps(ctx context.Context) ([]*models.GitIntegration, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGitHubApps", ctx)
	ret0, _ := ret[0].([]*models.GitIntegration)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListGitHubApps indicates an expected call of ListGitHubApps.
func (mr *MockGitIntegrationStoreMockRecorder) ListGitHubApps(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGitHubApps", reflect.TypeOf((*MockGitIntegrationStore)(nil).ListGitHubApps), ctx)
}

// Update mocks base method.
func (m *MockGitIntegrationStore) Update(ctx context.Context, integration *models.GitIntegration) (*models.GitIntegration, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, integration)
	ret0, _ := ret[0].(*models.GitIntegration)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGitIntegrationStoreMockRecorder) Update(ctx, integration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGitIntegrationStore)(nil).Update), ctx, integration)
}
