// Code generated by MockGen. DO NOT EDIT.
// Source: secret.go
//
// Generated by this command:
//
//	mockgen -source=secret.go -destination=../mocks/mock_secret_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	stores "github.com/Stackdome/stackdome/pkg/stores"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretStore is a mock of SecretStore interface.
type MockSecretStore struct {
	ctrl     *gomock.Controller
	recorder *MockSecretStoreMockRecorder
	isgomock struct{}
}

// MockSecretStoreMockRecorder is the mock recorder for MockSecretStore.
type MockSecretStoreMockRecorder struct {
	mock *MockSecretStore
}

// NewMockSecretStore creates a new mock instance.
func NewMockSecretStore(ctrl *gomock.Controller) *MockSecretStore {
	mock := &MockSecretStore{ctrl: ctrl}
	mock.recorder = &MockSecretStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretStore) EXPECT() *MockSecretStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecretStore) Create(ctx context.Context, secret *models.Secret) (*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, secret)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSecretStoreMockRecorder) Create(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecretStore)(nil).Create), ctx, secret)
}

// Delete mocks base method.
func (m *MockSecretStore) Delete(ctx context.Context, ID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecretStoreMockRecorder) Delete(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSecretStore)(nil).Delete), ctx, ID)
}

// GetByID mocks base method.
func (m *MockSecretStore) GetByID(ctx context.Context, ID string) (*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, ID)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSecretStoreMockRecorder) GetByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSecretStore)(nil).GetByID), ctx, ID)
}

// GetByName mocks base method.
func (m *MockSecretStore) GetByName(ctx context.Context, organisationID, name string) (*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, organisationID, name)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockSecretStoreMockRecorder) GetByName(ctx, organisationID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockSecretStore)(nil).GetByName), ctx, organisationID, name)
}

// GetSecretKeys mocks base method.
func (m *MockSecretStore) GetSecretKeys(ctx context.Context, secretID string) ([]string, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretKeys", ctx, secretID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetSecretKeys indicates an expected call of GetSecretKeys.
func (mr *MockSecretStoreMockRecorder) GetSecretKeys(ctx, secretID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretKeys", reflect.TypeOf((*MockSecretStore)(nil).GetSecretKeys), ctx, secretID)
}

// ListByOrganisation mocks base method.
func (m *MockSecretStore) ListByOrganisation(ctx context.Context, organisationID string, params stores.ListParams) ([]*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrganisation", ctx, organisationID, params)
	ret0, _ := ret[0].([]*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByOrganisation indicates an expected call of ListByOrganisation.
func (mr *MockSecretStoreMockRecorder) ListByOrganisation(ctx, organisationID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrganisation", reflect.TypeOf((*MockSecretStore)(nil).ListByOrganisation), ctx, organisationID, params)
}

// ListByProjectID mocks base method.
func (m *MockSecretStore) ListByProjectID(ctx context.Context, projectID string, params stores.ListParams) ([]*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProjectID", ctx, projectID, params)
	ret0, _ := ret[0].([]*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByProjectID indicates an expected call of ListByProjectID.
func (mr *MockSecretStoreMockRecorder) ListByProjectID(ctx, projectID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProjectID", reflect.TypeOf((*MockSecretStore)(nil).ListByProjectID), ctx, projectID, params)
}

// ListByProjectIDs mocks base method.
func (m *MockSecretStore) ListByProjectIDs(ctx context.Context, projectIDs []string, params stores.ListParams) ([]*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProjectIDs", ctx, projectIDs, params)
	ret0, _ := ret[0].([]*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByProjectIDs indicates an expected call of ListByProjectIDs.
func (mr *MockSecretStoreMockRecorder) ListByProjectIDs(ctx, projectIDs, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProjectIDs", reflect.TypeOf((*MockSecretStore)(nil).ListByProjectIDs), ctx, projectIDs, params)
}

// ListByType mocks base method.
func (m *MockSecretStore) ListByType(ctx context.Context, organisationID, secretType models.SecretType) ([]*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByType", ctx, organisationID, secretType)
	ret0, _ := ret[0].([]*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByType indicates an expected call of ListByType.
func (mr *MockSecretStoreMockRecorder) ListByType(ctx, organisationID, secretType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByType", reflect.TypeOf((*MockSecretStore)(nil).ListByType), ctx, organisationID, secretType)
}

// ListByUser mocks base method.
func (m *MockSecretStore) ListByUser(ctx context.Context, organisationID, userID string) ([]*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, organisationID, userID)
	ret0, _ := ret[0].([]*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockSecretStoreMockRecorder) ListByUser(ctx, organisationID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockSecretStore)(nil).ListByUser), ctx, organisationID, userID)
}

// Update mocks base method.
func (m *MockSecretStore) Update(ctx context.Context, secret *models.Secret) (*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, secret)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSecretStoreMockRecorder) Update(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSecretStore)(nil).Update), ctx, secret)
}

// UpdateEncryptedData mocks base method.
func (m *MockSecretStore) UpdateEncryptedData(ctx context.Context, secretID, encryptedData string, keys []string, dataHash string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEncryptedData", ctx, secretID, encryptedData, keys, dataHash)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// UpdateEncryptedData indicates an expected call of UpdateEncryptedData.
func (mr *MockSecretStoreMockRecorder) UpdateEncryptedData(ctx, secretID, encryptedData, keys, dataHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEncryptedData", reflect.TypeOf((*MockSecretStore)(nil).UpdateEncryptedData), ctx, secretID, encryptedData, keys, dataHash)
}

// ValidateSecretExists mocks base method.
func (m *MockSecretStore) ValidateSecretExists(ctx context.Context, secretID string) (bool, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSecretExists", ctx, secretID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ValidateSecretExists indicates an expected call of ValidateSecretExists.
func (mr *MockSecretStoreMockRecorder) ValidateSecretExists(ctx, secretID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSecretExists", reflect.TypeOf((*MockSecretStore)(nil).ValidateSecretExists), ctx, secretID)
}

// ValidateSecretHasKeys mocks base method.
func (m *MockSecretStore) ValidateSecretHasKeys(ctx context.Context, secretID string, requiredKeys []string) (bool, []string, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSecretHasKeys", ctx, secretID, requiredKeys)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(*errors.ServiceError)
	return ret0, ret1, ret2
}

// ValidateSecretHasKeys indicates an expected call of ValidateSecretHasKeys.
func (mr *MockSecretStoreMockRecorder) ValidateSecretHasKeys(ctx, secretID, requiredKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSecretHasKeys", reflect.TypeOf((*MockSecretStore)(nil).ValidateSecretHasKeys), ctx, secretID, requiredKeys)
}
