// Code generated by MockGen. DO NOT EDIT.
// Source: trial_allocation_store.go
//
// Generated by this command:
//
//	mockgen -source=trial_allocation_store.go -destination=../mocks/mock_trial_allocation_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTrialAllocationStore is a mock of TrialAllocationStore interface.
type MockTrialAllocationStore struct {
	ctrl     *gomock.Controller
	recorder *MockTrialAllocationStoreMockRecorder
	isgomock struct{}
}

// MockTrialAllocationStoreMockRecorder is the mock recorder for MockTrialAllocationStore.
type MockTrialAllocationStoreMockRecorder struct {
	mock *MockTrialAllocationStore
}

// NewMockTrialAllocationStore creates a new mock instance.
func NewMockTrialAllocationStore(ctrl *gomock.Controller) *MockTrialAllocationStore {
	mock := &MockTrialAllocationStore{ctrl: ctrl}
	mock.recorder = &MockTrialAllocationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrialAllocationStore) EXPECT() *MockTrialAllocationStoreMockRecorder {
	return m.recorder
}

// AcquireWithTx mocks base method.
func (m *MockTrialAllocationStore) AcquireWithTx(ctx context.Context, organisationID string, now, expiresAt time.Time, capacity int) (*models.TrialAllocation, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireWithTx", ctx, organisationID, now, expiresAt, capacity)
	ret0, _ := ret[0].(*models.TrialAllocation)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// AcquireWithTx indicates an expected call of AcquireWithTx.
func (mr *MockTrialAllocationStoreMockRecorder) AcquireWithTx(ctx, organisationID, now, expiresAt, capacity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireWithTx", reflect.TypeOf((*MockTrialAllocationStore)(nil).AcquireWithTx), ctx, organisationID, now, expiresAt, capacity)
}

// GetActiveByOrganisationID mocks base method.
func (m *MockTrialAllocationStore) GetActiveByOrganisationID(ctx context.Context, organisationID string, now time.Time) (*models.TrialAllocation, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByOrganisationID", ctx, organisationID, now)
	ret0, _ := ret[0].(*models.TrialAllocation)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetActiveByOrganisationID indicates an expected call of GetActiveByOrganisationID.
func (mr *MockTrialAllocationStoreMockRecorder) GetActiveByOrganisationID(ctx, organisationID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByOrganisationID", reflect.TypeOf((*MockTrialAllocationStore)(nil).GetActiveByOrganisationID), ctx, organisationID, now)
}

// GetByOrganisationID mocks base method.
func (m *MockTrialAllocationStore) GetByOrganisationID(ctx context.Context, organisationID string) (*models.TrialAllocation, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrganisationID", ctx, organisationID)
	ret0, _ := ret[0].(*models.TrialAllocation)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByOrganisationID indicates an expected call of GetByOrganisationID.
func (mr *MockTrialAllocationStoreMockRecorder) GetByOrganisationID(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrganisationID", reflect.TypeOf((*MockTrialAllocationStore)(nil).GetByOrganisationID), ctx, organisationID)
}

// RevalidateIfExistsWithTx mocks base method.
func (m *MockTrialAllocationStore) RevalidateIfExistsWithTx(ctx context.Context, organisationID string, now time.Time) (*models.TrialAllocation, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevalidateIfExistsWithTx", ctx, organisationID, now)
	ret0, _ := ret[0].(*models.TrialAllocation)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// RevalidateIfExistsWithTx indicates an expected call of RevalidateIfExistsWithTx.
func (mr *MockTrialAllocationStoreMockRecorder) RevalidateIfExistsWithTx(ctx, organisationID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevalidateIfExistsWithTx", reflect.TypeOf((*MockTrialAllocationStore)(nil).RevalidateIfExistsWithTx), ctx, organisationID, now)
}

// RevalidateWithTx mocks base method.
func (m *MockTrialAllocationStore) RevalidateWithTx(ctx context.Context, organisationID string, now time.Time) (*models.TrialAllocation, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevalidateWithTx", ctx, organisationID, now)
	ret0, _ := ret[0].(*models.TrialAllocation)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// RevalidateWithTx indicates an expected call of RevalidateWithTx.
func (mr *MockTrialAllocationStoreMockRecorder) RevalidateWithTx(ctx, organisationID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevalidateWithTx", reflect.TypeOf((*MockTrialAllocationStore)(nil).RevalidateWithTx), ctx, organisationID, now)
}
