// Code generated by MockGen. DO NOT EDIT.
// Source: organisation_domain.go
//
// Generated by this command:
//
//	mockgen -source=organisation_domain.go -destination=../mocks/mock_organisation_domain_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganisationDomainStore is a mock of OrganisationDomainStore interface.
type MockOrganisationDomainStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrganisationDomainStoreMockRecorder
	isgomock struct{}
}

// MockOrganisationDomainStoreMockRecorder is the mock recorder for MockOrganisationDomainStore.
type MockOrganisationDomainStoreMockRecorder struct {
	mock *MockOrganisationDomainStore
}

// NewMockOrganisationDomainStore creates a new mock instance.
func NewMockOrganisationDomainStore(ctrl *gomock.Controller) *MockOrganisationDomainStore {
	mock := &MockOrganisationDomainStore{ctrl: ctrl}
	mock.recorder = &MockOrganisationDomainStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganisationDomainStore) EXPECT() *MockOrganisationDomainStoreMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockOrganisationDomainStore) BulkCreate(ctx context.Context, domains []*models.OrganisationDomain) ([]*models.OrganisationDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, domains)
	ret0, _ := ret[0].([]*models.OrganisationDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockOrganisationDomainStoreMockRecorder) BulkCreate(ctx, domains any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockOrganisationDomainStore)(nil).BulkCreate), ctx, domains)
}

// Create mocks base method.
func (m *MockOrganisationDomainStore) Create(ctx context.Context, domain *models.OrganisationDomain) (*models.OrganisationDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, domain)
	ret0, _ := ret[0].(*models.OrganisationDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrganisationDomainStoreMockRecorder) Create(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganisationDomainStore)(nil).Create), ctx, domain)
}

// CreateWithTx mocks base method.
func (m *MockOrganisationDomainStore) CreateWithTx(ctx context.Context, domain *models.OrganisationDomain) (*models.OrganisationDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, domain)
	ret0, _ := ret[0].(*models.OrganisationDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockOrganisationDomainStoreMockRecorder) CreateWithTx(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockOrganisationDomainStore)(nil).CreateWithTx), ctx, domain)
}

// Delete mocks base method.
func (m *MockOrganisationDomainStore) Delete(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganisationDomainStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganisationDomainStore)(nil).Delete), ctx, id)
}

// DeleteWithTx mocks base method.
func (m *MockOrganisationDomainStore) DeleteWithTx(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTx", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// DeleteWithTx indicates an expected call of DeleteWithTx.
func (mr *MockOrganisationDomainStoreMockRecorder) DeleteWithTx(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTx", reflect.TypeOf((*MockOrganisationDomainStore)(nil).DeleteWithTx), ctx, id)
}

// Get mocks base method.
func (m *MockOrganisationDomainStore) Get(ctx context.Context, id string) (*models.OrganisationDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.OrganisationDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrganisationDomainStoreMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrganisationDomainStore)(nil).Get), ctx, id)
}

// ListByOrganisationID mocks base method.
func (m *MockOrganisationDomainStore) ListByOrganisationID(ctx context.Context, organisationID string) ([]*models.OrganisationDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrganisationID", ctx, organisationID)
	ret0, _ := ret[0].([]*models.OrganisationDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByOrganisationID indicates an expected call of ListByOrganisationID.
func (mr *MockOrganisationDomainStoreMockRecorder) ListByOrganisationID(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrganisationID", reflect.TypeOf((*MockOrganisationDomainStore)(nil).ListByOrganisationID), ctx, organisationID)
}

// Update mocks base method.
func (m *MockOrganisationDomainStore) Update(ctx context.Context, id string, domain *models.OrganisationDomain) (*models.OrganisationDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, domain)
	ret0, _ := ret[0].(*models.OrganisationDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrganisationDomainStoreMockRecorder) Update(ctx, id, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganisationDomainStore)(nil).Update), ctx, id, domain)
}
