// Code generated by MockGen. DO NOT EDIT.
// Source: stack_domains_store.go
//
// Generated by this command:
//
//	mockgen -source=stack_domains_store.go -destination=../mocks/mock_stack_domains_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockStackDomainsStore is a mock of StackDomainsStore interface.
type MockStackDomainsStore struct {
	ctrl     *gomock.Controller
	recorder *MockStackDomainsStoreMockRecorder
	isgomock struct{}
}

// MockStackDomainsStoreMockRecorder is the mock recorder for MockStackDomainsStore.
type MockStackDomainsStoreMockRecorder struct {
	mock *MockStackDomainsStore
}

// NewMockStackDomainsStore creates a new mock instance.
func NewMockStackDomainsStore(ctrl *gomock.Controller) *MockStackDomainsStore {
	mock := &MockStackDomainsStore{ctrl: ctrl}
	mock.recorder = &MockStackDomainsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStackDomainsStore) EXPECT() *MockStackDomainsStoreMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockStackDomainsStore) BulkCreate(ctx context.Context, domains []*models.StackDomain) (models.StackDomainList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, domains)
	ret0, _ := ret[0].(models.StackDomainList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockStackDomainsStoreMockRecorder) BulkCreate(ctx, domains any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockStackDomainsStore)(nil).BulkCreate), ctx, domains)
}

// Create mocks base method.
func (m *MockStackDomainsStore) Create(ctx context.Context, domain *models.StackDomain) (*models.StackDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, domain)
	ret0, _ := ret[0].(*models.StackDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStackDomainsStoreMockRecorder) Create(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStackDomainsStore)(nil).Create), ctx, domain)
}

// CreateWithTx mocks base method.
func (m *MockStackDomainsStore) CreateWithTx(ctx context.Context, domain *models.StackDomain) (*models.StackDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, domain)
	ret0, _ := ret[0].(*models.StackDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockStackDomainsStoreMockRecorder) CreateWithTx(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockStackDomainsStore)(nil).CreateWithTx), ctx, domain)
}

// Delete mocks base method.
func (m *MockStackDomainsStore) Delete(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStackDomainsStoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStackDomainsStore)(nil).Delete), ctx, id)
}

// DeleteForStackResourceAndPort mocks base method.
func (m *MockStackDomainsStore) DeleteForStackResourceAndPort(ctx context.Context, stackResourceID string, port int) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForStackResourceAndPort", ctx, stackResourceID, port)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// DeleteForStackResourceAndPort indicates an expected call of DeleteForStackResourceAndPort.
func (mr *MockStackDomainsStoreMockRecorder) DeleteForStackResourceAndPort(ctx, stackResourceID, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForStackResourceAndPort", reflect.TypeOf((*MockStackDomainsStore)(nil).DeleteForStackResourceAndPort), ctx, stackResourceID, port)
}

// DeleteForStackResourceAndPortWithTx mocks base method.
func (m *MockStackDomainsStore) DeleteForStackResourceAndPortWithTx(ctx context.Context, stackResourceID string, port int) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForStackResourceAndPortWithTx", ctx, stackResourceID, port)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// DeleteForStackResourceAndPortWithTx indicates an expected call of DeleteForStackResourceAndPortWithTx.
func (mr *MockStackDomainsStoreMockRecorder) DeleteForStackResourceAndPortWithTx(ctx, stackResourceID, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForStackResourceAndPortWithTx", reflect.TypeOf((*MockStackDomainsStore)(nil).DeleteForStackResourceAndPortWithTx), ctx, stackResourceID, port)
}

// DeleteWithTx mocks base method.
func (m *MockStackDomainsStore) DeleteWithTx(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTx", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// DeleteWithTx indicates an expected call of DeleteWithTx.
func (mr *MockStackDomainsStoreMockRecorder) DeleteWithTx(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTx", reflect.TypeOf((*MockStackDomainsStore)(nil).DeleteWithTx), ctx, id)
}

// Get mocks base method.
func (m *MockStackDomainsStore) Get(ctx context.Context, id string) (*models.StackDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.StackDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStackDomainsStoreMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStackDomainsStore)(nil).Get), ctx, id)
}

// GetByFqdn mocks base method.
func (m *MockStackDomainsStore) GetByFqdn(ctx context.Context, fqdn string) (*models.StackDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFqdn", ctx, fqdn)
	ret0, _ := ret[0].(*models.StackDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByFqdn indicates an expected call of GetByFqdn.
func (mr *MockStackDomainsStoreMockRecorder) GetByFqdn(ctx, fqdn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFqdn", reflect.TypeOf((*MockStackDomainsStore)(nil).GetByFqdn), ctx, fqdn)
}

// GetByStackResourceAndPort mocks base method.
func (m *MockStackDomainsStore) GetByStackResourceAndPort(ctx context.Context, stackResourceID string, port int) (*models.StackDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStackResourceAndPort", ctx, stackResourceID, port)
	ret0, _ := ret[0].(*models.StackDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByStackResourceAndPort indicates an expected call of GetByStackResourceAndPort.
func (mr *MockStackDomainsStoreMockRecorder) GetByStackResourceAndPort(ctx, stackResourceID, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStackResourceAndPort", reflect.TypeOf((*MockStackDomainsStore)(nil).GetByStackResourceAndPort), ctx, stackResourceID, port)
}

// ListByFqdnPrefix mocks base method.
func (m *MockStackDomainsStore) ListByFqdnPrefix(ctx context.Context, prefix string) (models.StackDomainList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFqdnPrefix", ctx, prefix)
	ret0, _ := ret[0].(models.StackDomainList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByFqdnPrefix indicates an expected call of ListByFqdnPrefix.
func (mr *MockStackDomainsStoreMockRecorder) ListByFqdnPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFqdnPrefix", reflect.TypeOf((*MockStackDomainsStore)(nil).ListByFqdnPrefix), ctx, prefix)
}

// ListByOrganisationID mocks base method.
func (m *MockStackDomainsStore) ListByOrganisationID(ctx context.Context, organisationID string) (models.StackDomainList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrganisationID", ctx, organisationID)
	ret0, _ := ret[0].(models.StackDomainList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByOrganisationID indicates an expected call of ListByOrganisationID.
func (mr *MockStackDomainsStoreMockRecorder) ListByOrganisationID(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrganisationID", reflect.TypeOf((*MockStackDomainsStore)(nil).ListByOrganisationID), ctx, organisationID)
}

// ListByStackID mocks base method.
func (m *MockStackDomainsStore) ListByStackID(ctx context.Context, stackID string) (models.StackDomainList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStackID", ctx, stackID)
	ret0, _ := ret[0].(models.StackDomainList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByStackID indicates an expected call of ListByStackID.
func (mr *MockStackDomainsStoreMockRecorder) ListByStackID(ctx, stackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStackID", reflect.TypeOf((*MockStackDomainsStore)(nil).ListByStackID), ctx, stackID)
}

// ListByStackResourceID mocks base method.
func (m *MockStackDomainsStore) ListByStackResourceID(ctx context.Context, stackResourceID string) (models.StackDomainList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStackResourceID", ctx, stackResourceID)
	ret0, _ := ret[0].(models.StackDomainList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByStackResourceID indicates an expected call of ListByStackResourceID.
func (mr *MockStackDomainsStoreMockRecorder) ListByStackResourceID(ctx, stackResourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStackResourceID", reflect.TypeOf((*MockStackDomainsStore)(nil).ListByStackResourceID), ctx, stackResourceID)
}

// Update mocks base method.
func (m *MockStackDomainsStore) Update(ctx context.Context, id string, domain *models.StackDomain) (*models.StackDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, domain)
	ret0, _ := ret[0].(*models.StackDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStackDomainsStoreMockRecorder) Update(ctx, id, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStackDomainsStore)(nil).Update), ctx, id, domain)
}
