// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go
//
// Generated by this command:
//
//	mockgen -source=validator.go -destination=validator_mock_test.go -package=stackresource
//

// Package stackresource is a generated GoMock package.
package stackresource

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockValidator) Validate(ctx context.Context, stack *models.Stack, resource *models.StackResource, siblings []*models.StackResource) ([]errors.FieldError, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, stack, resource, siblings)
	ret0, _ := ret[0].([]errors.FieldError)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockValidatorMockRecorder) Validate(ctx, stack, resource, siblings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidator)(nil).Validate), ctx, stack, resource, siblings)
}

// MockvolumeGetter is a mock of volumeGetter interface.
type MockvolumeGetter struct {
	ctrl     *gomock.Controller
	recorder *MockvolumeGetterMockRecorder
	isgomock struct{}
}

// MockvolumeGetterMockRecorder is the mock recorder for MockvolumeGetter.
type MockvolumeGetterMockRecorder struct {
	mock *MockvolumeGetter
}

// NewMockvolumeGetter creates a new mock instance.
func NewMockvolumeGetter(ctrl *gomock.Controller) *MockvolumeGetter {
	mock := &MockvolumeGetter{ctrl: ctrl}
	mock.recorder = &MockvolumeGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvolumeGetter) EXPECT() *MockvolumeGetterMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockvolumeGetter) GetByID(ctx context.Context, id string) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockvolumeGetterMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockvolumeGetter)(nil).GetByID), ctx, id)
}

// GetByVolumeNameAndNamespace mocks base method.
func (m *MockvolumeGetter) GetByVolumeNameAndNamespace(ctx context.Context, volumeName, namespace string) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVolumeNameAndNamespace", ctx, volumeName, namespace)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByVolumeNameAndNamespace indicates an expected call of GetByVolumeNameAndNamespace.
func (mr *MockvolumeGetterMockRecorder) GetByVolumeNameAndNamespace(ctx, volumeName, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVolumeNameAndNamespace", reflect.TypeOf((*MockvolumeGetter)(nil).GetByVolumeNameAndNamespace), ctx, volumeName, namespace)
}

// MocksecretGetter is a mock of secretGetter interface.
type MocksecretGetter struct {
	ctrl     *gomock.Controller
	recorder *MocksecretGetterMockRecorder
	isgomock struct{}
}

// MocksecretGetterMockRecorder is the mock recorder for MocksecretGetter.
type MocksecretGetterMockRecorder struct {
	mock *MocksecretGetter
}

// NewMocksecretGetter creates a new mock instance.
func NewMocksecretGetter(ctrl *gomock.Controller) *MocksecretGetter {
	mock := &MocksecretGetter{ctrl: ctrl}
	mock.recorder = &MocksecretGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretGetter) EXPECT() *MocksecretGetterMockRecorder {
	return m.recorder
}

// GetByName mocks base method.
func (m *MocksecretGetter) GetByName(ctx context.Context, organisationID, name string) (*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, organisationID, name)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MocksecretGetterMockRecorder) GetByName(ctx, organisationID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MocksecretGetter)(nil).GetByName), ctx, organisationID, name)
}

// MockdomainLister is a mock of domainLister interface.
type MockdomainLister struct {
	ctrl     *gomock.Controller
	recorder *MockdomainListerMockRecorder
	isgomock struct{}
}

// MockdomainListerMockRecorder is the mock recorder for MockdomainLister.
type MockdomainListerMockRecorder struct {
	mock *MockdomainLister
}

// NewMockdomainLister creates a new mock instance.
func NewMockdomainLister(ctrl *gomock.Controller) *MockdomainLister {
	mock := &MockdomainLister{ctrl: ctrl}
	mock.recorder = &MockdomainListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdomainLister) EXPECT() *MockdomainListerMockRecorder {
	return m.recorder
}

// ListByOrganisationID mocks base method.
func (m *MockdomainLister) ListByOrganisationID(ctx context.Context, organisationID string) ([]*models.OrganisationDomain, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrganisationID", ctx, organisationID)
	ret0, _ := ret[0].([]*models.OrganisationDomain)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListByOrganisationID indicates an expected call of ListByOrganisationID.
func (mr *MockdomainListerMockRecorder) ListByOrganisationID(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrganisationID", reflect.TypeOf((*MockdomainLister)(nil).ListByOrganisationID), ctx, organisationID)
}

// MockgitIntegrationGetter is a mock of gitIntegrationGetter interface.
type MockgitIntegrationGetter struct {
	ctrl     *gomock.Controller
	recorder *MockgitIntegrationGetterMockRecorder
	isgomock struct{}
}

// MockgitIntegrationGetterMockRecorder is the mock recorder for MockgitIntegrationGetter.
type MockgitIntegrationGetterMockRecorder struct {
	mock *MockgitIntegrationGetter
}

// NewMockgitIntegrationGetter creates a new mock instance.
func NewMockgitIntegrationGetter(ctrl *gomock.Controller) *MockgitIntegrationGetter {
	mock := &MockgitIntegrationGetter{ctrl: ctrl}
	mock.recorder = &MockgitIntegrationGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgitIntegrationGetter) EXPECT() *MockgitIntegrationGetterMockRecorder {
	return m.recorder
}

// InternalGetByID mocks base method.
func (m *MockgitIntegrationGetter) InternalGetByID(ctx context.Context, ID string) (*models.GitIntegration, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetByID", ctx, ID)
	ret0, _ := ret[0].(*models.GitIntegration)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalGetByID indicates an expected call of InternalGetByID.
func (mr *MockgitIntegrationGetterMockRecorder) InternalGetByID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetByID", reflect.TypeOf((*MockgitIntegrationGetter)(nil).InternalGetByID), ctx, ID)
}
