// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Stackdome/stackdome/pkg/services (interfaces: PreviewWebhookService)
//
// Generated by this command:
//
//	mockgen -destination=preview_webhook_service_mock.go -package=services -self_package=github.com/Stackdome/stackdome/pkg/services github.com/Stackdome/stackdome/pkg/services PreviewWebhookService
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockPreviewWebhookService is a mock of PreviewWebhookService interface.
type MockPreviewWebhookService struct {
	ctrl     *gomock.Controller
	recorder *MockPreviewWebhookServiceMockRecorder
	isgomock struct{}
}

// MockPreviewWebhookServiceMockRecorder is the mock recorder for MockPreviewWebhookService.
type MockPreviewWebhookServiceMockRecorder struct {
	mock *MockPreviewWebhookService
}

// NewMockPreviewWebhookService creates a new mock instance.
func NewMockPreviewWebhookService(ctrl *gomock.Controller) *MockPreviewWebhookService {
	mock := &MockPreviewWebhookService{ctrl: ctrl}
	mock.recorder = &MockPreviewWebhookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreviewWebhookService) EXPECT() *MockPreviewWebhookServiceMockRecorder {
	return m.recorder
}

// HandlePullRequest mocks base method.
func (m *MockPreviewWebhookService) HandlePullRequest(ctx context.Context, ev PullRequestEvent) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePullRequest", ctx, ev)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// HandlePullRequest indicates an expected call of HandlePullRequest.
func (mr *MockPreviewWebhookServiceMockRecorder) HandlePullRequest(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePullRequest", reflect.TypeOf((*MockPreviewWebhookService)(nil).HandlePullRequest), ctx, ev)
}
