// Code generated by MockGen. DO NOT EDIT.
// Source: runtime_policy.go
//
// Generated by this command:
//
//	mockgen -source=runtime_policy.go -destination=runtime_policy_mock.go -package=services -self_package=github.com/Stackdome/stackdome/pkg/services
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRuntimePolicy is a mock of RuntimePolicy interface.
type MockRuntimePolicy struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimePolicyMockRecorder
	isgomock struct{}
}

// MockRuntimePolicyMockRecorder is the mock recorder for MockRuntimePolicy.
type MockRuntimePolicyMockRecorder struct {
	mock *MockRuntimePolicy
}

// NewMockRuntimePolicy creates a new mock instance.
func NewMockRuntimePolicy(ctrl *gomock.Controller) *MockRuntimePolicy {
	mock := &MockRuntimePolicy{ctrl: ctrl}
	mock.recorder = &MockRuntimePolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimePolicy) EXPECT() *MockRuntimePolicyMockRecorder {
	return m.recorder
}

// ApplyPostgresAddonDefaults mocks base method.
func (m *MockRuntimePolicy) ApplyPostgresAddonDefaults(addon *models.PostgresAddon) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplyPostgresAddonDefaults", addon)
}

// ApplyPostgresAddonDefaults indicates an expected call of ApplyPostgresAddonDefaults.
func (mr *MockRuntimePolicyMockRecorder) ApplyPostgresAddonDefaults(addon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPostgresAddonDefaults", reflect.TypeOf((*MockRuntimePolicy)(nil).ApplyPostgresAddonDefaults), addon)
}

// ApplyStackResourceDefaults mocks base method.
func (m *MockRuntimePolicy) ApplyStackResourceDefaults(resource *models.StackResource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplyStackResourceDefaults", resource)
}

// ApplyStackResourceDefaults indicates an expected call of ApplyStackResourceDefaults.
func (mr *MockRuntimePolicyMockRecorder) ApplyStackResourceDefaults(resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyStackResourceDefaults", reflect.TypeOf((*MockRuntimePolicy)(nil).ApplyStackResourceDefaults), resource)
}

// EnsureComputeAccess mocks base method.
func (m *MockRuntimePolicy) EnsureComputeAccess(ctx context.Context, organisationID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureComputeAccess", ctx, organisationID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// EnsureComputeAccess indicates an expected call of EnsureComputeAccess.
func (mr *MockRuntimePolicyMockRecorder) EnsureComputeAccess(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureComputeAccess", reflect.TypeOf((*MockRuntimePolicy)(nil).EnsureComputeAccess), ctx, organisationID)
}

// IsolationPolicyVersion mocks base method.
func (m *MockRuntimePolicy) IsolationPolicyVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsolationPolicyVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// IsolationPolicyVersion indicates an expected call of IsolationPolicyVersion.
func (mr *MockRuntimePolicyMockRecorder) IsolationPolicyVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsolationPolicyVersion", reflect.TypeOf((*MockRuntimePolicy)(nil).IsolationPolicyVersion))
}

// ValidateOrganisationDeletion mocks base method.
func (m *MockRuntimePolicy) ValidateOrganisationDeletion(ctx context.Context, organisationID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateOrganisationDeletion", ctx, organisationID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// ValidateOrganisationDeletion indicates an expected call of ValidateOrganisationDeletion.
func (mr *MockRuntimePolicyMockRecorder) ValidateOrganisationDeletion(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateOrganisationDeletion", reflect.TypeOf((*MockRuntimePolicy)(nil).ValidateOrganisationDeletion), ctx, organisationID)
}

// ValidatePostgresAddonLimits mocks base method.
func (m *MockRuntimePolicy) ValidatePostgresAddonLimits(ctx context.Context, organisationID, existingAddonID string, addon *models.PostgresAddon) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePostgresAddonLimits", ctx, organisationID, existingAddonID, addon)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// ValidatePostgresAddonLimits indicates an expected call of ValidatePostgresAddonLimits.
func (mr *MockRuntimePolicyMockRecorder) ValidatePostgresAddonLimits(ctx, organisationID, existingAddonID, addon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePostgresAddonLimits", reflect.TypeOf((*MockRuntimePolicy)(nil).ValidatePostgresAddonLimits), ctx, organisationID, existingAddonID, addon)
}

// ValidateStackLimits mocks base method.
func (m *MockRuntimePolicy) ValidateStackLimits(ctx context.Context, change StackLimitChange) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStackLimits", ctx, change)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// ValidateStackLimits indicates an expected call of ValidateStackLimits.
func (mr *MockRuntimePolicyMockRecorder) ValidateStackLimits(ctx, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStackLimits", reflect.TypeOf((*MockRuntimePolicy)(nil).ValidateStackLimits), ctx, change)
}

// ValidateVolumeLimits mocks base method.
func (m *MockRuntimePolicy) ValidateVolumeLimits(ctx context.Context, organisationID, size string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateVolumeLimits", ctx, organisationID, size)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// ValidateVolumeLimits indicates an expected call of ValidateVolumeLimits.
func (mr *MockRuntimePolicyMockRecorder) ValidateVolumeLimits(ctx, organisationID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateVolumeLimits", reflect.TypeOf((*MockRuntimePolicy)(nil).ValidateVolumeLimits), ctx, organisationID, size)
}
