// Code generated by MockGen. DO NOT EDIT.
// Source: stack_release_service.go
//
// Generated by this command:
//
//	mockgen -source=stack_release_service.go -destination=stack_release_service_mock_test.go -package=services -exclude_interfaces StackReleaseService
//

// Package services is a generated GoMock package.
package services

import (
	reflect "reflect"

	git "github.com/Stackdome/stackdome/pkg/clients/git"
	gomock "go.uber.org/mock/gomock"
)

// MocksourceGitClientProvider is a mock of sourceGitClientProvider interface.
type MocksourceGitClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MocksourceGitClientProviderMockRecorder
	isgomock struct{}
}

// MocksourceGitClientProviderMockRecorder is the mock recorder for MocksourceGitClientProvider.
type MocksourceGitClientProviderMockRecorder struct {
	mock *MocksourceGitClientProvider
}

// NewMocksourceGitClientProvider creates a new mock instance.
func NewMocksourceGitClientProvider(ctrl *gomock.Controller) *MocksourceGitClientProvider {
	mock := &MocksourceGitClientProvider{ctrl: ctrl}
	mock.recorder = &MocksourceGitClientProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksourceGitClientProvider) EXPECT() *MocksourceGitClientProviderMockRecorder {
	return m.recorder
}

// ClientFor mocks base method.
func (m *MocksourceGitClientProvider) ClientFor(repoURL string, creds git.GitCredentials) (git.GitClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientFor", repoURL, creds)
	ret0, _ := ret[0].(git.GitClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientFor indicates an expected call of ClientFor.
func (mr *MocksourceGitClientProviderMockRecorder) ClientFor(repoURL, creds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientFor", reflect.TypeOf((*MocksourceGitClientProvider)(nil).ClientFor), repoURL, creds)
}
