// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Stackdome/stackdome/pkg/services (interfaces: StackService)
//
// Generated by this command:
//
//	mockgen -destination=stack_service_mock.go -package=services -self_package=github.com/Stackdome/stackdome/pkg/services github.com/Stackdome/stackdome/pkg/services StackService
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	errors "github.com/Stackdome/stackdome/pkg/errors"
	models "github.com/Stackdome/stackdome/pkg/models"
	clusterresource "github.com/Stackdome/stackdome/pkg/services/clusterresource"
	gomock "go.uber.org/mock/gomock"
)

// MockStackService is a mock of StackService interface.
type MockStackService struct {
	ctrl     *gomock.Controller
	recorder *MockStackServiceMockRecorder
	isgomock struct{}
}

// MockStackServiceMockRecorder is the mock recorder for MockStackService.
type MockStackServiceMockRecorder struct {
	mock *MockStackService
}

// NewMockStackService creates a new mock instance.
func NewMockStackService(ctrl *gomock.Controller) *MockStackService {
	mock := &MockStackService{ctrl: ctrl}
	mock.recorder = &MockStackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStackService) EXPECT() *MockStackServiceMockRecorder {
	return m.recorder
}

// ApplyStack mocks base method.
func (m *MockStackService) ApplyStack(ctx context.Context, spec *models.Stack) (*models.Stack, bool, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyStack", ctx, spec)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(*errors.ServiceError)
	return ret0, ret1, ret2
}

// ApplyStack indicates an expected call of ApplyStack.
func (mr *MockStackServiceMockRecorder) ApplyStack(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyStack", reflect.TypeOf((*MockStackService)(nil).ApplyStack), ctx, spec)
}

// CreateStack mocks base method.
func (m *MockStackService) CreateStack(ctx context.Context, spec *models.Stack) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStack", ctx, spec)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// CreateStack indicates an expected call of CreateStack.
func (mr *MockStackServiceMockRecorder) CreateStack(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStack", reflect.TypeOf((*MockStackService)(nil).CreateStack), ctx, spec)
}

// CreateStackConnection mocks base method.
func (m *MockStackService) CreateStackConnection(ctx context.Context, stackID string, connection *models.StackConnection) (*models.StackConnection, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStackConnection", ctx, stackID, connection)
	ret0, _ := ret[0].(*models.StackConnection)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// CreateStackConnection indicates an expected call of CreateStackConnection.
func (mr *MockStackServiceMockRecorder) CreateStackConnection(ctx, stackID, connection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStackConnection", reflect.TypeOf((*MockStackService)(nil).CreateStackConnection), ctx, stackID, connection)
}

// CreateStackVolume mocks base method.
func (m *MockStackService) CreateStackVolume(ctx context.Context, stackID string, volume *models.Volume) (*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStackVolume", ctx, stackID, volume)
	ret0, _ := ret[0].(*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// CreateStackVolume indicates an expected call of CreateStackVolume.
func (mr *MockStackServiceMockRecorder) CreateStackVolume(ctx, stackID, volume any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStackVolume", reflect.TypeOf((*MockStackService)(nil).CreateStackVolume), ctx, stackID, volume)
}

// DeleteStack mocks base method.
func (m *MockStackService) DeleteStack(ctx context.Context, ID string) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStack", ctx, ID)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// DeleteStack indicates an expected call of DeleteStack.
func (mr *MockStackServiceMockRecorder) DeleteStack(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStack", reflect.TypeOf((*MockStackService)(nil).DeleteStack), ctx, ID)
}

// DeleteStackConnection mocks base method.
func (m *MockStackService) DeleteStackConnection(ctx context.Context, stackID, connectionID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStackConnection", ctx, stackID, connectionID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// DeleteStackConnection indicates an expected call of DeleteStackConnection.
func (mr *MockStackServiceMockRecorder) DeleteStackConnection(ctx, stackID, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStackConnection", reflect.TypeOf((*MockStackService)(nil).DeleteStackConnection), ctx, stackID, connectionID)
}

// GetStack mocks base method.
func (m *MockStackService) GetStack(ctx context.Context, ID string) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStack", ctx, ID)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetStack indicates an expected call of GetStack.
func (mr *MockStackServiceMockRecorder) GetStack(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStack", reflect.TypeOf((*MockStackService)(nil).GetStack), ctx, ID)
}

// GetStackTopology mocks base method.
func (m *MockStackService) GetStackTopology(ctx context.Context, ID string) (*models.StackTopology, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStackTopology", ctx, ID)
	ret0, _ := ret[0].(*models.StackTopology)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetStackTopology indicates an expected call of GetStackTopology.
func (mr *MockStackServiceMockRecorder) GetStackTopology(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStackTopology", reflect.TypeOf((*MockStackService)(nil).GetStackTopology), ctx, ID)
}

// GetStacksByOrganisationID mocks base method.
func (m *MockStackService) GetStacksByOrganisationID(ctx context.Context, organisationID string) ([]*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStacksByOrganisationID", ctx, organisationID)
	ret0, _ := ret[0].([]*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetStacksByOrganisationID indicates an expected call of GetStacksByOrganisationID.
func (mr *MockStackServiceMockRecorder) GetStacksByOrganisationID(ctx, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStacksByOrganisationID", reflect.TypeOf((*MockStackService)(nil).GetStacksByOrganisationID), ctx, organisationID)
}

// GetStacksByProjectID mocks base method.
func (m *MockStackService) GetStacksByProjectID(ctx context.Context, projectID string) ([]*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStacksByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// GetStacksByProjectID indicates an expected call of GetStacksByProjectID.
func (mr *MockStackServiceMockRecorder) GetStacksByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStacksByProjectID", reflect.TypeOf((*MockStackService)(nil).GetStacksByProjectID), ctx, projectID)
}

// InjectBackgroundJobEnqueuer mocks base method.
func (m *MockStackService) InjectBackgroundJobEnqueuer(dep clusterresource.BackgroundJobEnqueuerDep) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InjectBackgroundJobEnqueuer", dep)
}

// InjectBackgroundJobEnqueuer indicates an expected call of InjectBackgroundJobEnqueuer.
func (mr *MockStackServiceMockRecorder) InjectBackgroundJobEnqueuer(dep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectBackgroundJobEnqueuer", reflect.TypeOf((*MockStackService)(nil).InjectBackgroundJobEnqueuer), dep)
}

// InjectClusterResourceServiceDeps mocks base method.
func (m *MockStackService) InjectClusterResourceServiceDeps(deps clusterresource.ClusterResourceServiceDeps) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InjectClusterResourceServiceDeps", deps)
}

// InjectClusterResourceServiceDeps indicates an expected call of InjectClusterResourceServiceDeps.
func (mr *MockStackServiceMockRecorder) InjectClusterResourceServiceDeps(deps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectClusterResourceServiceDeps", reflect.TypeOf((*MockStackService)(nil).InjectClusterResourceServiceDeps), deps)
}

// InternalCreateStack mocks base method.
func (m *MockStackService) InternalCreateStack(ctx context.Context, spec *models.Stack) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalCreateStack", ctx, spec)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalCreateStack indicates an expected call of InternalCreateStack.
func (mr *MockStackServiceMockRecorder) InternalCreateStack(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalCreateStack", reflect.TypeOf((*MockStackService)(nil).InternalCreateStack), ctx, spec)
}

// InternalDeleteFromDB mocks base method.
func (m *MockStackService) InternalDeleteFromDB(ctx context.Context, ID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalDeleteFromDB", ctx, ID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// InternalDeleteFromDB indicates an expected call of InternalDeleteFromDB.
func (mr *MockStackServiceMockRecorder) InternalDeleteFromDB(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalDeleteFromDB", reflect.TypeOf((*MockStackService)(nil).InternalDeleteFromDB), ctx, ID)
}

// InternalDeleteStack mocks base method.
func (m *MockStackService) InternalDeleteStack(ctx context.Context, stack *models.Stack) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalDeleteStack", ctx, stack)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalDeleteStack indicates an expected call of InternalDeleteStack.
func (mr *MockStackServiceMockRecorder) InternalDeleteStack(ctx, stack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalDeleteStack", reflect.TypeOf((*MockStackService)(nil).InternalDeleteStack), ctx, stack)
}

// InternalGetStack mocks base method.
func (m *MockStackService) InternalGetStack(ctx context.Context, ID string) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetStack", ctx, ID)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalGetStack indicates an expected call of InternalGetStack.
func (mr *MockStackServiceMockRecorder) InternalGetStack(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetStack", reflect.TypeOf((*MockStackService)(nil).InternalGetStack), ctx, ID)
}

// InternalList mocks base method.
func (m *MockStackService) InternalList(ctx context.Context, query string, args ...any) ([]*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InternalList", varargs...)
	ret0, _ := ret[0].([]*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalList indicates an expected call of InternalList.
func (mr *MockStackServiceMockRecorder) InternalList(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalList", reflect.TypeOf((*MockStackService)(nil).InternalList), varargs...)
}

// InternalUpdateStack mocks base method.
func (m *MockStackService) InternalUpdateStack(ctx context.Context, ID string, spec *models.Stack) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalUpdateStack", ctx, ID, spec)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalUpdateStack indicates an expected call of InternalUpdateStack.
func (mr *MockStackServiceMockRecorder) InternalUpdateStack(ctx, ID, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalUpdateStack", reflect.TypeOf((*MockStackService)(nil).InternalUpdateStack), ctx, ID, spec)
}

// ListStackConnections mocks base method.
func (m *MockStackService) ListStackConnections(ctx context.Context, stackID string) (models.StackConnections, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStackConnections", ctx, stackID)
	ret0, _ := ret[0].(models.StackConnections)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListStackConnections indicates an expected call of ListStackConnections.
func (mr *MockStackServiceMockRecorder) ListStackConnections(ctx, stackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStackConnections", reflect.TypeOf((*MockStackService)(nil).ListStackConnections), ctx, stackID)
}

// ListStacksForCurrentUser mocks base method.
func (m *MockStackService) ListStacksForCurrentUser(ctx context.Context, orgID string) ([]*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStacksForCurrentUser", ctx, orgID)
	ret0, _ := ret[0].([]*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListStacksForCurrentUser indicates an expected call of ListStacksForCurrentUser.
func (mr *MockStackServiceMockRecorder) ListStacksForCurrentUser(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStacksForCurrentUser", reflect.TypeOf((*MockStackService)(nil).ListStacksForCurrentUser), ctx, orgID)
}

// SetReleaseService mocks base method.
func (m *MockStackService) SetReleaseService(rs releaseServiceForStack) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReleaseService", rs)
}

// SetReleaseService indicates an expected call of SetReleaseService.
func (mr *MockStackServiceMockRecorder) SetReleaseService(rs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReleaseService", reflect.TypeOf((*MockStackService)(nil).SetReleaseService), rs)
}

// UpdateStack mocks base method.
func (m *MockStackService) UpdateStack(ctx context.Context, ID string, spec *models.Stack) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStack", ctx, ID, spec)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateStack indicates an expected call of UpdateStack.
func (mr *MockStackServiceMockRecorder) UpdateStack(ctx, ID, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStack", reflect.TypeOf((*MockStackService)(nil).UpdateStack), ctx, ID, spec)
}

// UpdateStackConnection mocks base method.
func (m *MockStackService) UpdateStackConnection(ctx context.Context, stackID, connectionID string, connection *models.StackConnection) (*models.StackConnection, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStackConnection", ctx, stackID, connectionID, connection)
	ret0, _ := ret[0].(*models.StackConnection)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateStackConnection indicates an expected call of UpdateStackConnection.
func (mr *MockStackServiceMockRecorder) UpdateStackConnection(ctx, stackID, connectionID, connection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStackConnection", reflect.TypeOf((*MockStackService)(nil).UpdateStackConnection), ctx, stackID, connectionID, connection)
}

// UpdateStackCrRevision mocks base method.
func (m *MockStackService) UpdateStackCrRevision(ctx context.Context, ID, revision string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStackCrRevision", ctx, ID, revision)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// UpdateStackCrRevision indicates an expected call of UpdateStackCrRevision.
func (mr *MockStackServiceMockRecorder) UpdateStackCrRevision(ctx, ID, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStackCrRevision", reflect.TypeOf((*MockStackService)(nil).UpdateStackCrRevision), ctx, ID, revision)
}

// UpdateStackShell mocks base method.
func (m *MockStackService) UpdateStackShell(ctx context.Context, ID string, spec *models.Stack) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStackShell", ctx, ID, spec)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateStackShell indicates an expected call of UpdateStackShell.
func (mr *MockStackServiceMockRecorder) UpdateStackShell(ctx, ID, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStackShell", reflect.TypeOf((*MockStackService)(nil).UpdateStackShell), ctx, ID, spec)
}

// UpdateStatus mocks base method.
func (m *MockStackService) UpdateStatus(ctx context.Context, ID string, status *models.StackStatus) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, ID, status)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockStackServiceMockRecorder) UpdateStatus(ctx, ID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockStackService)(nil).UpdateStatus), ctx, ID, status)
}
