[request_definition]
r = subject, domain, resource, action

[policy_definition]
p = subject, domain, resource, action

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = ((g(r.subject, p.subject, r.domain) && keyMatch(r.resource, p.resource) && (p.domain == "*" || r.domain == p.domain)) \
    || (r.subject == p.subject && keyMatch(r.resource, p.resource) && r.domain == p.domain)) \
    && (r.action == p.action || p.action == "*")
