// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=types_mock.go -package=stack
//

// Package stack is a generated GoMock package.
package stack

import (
	context "context"
	reflect "reflect"

	errors "github.com/ashishmax31/stackdome-api-server/pkg/errors"
	models "github.com/ashishmax31/stackdome-api-server/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MocksubReconciler is a mock of subReconciler interface.
type MocksubReconciler struct {
	ctrl     *gomock.Controller
	recorder *MocksubReconcilerMockRecorder
	isgomock struct{}
}

// MocksubReconcilerMockRecorder is the mock recorder for MocksubReconciler.
type MocksubReconcilerMockRecorder struct {
	mock *MocksubReconciler
}

// NewMocksubReconciler creates a new mock instance.
func NewMocksubReconciler(ctrl *gomock.Controller) *MocksubReconciler {
	mock := &MocksubReconciler{ctrl: ctrl}
	mock.recorder = &MocksubReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubReconciler) EXPECT() *MocksubReconcilerMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MocksubReconciler) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MocksubReconcilerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MocksubReconciler)(nil).Name))
}

// Reconcile mocks base method.
func (m *MocksubReconciler) Reconcile(ctx context.Context, stack *models.Stack) (subReconcilerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, stack)
	ret0, _ := ret[0].(subReconcilerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MocksubReconcilerMockRecorder) Reconcile(ctx, stack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MocksubReconciler)(nil).Reconcile), ctx, stack)
}

// MockstackService is a mock of stackService interface.
type MockstackService struct {
	ctrl     *gomock.Controller
	recorder *MockstackServiceMockRecorder
	isgomock struct{}
}

// MockstackServiceMockRecorder is the mock recorder for MockstackService.
type MockstackServiceMockRecorder struct {
	mock *MockstackService
}

// NewMockstackService creates a new mock instance.
func NewMockstackService(ctrl *gomock.Controller) *MockstackService {
	mock := &MockstackService{ctrl: ctrl}
	mock.recorder = &MockstackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstackService) EXPECT() *MockstackServiceMockRecorder {
	return m.recorder
}

// InternalDeleteFromDB mocks base method.
func (m *MockstackService) InternalDeleteFromDB(ctx context.Context, ID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalDeleteFromDB", ctx, ID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// InternalDeleteFromDB indicates an expected call of InternalDeleteFromDB.
func (mr *MockstackServiceMockRecorder) InternalDeleteFromDB(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalDeleteFromDB", reflect.TypeOf((*MockstackService)(nil).InternalDeleteFromDB), ctx, ID)
}

// InternalGetStack mocks base method.
func (m *MockstackService) InternalGetStack(ctx context.Context, ID string) (*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetStack", ctx, ID)
	ret0, _ := ret[0].(*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalGetStack indicates an expected call of InternalGetStack.
func (mr *MockstackServiceMockRecorder) InternalGetStack(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetStack", reflect.TypeOf((*MockstackService)(nil).InternalGetStack), ctx, ID)
}

// InternalList mocks base method.
func (m *MockstackService) InternalList(ctx context.Context, query string, args ...any) ([]*models.Stack, *errors.ServiceError) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InternalList", varargs...)
	ret0, _ := ret[0].([]*models.Stack)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalList indicates an expected call of InternalList.
func (mr *MockstackServiceMockRecorder) InternalList(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalList", reflect.TypeOf((*MockstackService)(nil).InternalList), varargs...)
}

// UpdateStackCrRevision mocks base method.
func (m *MockstackService) UpdateStackCrRevision(ctx context.Context, ID, crRevision string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStackCrRevision", ctx, ID, crRevision)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// UpdateStackCrRevision indicates an expected call of UpdateStackCrRevision.
func (mr *MockstackServiceMockRecorder) UpdateStackCrRevision(ctx, ID, crRevision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStackCrRevision", reflect.TypeOf((*MockstackService)(nil).UpdateStackCrRevision), ctx, ID, crRevision)
}

// UpdateStatus mocks base method.
func (m *MockstackService) UpdateStatus(ctx context.Context, ID string, status *models.StackStatus) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, ID, status)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockstackServiceMockRecorder) UpdateStatus(ctx, ID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockstackService)(nil).UpdateStatus), ctx, ID, status)
}

// MocksecretService is a mock of secretService interface.
type MocksecretService struct {
	ctrl     *gomock.Controller
	recorder *MocksecretServiceMockRecorder
	isgomock struct{}
}

// MocksecretServiceMockRecorder is the mock recorder for MocksecretService.
type MocksecretServiceMockRecorder struct {
	mock *MocksecretService
}

// NewMocksecretService creates a new mock instance.
func NewMocksecretService(ctrl *gomock.Controller) *MocksecretService {
	mock := &MocksecretService{ctrl: ctrl}
	mock.recorder = &MocksecretServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretService) EXPECT() *MocksecretServiceMockRecorder {
	return m.recorder
}

// InternalGetByID mocks base method.
func (m *MocksecretService) InternalGetByID(ctx context.Context, id string) (*models.Secret, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetByID", ctx, id)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalGetByID indicates an expected call of InternalGetByID.
func (mr *MocksecretServiceMockRecorder) InternalGetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetByID", reflect.TypeOf((*MocksecretService)(nil).InternalGetByID), ctx, id)
}

// MocknamespaceService is a mock of namespaceService interface.
type MocknamespaceService struct {
	ctrl     *gomock.Controller
	recorder *MocknamespaceServiceMockRecorder
	isgomock struct{}
}

// MocknamespaceServiceMockRecorder is the mock recorder for MocknamespaceService.
type MocknamespaceServiceMockRecorder struct {
	mock *MocknamespaceService
}

// NewMocknamespaceService creates a new mock instance.
func NewMocknamespaceService(ctrl *gomock.Controller) *MocknamespaceService {
	mock := &MocknamespaceService{ctrl: ctrl}
	mock.recorder = &MocknamespaceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknamespaceService) EXPECT() *MocknamespaceServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MocknamespaceService) Get(ctx context.Context, id string) (*models.Namespace, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.Namespace)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocknamespaceServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocknamespaceService)(nil).Get), ctx, id)
}

// InternalDeleteFromDB mocks base method.
func (m *MocknamespaceService) InternalDeleteFromDB(ctx context.Context, ID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalDeleteFromDB", ctx, ID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// InternalDeleteFromDB indicates an expected call of InternalDeleteFromDB.
func (mr *MocknamespaceServiceMockRecorder) InternalDeleteFromDB(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalDeleteFromDB", reflect.TypeOf((*MocknamespaceService)(nil).InternalDeleteFromDB), ctx, ID)
}

// MockvolumeService is a mock of volumeService interface.
type MockvolumeService struct {
	ctrl     *gomock.Controller
	recorder *MockvolumeServiceMockRecorder
	isgomock struct{}
}

// MockvolumeServiceMockRecorder is the mock recorder for MockvolumeService.
type MockvolumeServiceMockRecorder struct {
	mock *MockvolumeService
}

// NewMockvolumeService creates a new mock instance.
func NewMockvolumeService(ctrl *gomock.Controller) *MockvolumeService {
	mock := &MockvolumeService{ctrl: ctrl}
	mock.recorder = &MockvolumeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvolumeService) EXPECT() *MockvolumeServiceMockRecorder {
	return m.recorder
}

// InternalDeleteVolumesUsedByStackFromDB mocks base method.
func (m *MockvolumeService) InternalDeleteVolumesUsedByStackFromDB(ctx context.Context, stackID string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalDeleteVolumesUsedByStackFromDB", ctx, stackID)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// InternalDeleteVolumesUsedByStackFromDB indicates an expected call of InternalDeleteVolumesUsedByStackFromDB.
func (mr *MockvolumeServiceMockRecorder) InternalDeleteVolumesUsedByStackFromDB(ctx, stackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalDeleteVolumesUsedByStackFromDB", reflect.TypeOf((*MockvolumeService)(nil).InternalDeleteVolumesUsedByStackFromDB), ctx, stackID)
}

// ListVolumesUsedByStack mocks base method.
func (m *MockvolumeService) ListVolumesUsedByStack(ctx context.Context, stackID string) ([]*models.Volume, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolumesUsedByStack", ctx, stackID)
	ret0, _ := ret[0].([]*models.Volume)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// ListVolumesUsedByStack indicates an expected call of ListVolumesUsedByStack.
func (mr *MockvolumeServiceMockRecorder) ListVolumesUsedByStack(ctx, stackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolumesUsedByStack", reflect.TypeOf((*MockvolumeService)(nil).ListVolumesUsedByStack), ctx, stackID)
}

// MockpostgresAddonService is a mock of postgresAddonService interface.
type MockpostgresAddonService struct {
	ctrl     *gomock.Controller
	recorder *MockpostgresAddonServiceMockRecorder
	isgomock struct{}
}

// MockpostgresAddonServiceMockRecorder is the mock recorder for MockpostgresAddonService.
type MockpostgresAddonServiceMockRecorder struct {
	mock *MockpostgresAddonService
}

// NewMockpostgresAddonService creates a new mock instance.
func NewMockpostgresAddonService(ctrl *gomock.Controller) *MockpostgresAddonService {
	mock := &MockpostgresAddonService{ctrl: ctrl}
	mock.recorder = &MockpostgresAddonServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostgresAddonService) EXPECT() *MockpostgresAddonServiceMockRecorder {
	return m.recorder
}

// InternalGetCredentials mocks base method.
func (m *MockpostgresAddonService) InternalGetCredentials(ctx context.Context, addonID, database string, superuser bool) (*models.PostgresCredentials, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetCredentials", ctx, addonID, database, superuser)
	ret0, _ := ret[0].(*models.PostgresCredentials)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalGetCredentials indicates an expected call of InternalGetCredentials.
func (mr *MockpostgresAddonServiceMockRecorder) InternalGetCredentials(ctx, addonID, database, superuser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetCredentials", reflect.TypeOf((*MockpostgresAddonService)(nil).InternalGetCredentials), ctx, addonID, database, superuser)
}

// InternalGetPostgresAddon mocks base method.
func (m *MockpostgresAddonService) InternalGetPostgresAddon(ctx context.Context, id string) (*models.PostgresAddon, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalGetPostgresAddon", ctx, id)
	ret0, _ := ret[0].(*models.PostgresAddon)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// InternalGetPostgresAddon indicates an expected call of InternalGetPostgresAddon.
func (mr *MockpostgresAddonServiceMockRecorder) InternalGetPostgresAddon(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalGetPostgresAddon", reflect.TypeOf((*MockpostgresAddonService)(nil).InternalGetPostgresAddon), ctx, id)
}
